/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -IC:\Bar\nim\lib -Ic:\UserProgram\nim\pipet\src -o c:\UserProgram\nim\pipet\releasecache\@mpipetpkg@sreport.nim.c.o c:\UserProgram\nim\pipet\releasecache\@mpipetpkg@sreport.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tySequence__MEBiqQBl7pAoNbiVk1PPWQ tySequence__MEBiqQBl7pAoNbiVk1PPWQ;
typedef struct tySequence__MEBiqQBl7pAoNbiVk1PPWQ_Content tySequence__MEBiqQBl7pAoNbiVk1PPWQ_Content;
typedef struct tyObject_TestResult__ngc9cAnVBEaUVswdGxkgeYg tyObject_TestResult__ngc9cAnVBEaUVswdGxkgeYg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_Table__v9bzVWMUF1VvPkxNkpfTgpg tyObject_Table__v9bzVWMUF1VvPkxNkpfTgpg;
typedef struct tySequence__SFipDZIkFtPcrLs0AGBBjQ tySequence__SFipDZIkFtPcrLs0AGBBjQ;
typedef struct tySequence__SFipDZIkFtPcrLs0AGBBjQ_Content tySequence__SFipDZIkFtPcrLs0AGBBjQ_Content;
typedef struct tyObject_LoggercolonObjectType___LoKBwYa9ckNOHzlG1dpzgyg tyObject_LoggercolonObjectType___LoKBwYa9ckNOHzlG1dpzgyg;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
typedef struct tyObject_JsonNodeObj__O2CZVZbeIV9cSw3JlG8aKJg tyObject_JsonNodeObj__O2CZVZbeIV9cSw3JlG8aKJg;
typedef struct tyObject_OrderedTable__yrke7c9cCDaOT9aNXi69a86Dg tyObject_OrderedTable__yrke7c9cCDaOT9aNXi69a86Dg;
typedef struct tySequence__3fzGkpkBFibu62MfifCUDQ tySequence__3fzGkpkBFibu62MfifCUDQ;
typedef struct tySequence__3fzGkpkBFibu62MfifCUDQ_Content tySequence__3fzGkpkBFibu62MfifCUDQ_Content;
typedef struct tySequence__yVSZQNo6mXbAAyICpmTzgA tySequence__yVSZQNo6mXbAAyICpmTzgA;
typedef struct tySequence__yVSZQNo6mXbAAyICpmTzgA_Content tySequence__yVSZQNo6mXbAAyICpmTzgA_Content;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__xIN54dE1a4ZyAUnTpAuU2g tySequence__xIN54dE1a4ZyAUnTpAuU2g;
typedef struct tySequence__xIN54dE1a4ZyAUnTpAuU2g_Content tySequence__xIN54dE1a4ZyAUnTpAuU2g_Content;
typedef struct tyTuple__8ZxhPt1NwfElsJs8zUSV9bg tyTuple__8ZxhPt1NwfElsJs8zUSV9bg;
typedef struct tyTuple__VtrNzwFntzmaYRhDHE7gKw tyTuple__VtrNzwFntzmaYRhDHE7gKw;
typedef struct tyObject_StackTraceEntry__2ELMRvKL5HlwpyV9cRIuTmw tyObject_StackTraceEntry__2ELMRvKL5HlwpyV9cRIuTmw;
struct tySequence__MEBiqQBl7pAoNbiVk1PPWQ {
  NI len; tySequence__MEBiqQBl7pAoNbiVk1PPWQ_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_TestResult__ngc9cAnVBEaUVswdGxkgeYg {
	NimStringV2 id;
	NimStringV2 desc;
	NimStringV2 status;
	NF durationSec;
	NI expectStatus;
	NI actualStatus;
	NimStringV2 diff;
	NimStringV2 actualBody;
	NimStringV2 expectBody;
	NimStringV2 skipFields;
	NimStringV2 tags;
};
typedef NU8 tyEnum_FileMode__9aETr7eq5EZaB8QOennw9cKg;
struct tySequence__SFipDZIkFtPcrLs0AGBBjQ {
  NI len; tySequence__SFipDZIkFtPcrLs0AGBBjQ_Content* p;
};
struct tyObject_Table__v9bzVWMUF1VvPkxNkpfTgpg {
	tySequence__SFipDZIkFtPcrLs0AGBBjQ data;
	NI counter;
};
typedef NimStringV2 tyArray__YgExxhfgKcesA5EOUj1MOA[1];
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
	NimStringV2 Field0;
	NimStringV2 Field1;
};
typedef tyTuple__UV3llMMYFckfui8YMBuUZA tyArray__OnzEA2l6u7CA8vqyXXXq7Q[1];
typedef NU8 tyEnum_JsonNodeKind__T9cPH25F5jQg3TdbvGfA9b6w;
struct tySequence__3fzGkpkBFibu62MfifCUDQ {
  NI len; tySequence__3fzGkpkBFibu62MfifCUDQ_Content* p;
};
struct tyObject_OrderedTable__yrke7c9cCDaOT9aNXi69a86Dg {
	tySequence__3fzGkpkBFibu62MfifCUDQ data;
	NI counter;
	NI first;
	NI last;
};
struct tySequence__yVSZQNo6mXbAAyICpmTzgA {
  NI len; tySequence__yVSZQNo6mXbAAyICpmTzgA_Content* p;
};
struct tyObject_JsonNodeObj__O2CZVZbeIV9cSw3JlG8aKJg {
	NIM_BOOL isUnquoted;
	tyEnum_JsonNodeKind__T9cPH25F5jQg3TdbvGfA9b6w kind;
union{
	struct {
	NimStringV2 str;
} _kind_1;
	struct {
	NI64 num;
} _kind_2;
	struct {
	NF fnum;
} _kind_3;
	struct {
	NIM_BOOL bval;
} _kind_4;
	struct {
	tyObject_OrderedTable__yrke7c9cCDaOT9aNXi69a86Dg fields;
} _kind_6;
	struct {
	tySequence__yVSZQNo6mXbAAyICpmTzgA elems;
} _kind_7;
};
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__xIN54dE1a4ZyAUnTpAuU2g {
  NI len; tySequence__xIN54dE1a4ZyAUnTpAuU2g_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__xIN54dE1a4ZyAUnTpAuU2g trace;
	Exception* up;
};
typedef NU8 tyEnum_FloatFormatMode__NktTD9agsSu9bXX0rEiwGseg;
typedef tyTuple__UV3llMMYFckfui8YMBuUZA tyArray__oMvlj9bYpRbsICDDlYDUECg[2];
struct tySequence__MEBiqQBl7pAoNbiVk1PPWQ_Content { NI cap; tyObject_TestResult__ngc9cAnVBEaUVswdGxkgeYg data[SEQ_DECL_SIZE]; };
struct tyTuple__8ZxhPt1NwfElsJs8zUSV9bg {
	NI Field0;
	NimStringV2 Field1;
	NimStringV2 Field2;
};
struct tySequence__SFipDZIkFtPcrLs0AGBBjQ_Content { NI cap; tyTuple__8ZxhPt1NwfElsJs8zUSV9bg data[SEQ_DECL_SIZE]; };
struct tyTuple__VtrNzwFntzmaYRhDHE7gKw {
	NI Field0;
	NI Field1;
	NimStringV2 Field2;
	tyObject_JsonNodeObj__O2CZVZbeIV9cSw3JlG8aKJg* Field3;
};
struct tySequence__3fzGkpkBFibu62MfifCUDQ_Content { NI cap; tyTuple__VtrNzwFntzmaYRhDHE7gKw data[SEQ_DECL_SIZE]; };
struct tySequence__yVSZQNo6mXbAAyICpmTzgA_Content { NI cap; tyObject_JsonNodeObj__O2CZVZbeIV9cSw3JlG8aKJg* data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__2ELMRvKL5HlwpyV9cRIuTmw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__xIN54dE1a4ZyAUnTpAuU2g_Content { NI cap; tyObject_StackTraceEntry__2ELMRvKL5HlwpyV9cRIuTmw data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(FILE*, open__stdZsyncio_u566)(NimStringV2 filename_p0, tyEnum_FileMode__9aETr7eq5EZaB8QOennw9cKg mode_p1, NI bufSize_p2);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, writeRows__pipetpkgZreport_u11)(FILE* f_p0, tySequence__MEBiqQBl7pAoNbiVk1PPWQ results_p1);
static N_INLINE(void, writeLine__pipetpkgZlogger_u576)(FILE* f_p0, NimStringV2* x_p1, NI x_p1Len_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, write__stdZsyncio_u272)(FILE* f_p0, NimStringV2 s_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, debug__pipetpkgZlogger_u613)(tyObject_LoggercolonObjectType___LoKBwYa9ckNOHzlG1dpzgyg* logger_p0, NimStringV2 message_p1, tyObject_Table__v9bzVWMUF1VvPkxNkpfTgpg fields_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__v9bzVWMUF1VvPkxNkpfTgpg, toTable__pipetpkgZcore_u1321)(tyTuple__UV3llMMYFckfui8YMBuUZA* pairs_p0, NI pairs_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuReplaceStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NimStringV2 by_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, normalizeBody__pipetpkgZreport_u7)(NimStringV2 s_p0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2723)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__O2CZVZbeIV9cSw3JlG8aKJg*, parseJson__pureZjson_u5759)(NimStringV2 buffer_p0, NIM_BOOL rawIntegers_p1, NIM_BOOL rawFloats_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u321)(tyObject_JsonNodeObj__O2CZVZbeIV9cSw3JlG8aKJg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pureZjson_u4984)(tyObject_JsonNodeObj__O2CZVZbeIV9cSw3JlG8aKJg* node_p0);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u3688)(Exception** dest_p0, Exception* src_p1, NIM_BOOL cyclic_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuformatFloat)(NF f_p0, tyEnum_FloatFormatMode__NktTD9agsSu9bXX0rEiwGseg format_p1, NI precision_p2, NIM_CHAR decimalSep_p3);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pipetpkgZlogger_u595)(tyObject_Table__v9bzVWMUF1VvPkxNkpfTgpg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, info__pipetpkgZlogger_u619)(tyObject_LoggercolonObjectType___LoKBwYa9ckNOHzlG1dpzgyg* logger_p0, NimStringV2 message_p1, tyObject_Table__v9bzVWMUF1VvPkxNkpfTgpg fields_p2);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(void, close__stdZsyncio_u290)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__MEBiqQBl7pAoNbiVk1PPWQ, newSeq__pipetpkgZreport_u235)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(void, add__pipetpkgZreport_u257)(tySequence__MEBiqQBl7pAoNbiVk1PPWQ* x_p0, tyObject_TestResult__ngc9cAnVBEaUVswdGxkgeYg* y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdup___pipetpkgZcore_u2984)(tyObject_TestResult__ngc9cAnVBEaUVswdGxkgeYg* src_p0, tyObject_TestResult__ngc9cAnVBEaUVswdGxkgeYg* Result);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pipetpkgZreport_u78)(tySequence__MEBiqQBl7pAoNbiVk1PPWQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, debug__pipetpkgZlogger_u637)(tyObject_LoggercolonObjectType___LoKBwYa9ckNOHzlG1dpzgyg* logger_p0, NimStringV2 message_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pipetpkgZreport_u81)(tySequence__MEBiqQBl7pAoNbiVk1PPWQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuRepeatStr)(NimStringV2 s_p0, NI n_p1);
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_2 = { 1 | NIM_STRLIT_FLAG, "\012" };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_3 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_2};
static const struct {
  NI cap; NIM_CHAR data[99+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_5 = { 99 | NIM_STRLIT_FLAG, "id|desc|tags|status|duration_s|expect_status|actual_status|diff|actual_body|expect_body|skip_fields" };
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_6 = { 15 | NIM_STRLIT_FLAG, "\345\206\231\345\205\245\346\212\245\345\221\212\350\241\214" };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_7 = {15, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_6};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_8 = { 5 | NIM_STRLIT_FLAG, "count" };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_9 = {5, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_8};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_10 = { 1 | NIM_STRLIT_FLAG, "|" };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_11 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_10};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_12 = { 1 | NIM_STRLIT_FLAG, ";" };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_13 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_12};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_14 = { 2 | NIM_STRLIT_FLAG, "\015\012" };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_15 = {2, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_14};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_16 = { 1 | NIM_STRLIT_FLAG, " " };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_17 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_16};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_18 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_2};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_19 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_16};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_20 = { 1 | NIM_STRLIT_FLAG, "\015" };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_21 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_20};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_22 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_16};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_23 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_10};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_24 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_12};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_25 = {2, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_14};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_26 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_16};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_27 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_2};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_28 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_16};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_29 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_20};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_30 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_16};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_31 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_10};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_32 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_12};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_33 = {2, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_14};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_34 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_16};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_35 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_2};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_36 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_16};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_37 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_20};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_38 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_16};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_39 = { 3 | NIM_STRLIT_FLAG, "N/A" };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_40 = {3, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_39};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_41 = {2, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_14};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_42 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_43 = {0, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_42};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_44 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_2};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_45 = {0, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_42};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_46 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_20};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_47 = {0, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_42};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_48 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_10};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_49 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_12};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_50 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_10};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_51 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_12};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_52 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_10};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_53 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_12};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_54 = {2, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_14};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_55 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_16};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_56 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_2};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_57 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_16};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_58 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_20};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_59 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_16};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_60 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_10};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_61 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_10};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_62 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_10};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_63 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_10};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_64 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_10};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_65 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_10};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_66 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_10};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_67 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_10};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_68 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_10};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_69 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_10};
static const struct {
  NI cap; NIM_CHAR data[90+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_70 = { 90 | NIM_STRLIT_FLAG, "iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_71 = {90, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_70};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_72 = { 21 | NIM_STRLIT_FLAG, "\345\205\250\351\207\217\346\212\245\345\221\212\345\267\262\347\224\237\346\210\220" };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_73 = {21, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_72};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_74 = { 4 | NIM_STRLIT_FLAG, "file" };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_75 = {4, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_74};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_76 = { 4 | NIM_STRLIT_FLAG, "rows" };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_77 = {4, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_76};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_78 = { 22 | NIM_STRLIT_FLAG, "\012PSV \346\212\245\345\221\212\345\267\262\344\277\235\345\255\230: " };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_79 = {22, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_78};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_80 = { 4 | NIM_STRLIT_FLAG, "FAIL" };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_81 = {4, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_80};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_82 = {90, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_70};
static const struct {
  NI cap; NIM_CHAR data[39+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_83 = { 39 | NIM_STRLIT_FLAG, "\346\227\240\345\244\261\350\264\245\347\224\250\344\276\213\357\274\214\344\270\215\347\224\237\346\210\220\345\274\202\345\270\270\346\212\245\345\221\212" };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_84 = {39, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_83};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_85 = { 21 | NIM_STRLIT_FLAG, "\345\274\202\345\270\270\346\212\245\345\221\212\345\267\262\347\224\237\346\210\220" };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_86 = {21, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_85};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_87 = {4, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_74};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_88 = {4, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_76};
static const struct {
  NI cap; NIM_CHAR data[34+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_89 = { 34 | NIM_STRLIT_FLAG, "\345\274\202\345\270\270\347\224\250\344\276\213 PSV \346\212\245\345\221\212\345\267\262\344\277\235\345\255\230: " };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_90 = {34, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_89};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_91 = {4, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_80};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_92 = {90, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_70};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_93 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_2};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_94 = { 1 | NIM_STRLIT_FLAG, "=" };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_95 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_94};
static const struct {
  NI cap; NIM_CHAR data[39+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_97 = { 39 | NIM_STRLIT_FLAG, "\345\244\261\350\264\245\347\224\250\344\276\213\350\257\246\346\203\205\357\274\210\345\256\236\351\231\205\345\223\215\345\272\224\344\275\223\357\274\211" };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_98 = {1, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_94};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_99 = { 2 | NIM_STRLIT_FLAG, "\012[" };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_100 = {2, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_99};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_101 = { 2 | NIM_STRLIT_FLAG, "] " };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_102 = {2, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_101};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_103 = { 10 | NIM_STRLIT_FLAG, "  \345\267\256\345\274\202: " };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_104 = {10, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_103};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__QuD9cD3eGfqnfb8YjWMt5ow_105 = { 19 | NIM_STRLIT_FLAG, "  \345\256\236\351\231\205\345\223\215\345\272\224\344\275\223: " };
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_106 = {19, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_105};
static const NimStringV2 TM__QuD9cD3eGfqnfb8YjWMt5ow_107 = {90, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_70};
static NIM_CONST tyArray__YgExxhfgKcesA5EOUj1MOA TM__QuD9cD3eGfqnfb8YjWMt5ow_4 = {{99, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_5}}
;
static NIM_CONST tyArray__YgExxhfgKcesA5EOUj1MOA TM__QuD9cD3eGfqnfb8YjWMt5ow_96 = {{39, (NimStrPayload*)&TM__QuD9cD3eGfqnfb8YjWMt5ow_97}}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4167;
extern tyObject_LoggercolonObjectType___LoKBwYa9ckNOHzlG1dpzgyg* gLogger__pipetpkgZlogger_u94;
extern NIM_THREADVAR Exception* currException__system_u3655;
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pipetpkgZreport_u81)(tySequence__MEBiqQBl7pAoNbiVk1PPWQ dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].tags.p && !(dest_p0.p->data[colontmp_].tags.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].tags.p);
}
			if (dest_p0.p->data[colontmp_].skipFields.p && !(dest_p0.p->data[colontmp_].skipFields.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].skipFields.p);
}
			if (dest_p0.p->data[colontmp_].expectBody.p && !(dest_p0.p->data[colontmp_].expectBody.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].expectBody.p);
}
			if (dest_p0.p->data[colontmp_].actualBody.p && !(dest_p0.p->data[colontmp_].actualBody.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].actualBody.p);
}
			if (dest_p0.p->data[colontmp_].diff.p && !(dest_p0.p->data[colontmp_].diff.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].diff.p);
}
			if (dest_p0.p->data[colontmp_].status.p && !(dest_p0.p->data[colontmp_].status.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].status.p);
}
			if (dest_p0.p->data[colontmp_].desc.p && !(dest_p0.p->data[colontmp_].desc.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].desc.p);
}
			if (dest_p0.p->data[colontmp_].id.p && !(dest_p0.p->data[colontmp_].id.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].id.p);
}
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_TestResult__ngc9cAnVBEaUVswdGxkgeYg));
}
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4167);
	return result;
}
static N_INLINE(void, writeLine__pipetpkgZlogger_u576)(FILE* f_p0, NimStringV2* x_p1, NI x_p1Len_0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NimStringV2* i_1;
		NI i_2;
		i_1 = (NimStringV2*)0;
		i_2 = ((NI)0);
		{
			while (1) {
				if (!(i_2 < x_p1Len_0)) goto LA3;
				if (i_2 < 0 || i_2 >= x_p1Len_0){ raiseIndexError2(i_2,x_p1Len_0-1); goto BeforeRet_;
				}
				i_1 = (&x_p1[i_2]);
				write__stdZsyncio_u272(f_p0, (*i_1));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				i_2 += ((NI)1);
			} LA3: ;
		}
	}
	write__stdZsyncio_u272(f_p0, TM__QuD9cD3eGfqnfb8YjWMt5ow_3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
{	result = NIM_FALSE;
	alen_1 = a_p0.len;
	blen_1 = b_p1.len;
	{
		if (!(alen_1 == blen_1)) goto LA3_;
		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		result = equalMem__system_u1763(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
}
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	T1_ = (NIM_BOOL)0;
	T1_ = (targetDepth_p1 <= (*source_p0).depth);
	if (!(T1_)) goto LA2_;
	T1_ = ((*source_p0).display[targetDepth_p1] == token_p2);
LA2_: ;
	result = T1_;
	return result;
}
static N_INLINE(Exception*, nimBorrowCurrentException)(void) {
	Exception* result;
	result = currException__system_u3655;
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___system_u3688(&currException__system_u3655, (*currException__system_u3655).up, NIM_FALSE);
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, normalizeBody__pipetpkgZreport_u7)(NimStringV2 s_p0) {
	NimStringV2 result;
	tyObject_JsonNodeObj__O2CZVZbeIV9cSw3JlG8aKJg* node_1;
	tyObject_JsonNodeObj__O2CZVZbeIV9cSw3JlG8aKJg* T9_;
	NimStringV2 T10_;
NIM_BOOL oldNimErrFin8_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = eqStrings(s_p0, TM__QuD9cD3eGfqnfb8YjWMt5ow_40);
		if (T3_) goto LA4_;
		T3_ = (s_p0.len == ((NI)0));
LA4_: ;
		if (!T3_) goto LA5_;
		eqcopy___system_u2723((&result), s_p0);
		goto BeforeRet_;
	}
LA5_: ;
	node_1 = NIM_NIL;
	T9_ = NIM_NIL;
	T9_ = parseJson__pureZjson_u5759(s_p0, NIM_FALSE, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u321(T9_); goto LA8_;}
	node_1 = T9_;
	T10_.len = 0; T10_.p = NIM_NIL;
	T10_ = dollar___pureZjson_u4984(node_1);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T10_); goto LA8_;}
	result = T10_;
	eqdestroy___pureZjson_u321(node_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
	goto BeforeRet_;
	{
		LA8_:;
	}
	{
		oldNimErrFin8_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___pureZjson_u321(node_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
		*nimErr_ = oldNimErrFin8_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
	if (NIM_UNLIKELY(*nimErr_)) {
		LA7_:;
		if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 4, 1530822144)) {
			NimStringV2 colontmpD_;
			NimStringV2 colontmpD__2;
			NimStringV2 T17_;
			NimStringV2 T18_;
			NimStringV2 T19_;
			*nimErr_ = NIM_FALSE;
			colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
			colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
			T17_.len = 0; T17_.p = NIM_NIL;
			T17_ = nsuReplaceStr(s_p0, TM__QuD9cD3eGfqnfb8YjWMt5ow_41, TM__QuD9cD3eGfqnfb8YjWMt5ow_43);
			if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T17_); goto LA16_;}
			colontmpD_ = T17_;
			T18_.len = 0; T18_.p = NIM_NIL;
			T18_ = nsuReplaceStr(colontmpD_, TM__QuD9cD3eGfqnfb8YjWMt5ow_44, TM__QuD9cD3eGfqnfb8YjWMt5ow_45);
			if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T18_); goto LA16_;}
			colontmpD__2 = T18_;
			T19_.len = 0; T19_.p = NIM_NIL;
			T19_ = nsuReplaceStr(colontmpD__2, TM__QuD9cD3eGfqnfb8YjWMt5ow_46, TM__QuD9cD3eGfqnfb8YjWMt5ow_47);
			if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T19_); goto LA16_;}
			result = T19_;
			if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
			popCurrentException();
			goto BeforeRet_;
			{
				LA16_:;
			}
			{
				if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
				if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
			popCurrentException();
			LA14_:;
		}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, writeRows__pipetpkgZreport_u11)(FILE* f_p0, tySequence__MEBiqQBl7pAoNbiVk1PPWQ results_p1) {
	NimStringV2 colontmpD_;
	tyObject_Table__v9bzVWMUF1VvPkxNkpfTgpg colontmpD__2;
	tyArray__OnzEA2l6u7CA8vqyXXXq7Q T2_;
	NI T3_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimZeroMem((void*)(&colontmpD__2), sizeof(tyObject_Table__v9bzVWMUF1VvPkxNkpfTgpg));
	writeLine__pipetpkgZlogger_u576(f_p0, TM__QuD9cD3eGfqnfb8YjWMt5ow_4, 1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[0].Field0 = TM__QuD9cD3eGfqnfb8YjWMt5ow_9;
	T3_ = results_p1.len;
	colontmpD_ = dollar___systemZdollars_u14(T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[0].Field1 = colontmpD_;
	colontmpD__2 = toTable__pipetpkgZcore_u1321(T2_, 1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	debug__pipetpkgZlogger_u613(gLogger__pipetpkgZlogger_u94, TM__QuD9cD3eGfqnfb8YjWMt5ow_7, colontmpD__2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		tyObject_TestResult__ngc9cAnVBEaUVswdGxkgeYg* r_1;
		NI i_1;
		NI L_1;
		NI T5_;
		r_1 = (tyObject_TestResult__ngc9cAnVBEaUVswdGxkgeYg*)0;
		i_1 = ((NI)0);
		T5_ = results_p1.len;
		L_1 = T5_;
		{
			while (1) {
				NimStringV2 safeDiff_1;
				NimStringV2 colontmpD__3;
				NimStringV2 colontmpD__4;
				NimStringV2 colontmpD__5;
				NimStringV2 safeDesc_1;
				NimStringV2 colontmpD__6;
				NimStringV2 colontmpD__7;
				NimStringV2 colontmpD__8;
				NimStringV2 safeTags_1;
				NimStringV2 colontmpD__9;
				NimStringV2 colontmpD__10;
				NimStringV2 colontmpD__11;
				NimStringV2 safeBody_1;
				NimStringV2 colontmpD__12;
				NimStringV2 safeExpect_1;
				NimStringV2 colontmpD__13;
				NimStringV2 safeSkip_1;
				NimStringV2 colontmpD__14;
				NimStringV2 colontmpD__15;
				NimStringV2 colontmpD__16;
				NimStringV2 durationStr_1;
				NimStringV2 colontmpD__17;
				NimStringV2 colontmpD__18;
				NimStringV2 colontmpD__19;
				tyArray__YgExxhfgKcesA5EOUj1MOA T9_;
				NimStringV2 T10_;
				if (!(i_1 < L_1)) goto LA7;
				safeDiff_1.len = 0; safeDiff_1.p = NIM_NIL;
				colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
				colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
				colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
				safeDesc_1.len = 0; safeDesc_1.p = NIM_NIL;
				colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
				colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
				colontmpD__8.len = 0; colontmpD__8.p = NIM_NIL;
				safeTags_1.len = 0; safeTags_1.p = NIM_NIL;
				colontmpD__9.len = 0; colontmpD__9.p = NIM_NIL;
				colontmpD__10.len = 0; colontmpD__10.p = NIM_NIL;
				colontmpD__11.len = 0; colontmpD__11.p = NIM_NIL;
				safeBody_1.len = 0; safeBody_1.p = NIM_NIL;
				colontmpD__12.len = 0; colontmpD__12.p = NIM_NIL;
				safeExpect_1.len = 0; safeExpect_1.p = NIM_NIL;
				colontmpD__13.len = 0; colontmpD__13.p = NIM_NIL;
				safeSkip_1.len = 0; safeSkip_1.p = NIM_NIL;
				colontmpD__14.len = 0; colontmpD__14.p = NIM_NIL;
				colontmpD__15.len = 0; colontmpD__15.p = NIM_NIL;
				colontmpD__16.len = 0; colontmpD__16.p = NIM_NIL;
				durationStr_1.len = 0; durationStr_1.p = NIM_NIL;
				colontmpD__17.len = 0; colontmpD__17.p = NIM_NIL;
				colontmpD__18.len = 0; colontmpD__18.p = NIM_NIL;
				colontmpD__19.len = 0; colontmpD__19.p = NIM_NIL;
				if (i_1 < 0 || i_1 >= results_p1.len){ raiseIndexError2(i_1,results_p1.len-1); goto LA8_;
				}
				r_1 = (&results_p1.p->data[i_1]);
				colontmpD__3 = nsuReplaceStr((*r_1).diff, TM__QuD9cD3eGfqnfb8YjWMt5ow_11, TM__QuD9cD3eGfqnfb8YjWMt5ow_13);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				colontmpD__4 = nsuReplaceStr(colontmpD__3, TM__QuD9cD3eGfqnfb8YjWMt5ow_15, TM__QuD9cD3eGfqnfb8YjWMt5ow_17);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				colontmpD__5 = nsuReplaceStr(colontmpD__4, TM__QuD9cD3eGfqnfb8YjWMt5ow_18, TM__QuD9cD3eGfqnfb8YjWMt5ow_19);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				safeDiff_1 = nsuReplaceStr(colontmpD__5, TM__QuD9cD3eGfqnfb8YjWMt5ow_21, TM__QuD9cD3eGfqnfb8YjWMt5ow_22);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				colontmpD__6 = nsuReplaceStr((*r_1).desc, TM__QuD9cD3eGfqnfb8YjWMt5ow_23, TM__QuD9cD3eGfqnfb8YjWMt5ow_24);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				colontmpD__7 = nsuReplaceStr(colontmpD__6, TM__QuD9cD3eGfqnfb8YjWMt5ow_25, TM__QuD9cD3eGfqnfb8YjWMt5ow_26);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				colontmpD__8 = nsuReplaceStr(colontmpD__7, TM__QuD9cD3eGfqnfb8YjWMt5ow_27, TM__QuD9cD3eGfqnfb8YjWMt5ow_28);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				safeDesc_1 = nsuReplaceStr(colontmpD__8, TM__QuD9cD3eGfqnfb8YjWMt5ow_29, TM__QuD9cD3eGfqnfb8YjWMt5ow_30);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				colontmpD__9 = nsuReplaceStr((*r_1).tags, TM__QuD9cD3eGfqnfb8YjWMt5ow_31, TM__QuD9cD3eGfqnfb8YjWMt5ow_32);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				colontmpD__10 = nsuReplaceStr(colontmpD__9, TM__QuD9cD3eGfqnfb8YjWMt5ow_33, TM__QuD9cD3eGfqnfb8YjWMt5ow_34);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				colontmpD__11 = nsuReplaceStr(colontmpD__10, TM__QuD9cD3eGfqnfb8YjWMt5ow_35, TM__QuD9cD3eGfqnfb8YjWMt5ow_36);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				safeTags_1 = nsuReplaceStr(colontmpD__11, TM__QuD9cD3eGfqnfb8YjWMt5ow_37, TM__QuD9cD3eGfqnfb8YjWMt5ow_38);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				colontmpD__12 = normalizeBody__pipetpkgZreport_u7((*r_1).actualBody);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				safeBody_1 = nsuReplaceStr(colontmpD__12, TM__QuD9cD3eGfqnfb8YjWMt5ow_48, TM__QuD9cD3eGfqnfb8YjWMt5ow_49);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				colontmpD__13 = normalizeBody__pipetpkgZreport_u7((*r_1).expectBody);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				safeExpect_1 = nsuReplaceStr(colontmpD__13, TM__QuD9cD3eGfqnfb8YjWMt5ow_50, TM__QuD9cD3eGfqnfb8YjWMt5ow_51);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				colontmpD__14 = nsuReplaceStr((*r_1).skipFields, TM__QuD9cD3eGfqnfb8YjWMt5ow_52, TM__QuD9cD3eGfqnfb8YjWMt5ow_53);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				colontmpD__15 = nsuReplaceStr(colontmpD__14, TM__QuD9cD3eGfqnfb8YjWMt5ow_54, TM__QuD9cD3eGfqnfb8YjWMt5ow_55);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				colontmpD__16 = nsuReplaceStr(colontmpD__15, TM__QuD9cD3eGfqnfb8YjWMt5ow_56, TM__QuD9cD3eGfqnfb8YjWMt5ow_57);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				safeSkip_1 = nsuReplaceStr(colontmpD__16, TM__QuD9cD3eGfqnfb8YjWMt5ow_58, TM__QuD9cD3eGfqnfb8YjWMt5ow_59);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				durationStr_1 = nsuformatFloat((*r_1).durationSec, ((tyEnum_FloatFormatMode__NktTD9agsSu9bXX0rEiwGseg)1), ((NI)3), 46);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				T10_.len = 0; T10_.p = NIM_NIL;
				colontmpD__17 = dollar___systemZdollars_u14((*r_1).expectStatus);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				colontmpD__18 = dollar___systemZdollars_u14((*r_1).actualStatus);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				T10_ = rawNewString((*r_1).id.len + safeDesc_1.len + safeTags_1.len + (*r_1).status.len + durationStr_1.len + colontmpD__17.len + colontmpD__18.len + safeDiff_1.len + safeBody_1.len + safeExpect_1.len + safeSkip_1.len + 10);
appendString((&T10_), (*r_1).id);
appendString((&T10_), TM__QuD9cD3eGfqnfb8YjWMt5ow_60);
appendString((&T10_), safeDesc_1);
appendString((&T10_), TM__QuD9cD3eGfqnfb8YjWMt5ow_61);
appendString((&T10_), safeTags_1);
appendString((&T10_), TM__QuD9cD3eGfqnfb8YjWMt5ow_62);
appendString((&T10_), (*r_1).status);
appendString((&T10_), TM__QuD9cD3eGfqnfb8YjWMt5ow_63);
appendString((&T10_), durationStr_1);
appendString((&T10_), TM__QuD9cD3eGfqnfb8YjWMt5ow_64);
appendString((&T10_), colontmpD__17);
appendString((&T10_), TM__QuD9cD3eGfqnfb8YjWMt5ow_65);
appendString((&T10_), colontmpD__18);
appendString((&T10_), TM__QuD9cD3eGfqnfb8YjWMt5ow_66);
appendString((&T10_), safeDiff_1);
appendString((&T10_), TM__QuD9cD3eGfqnfb8YjWMt5ow_67);
appendString((&T10_), safeBody_1);
appendString((&T10_), TM__QuD9cD3eGfqnfb8YjWMt5ow_68);
appendString((&T10_), safeExpect_1);
appendString((&T10_), TM__QuD9cD3eGfqnfb8YjWMt5ow_69);
appendString((&T10_), safeSkip_1);
				colontmpD__19 = T10_;
				T9_[0] = colontmpD__19;
				writeLine__pipetpkgZlogger_u576(f_p0, T9_, 1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				i_1 += ((NI)1);
				{
					NI T13_;
					T13_ = results_p1.len;
					if (!!((T13_ == L_1))) goto LA14_;
					failedAssertImpl__stdZassertions_u95(TM__QuD9cD3eGfqnfb8YjWMt5ow_71);
					if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				}
LA14_: ;
				{
					LA8_:;
				}
				{
					if (colontmpD__19.p && !(colontmpD__19.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__19.p);
}
					if (colontmpD__18.p && !(colontmpD__18.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__18.p);
}
					if (colontmpD__17.p && !(colontmpD__17.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__17.p);
}
					if (durationStr_1.p && !(durationStr_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(durationStr_1.p);
}
					if (colontmpD__16.p && !(colontmpD__16.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__16.p);
}
					if (colontmpD__15.p && !(colontmpD__15.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__15.p);
}
					if (colontmpD__14.p && !(colontmpD__14.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__14.p);
}
					if (safeSkip_1.p && !(safeSkip_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(safeSkip_1.p);
}
					if (colontmpD__13.p && !(colontmpD__13.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__13.p);
}
					if (safeExpect_1.p && !(safeExpect_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(safeExpect_1.p);
}
					if (colontmpD__12.p && !(colontmpD__12.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__12.p);
}
					if (safeBody_1.p && !(safeBody_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(safeBody_1.p);
}
					if (colontmpD__11.p && !(colontmpD__11.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__11.p);
}
					if (colontmpD__10.p && !(colontmpD__10.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__10.p);
}
					if (colontmpD__9.p && !(colontmpD__9.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__9.p);
}
					if (safeTags_1.p && !(safeTags_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(safeTags_1.p);
}
					if (colontmpD__8.p && !(colontmpD__8.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__8.p);
}
					if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
					if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
					if (safeDesc_1.p && !(safeDesc_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(safeDesc_1.p);
}
					if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
					if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
					if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
					if (safeDiff_1.p && !(safeDiff_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(safeDiff_1.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			} LA7: ;
		}
	}
	{
		LA1_:;
	}
	{
		eqdestroy___pipetpkgZlogger_u595((&colontmpD__2));
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, writePsvReport__pipetpkgZreport_u204)(tySequence__MEBiqQBl7pAoNbiVk1PPWQ results_p0, NimStringV2 filename_p1) {
	FILE* f_1;
	NimStringV2 colontmpD_;
	tyObject_Table__v9bzVWMUF1VvPkxNkpfTgpg colontmpD__2;
	NimStringV2 colontmpD__3;
	tyArray__oMvlj9bYpRbsICDDlYDUECg T3_;
	NI T4_;
	tyArray__YgExxhfgKcesA5EOUj1MOA T5_;
	NimStringV2 T6_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	f_1 = open__stdZsyncio_u566(filename_p1, ((tyEnum_FileMode__9aETr7eq5EZaB8QOennw9cKg)1), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimZeroMem((void*)(&colontmpD__2), sizeof(tyObject_Table__v9bzVWMUF1VvPkxNkpfTgpg));
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	writeRows__pipetpkgZreport_u11(f_1, results_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
	T3_[0].Field0 = TM__QuD9cD3eGfqnfb8YjWMt5ow_75;
	T3_[0].Field1 = filename_p1;
	T3_[1].Field0 = TM__QuD9cD3eGfqnfb8YjWMt5ow_77;
	T4_ = results_p0.len;
	colontmpD_ = dollar___systemZdollars_u14(T4_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
	T3_[1].Field1 = colontmpD_;
	colontmpD__2 = toTable__pipetpkgZcore_u1321(T3_, 2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
	info__pipetpkgZlogger_u619(gLogger__pipetpkgZlogger_u94, TM__QuD9cD3eGfqnfb8YjWMt5ow_73, colontmpD__2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
	T6_.len = 0; T6_.p = NIM_NIL;
	T6_ = rawNewString(filename_p1.len + 22);
appendString((&T6_), TM__QuD9cD3eGfqnfb8YjWMt5ow_79);
appendString((&T6_), filename_p1);
	colontmpD__3 = T6_;
	T5_[0] = colontmpD__3;
	echoBinSafe(T5_, 1);
	{
		LA2_:;
	}
	{
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		eqdestroy___pipetpkgZlogger_u595((&colontmpD__2));
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		close__stdZsyncio_u290(f_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pipetpkgZreport_u78)(tySequence__MEBiqQBl7pAoNbiVk1PPWQ* dest_p0) {
	(*dest_p0).len = 0; (*dest_p0).p = NIM_NIL;
}
N_LIB_PRIVATE N_NIMCALL(void, writeErrorPsvReport__pipetpkgZreport_u215)(tySequence__MEBiqQBl7pAoNbiVk1PPWQ results_p0, NimStringV2 filename_p1) {
	tySequence__MEBiqQBl7pAoNbiVk1PPWQ fails_1;
	tySequence__MEBiqQBl7pAoNbiVk1PPWQ resultX60gensym2__1;
	FILE* f_1;
	NimStringV2 colontmpD__2;
	tyObject_Table__v9bzVWMUF1VvPkxNkpfTgpg colontmpD__3;
	NimStringV2 colontmpD__4;
	tyArray__oMvlj9bYpRbsICDDlYDUECg T23_;
	NI T24_;
	tyArray__YgExxhfgKcesA5EOUj1MOA T25_;
	NimStringV2 T26_;
NIM_BOOL oldNimErrFin21_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	fails_1.len = 0; fails_1.p = NIM_NIL;
	resultX60gensym2__1.len = 0; resultX60gensym2__1.p = NIM_NIL;
	resultX60gensym2__1 = newSeq__pipetpkgZreport_u235(((NI)0));
	{
		tyObject_TestResult__ngc9cAnVBEaUVswdGxkgeYg* it_1;
		NI i_1;
		NI L_1;
		NI T3_;
		it_1 = (tyObject_TestResult__ngc9cAnVBEaUVswdGxkgeYg*)0;
		i_1 = ((NI)0);
		T3_ = results_p0.len;
		L_1 = T3_;
		{
			while (1) {
				if (!(i_1 < L_1)) goto LA5;
				if (i_1 < 0 || i_1 >= results_p0.len){ raiseIndexError2(i_1,results_p0.len-1); goto LA1_;
				}
				it_1 = (&results_p0.p->data[i_1]);
				{
					tyObject_TestResult__ngc9cAnVBEaUVswdGxkgeYg colontmpD_;
					tyObject_TestResult__ngc9cAnVBEaUVswdGxkgeYg T10_;
					if (!eqStrings((*it_1).status, TM__QuD9cD3eGfqnfb8YjWMt5ow_81)) goto LA8_;
					nimZeroMem((void*)(&T10_), sizeof(tyObject_TestResult__ngc9cAnVBEaUVswdGxkgeYg));
					eqdup___pipetpkgZcore_u2984((&(*it_1)), (&T10_));
					colontmpD_ = T10_;
					add__pipetpkgZreport_u257((&resultX60gensym2__1), (&colontmpD_));
				}
LA8_: ;
				i_1 += ((NI)1);
				{
					NI T13_;
					T13_ = results_p0.len;
					if (!!((T13_ == L_1))) goto LA14_;
					failedAssertImpl__stdZassertions_u95(TM__QuD9cD3eGfqnfb8YjWMt5ow_82);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
LA14_: ;
			} LA5: ;
		}
	}
	fails_1 = resultX60gensym2__1;
	eqwasMoved___pipetpkgZreport_u78((&resultX60gensym2__1));
	{
		NI T18_;
		T18_ = fails_1.len;
		if (!(T18_ == ((NI)0))) goto LA19_;
		debug__pipetpkgZlogger_u637(gLogger__pipetpkgZlogger_u94, TM__QuD9cD3eGfqnfb8YjWMt5ow_84);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		eqdestroy___pipetpkgZreport_u81(resultX60gensym2__1);
		eqdestroy___pipetpkgZreport_u81(fails_1);
		goto BeforeRet_;
	}
LA19_: ;
	f_1 = open__stdZsyncio_u566(filename_p1, ((tyEnum_FileMode__9aETr7eq5EZaB8QOennw9cKg)1), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	nimZeroMem((void*)(&colontmpD__3), sizeof(tyObject_Table__v9bzVWMUF1VvPkxNkpfTgpg));
	colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
	writeRows__pipetpkgZreport_u11(f_1, fails_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
	T23_[0].Field0 = TM__QuD9cD3eGfqnfb8YjWMt5ow_87;
	T23_[0].Field1 = filename_p1;
	T23_[1].Field0 = TM__QuD9cD3eGfqnfb8YjWMt5ow_88;
	T24_ = fails_1.len;
	colontmpD__2 = dollar___systemZdollars_u14(T24_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
	T23_[1].Field1 = colontmpD__2;
	colontmpD__3 = toTable__pipetpkgZcore_u1321(T23_, 2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
	info__pipetpkgZlogger_u619(gLogger__pipetpkgZlogger_u94, TM__QuD9cD3eGfqnfb8YjWMt5ow_86, colontmpD__3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
	T26_.len = 0; T26_.p = NIM_NIL;
	T26_ = rawNewString(filename_p1.len + 34);
appendString((&T26_), TM__QuD9cD3eGfqnfb8YjWMt5ow_90);
appendString((&T26_), filename_p1);
	colontmpD__4 = T26_;
	T25_[0] = colontmpD__4;
	echoBinSafe(T25_, 1);
	{
		LA22_:;
	}
	{
		if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		eqdestroy___pipetpkgZlogger_u595((&colontmpD__3));
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
	{
		LA21_:;
	}
	{
		oldNimErrFin21_ = *nimErr_; *nimErr_ = NIM_FALSE;
		close__stdZsyncio_u290(f_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		*nimErr_ = oldNimErrFin21_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___pipetpkgZreport_u81(resultX60gensym2__1);
		eqdestroy___pipetpkgZreport_u81(fails_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, printFailDetails__pipetpkgZreport_u296)(tySequence__MEBiqQBl7pAoNbiVk1PPWQ results_p0) {
	tySequence__MEBiqQBl7pAoNbiVk1PPWQ fails_1;
	tySequence__MEBiqQBl7pAoNbiVk1PPWQ resultX60gensym3__1;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	NimStringV2 colontmpD__3;
	tyArray__YgExxhfgKcesA5EOUj1MOA T21_;
	NimStringV2 T22_;
	tyArray__YgExxhfgKcesA5EOUj1MOA T23_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	fails_1.len = 0; fails_1.p = NIM_NIL;
	resultX60gensym3__1.len = 0; resultX60gensym3__1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	resultX60gensym3__1 = newSeq__pipetpkgZreport_u235(((NI)0));
	{
		tyObject_TestResult__ngc9cAnVBEaUVswdGxkgeYg* it_1;
		NI i_1;
		NI L_1;
		NI T3_;
		it_1 = (tyObject_TestResult__ngc9cAnVBEaUVswdGxkgeYg*)0;
		i_1 = ((NI)0);
		T3_ = results_p0.len;
		L_1 = T3_;
		{
			while (1) {
				if (!(i_1 < L_1)) goto LA5;
				if (i_1 < 0 || i_1 >= results_p0.len){ raiseIndexError2(i_1,results_p0.len-1); goto LA1_;
				}
				it_1 = (&results_p0.p->data[i_1]);
				{
					tyObject_TestResult__ngc9cAnVBEaUVswdGxkgeYg colontmpD__4;
					tyObject_TestResult__ngc9cAnVBEaUVswdGxkgeYg T10_;
					if (!eqStrings((*it_1).status, TM__QuD9cD3eGfqnfb8YjWMt5ow_91)) goto LA8_;
					nimZeroMem((void*)(&T10_), sizeof(tyObject_TestResult__ngc9cAnVBEaUVswdGxkgeYg));
					eqdup___pipetpkgZcore_u2984((&(*it_1)), (&T10_));
					colontmpD__4 = T10_;
					add__pipetpkgZreport_u257((&resultX60gensym3__1), (&colontmpD__4));
				}
LA8_: ;
				i_1 += ((NI)1);
				{
					NI T13_;
					T13_ = results_p0.len;
					if (!!((T13_ == L_1))) goto LA14_;
					failedAssertImpl__stdZassertions_u95(TM__QuD9cD3eGfqnfb8YjWMt5ow_92);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
LA14_: ;
			} LA5: ;
		}
	}
	fails_1 = resultX60gensym3__1;
	eqwasMoved___pipetpkgZreport_u78((&resultX60gensym3__1));
	{
		NI T18_;
		T18_ = fails_1.len;
		if (!(T18_ == ((NI)0))) goto LA19_;
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		eqdestroy___pipetpkgZreport_u81(resultX60gensym3__1);
		eqdestroy___pipetpkgZreport_u81(fails_1);
		goto BeforeRet_;
	}
LA19_: ;
	T22_.len = 0; T22_.p = NIM_NIL;
	colontmpD_ = nsuRepeatStr(TM__QuD9cD3eGfqnfb8YjWMt5ow_95, ((NI)60));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T22_ = rawNewString(colontmpD_.len + 1);
appendString((&T22_), TM__QuD9cD3eGfqnfb8YjWMt5ow_93);
appendString((&T22_), colontmpD_);
	colontmpD__2 = T22_;
	T21_[0] = colontmpD__2;
	echoBinSafe(T21_, 1);
	echoBinSafe(TM__QuD9cD3eGfqnfb8YjWMt5ow_96, 1);
	colontmpD__3 = nsuRepeatStr(TM__QuD9cD3eGfqnfb8YjWMt5ow_98, ((NI)60));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T23_[0] = colontmpD__3;
	echoBinSafe(T23_, 1);
	{
		tyObject_TestResult__ngc9cAnVBEaUVswdGxkgeYg* r_1;
		NI i_2;
		NI L_2;
		NI T25_;
		r_1 = (tyObject_TestResult__ngc9cAnVBEaUVswdGxkgeYg*)0;
		i_2 = ((NI)0);
		T25_ = fails_1.len;
		L_2 = T25_;
		{
			while (1) {
				NimStringV2 colontmpD__5;
				NimStringV2 colontmpD__6;
				NimStringV2 colontmpD__7;
				tyArray__YgExxhfgKcesA5EOUj1MOA T29_;
				NimStringV2 T30_;
				tyArray__YgExxhfgKcesA5EOUj1MOA T31_;
				NimStringV2 T32_;
				tyArray__YgExxhfgKcesA5EOUj1MOA T33_;
				NimStringV2 T34_;
				if (!(i_2 < L_2)) goto LA27;
				colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
				colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
				colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
				if (i_2 < 0 || i_2 >= fails_1.len){ raiseIndexError2(i_2,fails_1.len-1); goto LA28_;
				}
				r_1 = (&fails_1.p->data[i_2]);
				T30_.len = 0; T30_.p = NIM_NIL;
				T30_ = rawNewString((*r_1).id.len + (*r_1).desc.len + 4);
appendString((&T30_), TM__QuD9cD3eGfqnfb8YjWMt5ow_100);
appendString((&T30_), (*r_1).id);
appendString((&T30_), TM__QuD9cD3eGfqnfb8YjWMt5ow_102);
appendString((&T30_), (*r_1).desc);
				colontmpD__5 = T30_;
				T29_[0] = colontmpD__5;
				echoBinSafe(T29_, 1);
				T32_.len = 0; T32_.p = NIM_NIL;
				T32_ = rawNewString((*r_1).diff.len + 10);
appendString((&T32_), TM__QuD9cD3eGfqnfb8YjWMt5ow_104);
appendString((&T32_), (*r_1).diff);
				colontmpD__6 = T32_;
				T31_[0] = colontmpD__6;
				echoBinSafe(T31_, 1);
				T34_.len = 0; T34_.p = NIM_NIL;
				T34_ = rawNewString((*r_1).actualBody.len + 19);
appendString((&T34_), TM__QuD9cD3eGfqnfb8YjWMt5ow_106);
appendString((&T34_), (*r_1).actualBody);
				colontmpD__7 = T34_;
				T33_[0] = colontmpD__7;
				echoBinSafe(T33_, 1);
				i_2 += ((NI)1);
				{
					NI T37_;
					T37_ = fails_1.len;
					if (!!((T37_ == L_2))) goto LA38_;
					failedAssertImpl__stdZassertions_u95(TM__QuD9cD3eGfqnfb8YjWMt5ow_107);
					if (NIM_UNLIKELY(*nimErr_)) goto LA28_;
				}
LA38_: ;
				{
					LA28_:;
				}
				{
					if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
					if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
					if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			} LA27: ;
		}
	}
	{
		LA1_:;
	}
	{
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		eqdestroy___pipetpkgZreport_u81(resultX60gensym3__1);
		eqdestroy___pipetpkgZreport_u81(fails_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
