/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -IC:\Bar\nim\lib -Ic:\UserProgram\nim\pipet\src -o c:\UserProgram\nim\pipet\releasecache\@nyaml-2.2.1-c08b506896c1e44fcabd8455a6047e7a5304b312@syaml@sprivate@sinternal.nim.c.o c:\UserProgram\nim\pipet\releasecache\@nyaml-2.2.1-c08b506896c1e44fcabd8455a6047e7a5304b312@syaml@sprivate@sinternal.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tySequence__4eQHGndY6XBYpFOH09apV8Q tySequence__4eQHGndY6XBYpFOH09apV8Q;
typedef struct tySequence__4eQHGndY6XBYpFOH09apV8Q_Content tySequence__4eQHGndY6XBYpFOH09apV8Q_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
struct tySequence__4eQHGndY6XBYpFOH09apV8Q {
  NI len; tySequence__4eQHGndY6XBYpFOH09apV8Q_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
	NimStringV2 Field0;
	NimStringV2 Field1;
};
struct tySequence__4eQHGndY6XBYpFOH09apV8Q_Content { NI cap; tyTuple__UV3llMMYFckfui8YMBuUZA data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2723)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__pkgZyamlZprivateZinternal_u35)(tySequence__4eQHGndY6XBYpFOH09apV8Q* x_p0, tyTuple__UV3llMMYFckfui8YMBuUZA* y_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2726)(NimStringV2 src_p0);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
{	result = NIM_FALSE;
	alen_1 = a_p0.len;
	blen_1 = b_p1.len;
	{
		if (!(alen_1 == blen_1)) goto LA3_;
		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		result = equalMem__system_u1763(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, registerHandle__pkgZyamlZprivateZinternal_u18)(tySequence__4eQHGndY6XBYpFOH09apV8Q* handles_p0, NimStringV2 handle_p1, NimStringV2 uriPrefix_p2) {
	NIM_BOOL result;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	tyTuple__UV3llMMYFckfui8YMBuUZA T9_;
{	result = (NIM_BOOL)0;
	{
		NI i_1;
		NI colontmp_;
		NI T2_;
		NI TM__vOQNfVeC4ccuIXlcB1fFEA_2;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		T2_ = (*handles_p0).len;
		if (nimSubInt(T2_, ((NI)1), &TM__vOQNfVeC4ccuIXlcB1fFEA_2)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__vOQNfVeC4ccuIXlcB1fFEA_2);
		res_1 = ((NI)0);
		{
			while (1) {
				NI TM__vOQNfVeC4ccuIXlcB1fFEA_3;
				if (!(res_1 <= colontmp_)) goto LA4;
				i_1 = ((NI) (res_1));
				{
					if (i_1 < 0 || i_1 >= (*handles_p0).len){ raiseIndexError2(i_1,(*handles_p0).len-1); goto BeforeRet_;
					}
					if (!eqStrings((*handles_p0).p->data[i_1].Field0, handle_p1)) goto LA7_;
					if (i_1 < 0 || i_1 >= (*handles_p0).len){ raiseIndexError2(i_1,(*handles_p0).len-1); goto BeforeRet_;
					}
					eqcopy___system_u2723((&(*handles_p0).p->data[i_1].Field1), uriPrefix_p2);
					result = NIM_FALSE;
					goto BeforeRet_;
				}
LA7_: ;
				if (nimAddInt(res_1, ((NI)1), &TM__vOQNfVeC4ccuIXlcB1fFEA_3)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__vOQNfVeC4ccuIXlcB1fFEA_3);
			} LA4: ;
		}
	}
	colontmpD_ = eqdup___system_u2726(handle_p1);
	T9_.Field0 = colontmpD_;
	colontmpD__2 = eqdup___system_u2726(uriPrefix_p2);
	T9_.Field1 = colontmpD__2;
	add__pkgZyamlZprivateZinternal_u35((&(*handles_p0)), (&T9_));
	result = NIM_FALSE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
