/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -IC:\Bar\nim\lib -Ic:\UserProgram\nim\pipet\src -o c:\UserProgram\nim\pipet\releasecache\@palgorithm.nim.c.o c:\UserProgram\nim\pipet\releasecache\@palgorithm.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, fill__pureZstrutils_u1634)(NI* a_p0, NI a_p0Len_0, NI value_p1) {
	NI xX60gensym170__1;
{	xX60gensym170__1 = ((NI)0);
	{
		while (1) {
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_2;
			if (!(xX60gensym170__1 <= (a_p0Len_0-1))) goto LA2;
			if (xX60gensym170__1 < 0 || xX60gensym170__1 >= a_p0Len_0){ raiseIndexError2(xX60gensym170__1,a_p0Len_0-1); goto BeforeRet_;
			}
			a_p0[xX60gensym170__1] = value_p1;
			if (nimAddInt(xX60gensym170__1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_2)) { raiseOverflow(); goto BeforeRet_;
			};
			xX60gensym170__1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_2);
		} LA2: ;
	}
	}BeforeRet_: ;
}
