/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -IC:\Bar\nim\lib -Ic:\UserProgram\nim\pipet\src -o c:\UserProgram\nim\pipet\releasecache\@pasyncdispatch.nim.c.o c:\UserProgram\nim\pipet\releasecache\@pasyncdispatch.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include "winsock2.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_PDispatchercolonObjectType___EER9aatfQpqfboxLu1DH6eQ tyObject_PDispatchercolonObjectType___EER9aatfQpqfboxLu1DH6eQ;
typedef struct tyObject_OVERLAPPED__Id7yT9cbz9crJWrwAdWASzRQ tyObject_OVERLAPPED__Id7yT9cbz9crJWrwAdWASzRQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_GUID__ufT9aylbui9bKLmnaWbVOtcw tyObject_GUID__ufT9aylbui9bKLmnaWbVOtcw;
typedef N_STDCALL_PTR(NIM_BOOL, tyProc__V1oBYOdLK9azVJpo9bTScxZg) (NI sListenSocket_p0, NI sAcceptSocket_p1, void* lpOutputBuffer_p2, NI32 dwReceiveDataLength_p3, NI32 dwLocalAddressLength_p4, NI32 dwRemoteAddressLength_p5, NI32* lpdwBytesReceived_p6, tyObject_OVERLAPPED__Id7yT9cbz9crJWrwAdWASzRQ* lpOverlapped_p7);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc__9aGJdpoDOKW1Goi1Sjhfo6g) (NI s_p0, SOCKADDR* name_p1, int namelen_p2, void* lpSendBuffer_p3, NI32 dwSendDataLength_p4, NI32* lpdwBytesSent_p5, tyObject_OVERLAPPED__Id7yT9cbz9crJWrwAdWASzRQ* lpOverlapped_p6);
typedef N_STDCALL_PTR(void, tyProc__RfWrpsP5a6EUaTJTWW0Rxw) (void* lpOutputBuffer_p0, NI32 dwReceiveDataLength_p1, NI32 dwLocalAddressLength_p2, NI32 dwRemoteAddressLength_p3, SOCKADDR** LocalSockaddr_p4, int* LocalSockaddrLength_p5, SOCKADDR** RemoteSockaddr_p6, int* RemoteSockaddrLength_p7);
typedef NU8 tyEnum_Domain__Yif4bn0bsIUECeGYAvfo7w;
typedef NU8 tyEnum_SockType__2ci9b9b9bxg1YFPV9bSnCQcfUA;
typedef NU8 tyEnum_Protocol__otnLl7OYkVO1z0YaRP55mg;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef N_STDCALL_PTR(void, tyProc__eBYhSq4X6b00Vn281WL0VA) (NI32 para1_p0, NI32 para2_p1, tyObject_OVERLAPPED__Id7yT9cbz9crJWrwAdWASzRQ* para3_p2);
typedef N_STDCALL_PTR(int, tyProc__kjRSgSzgA0VEFV2tpYOkQw) (NI s_p0, NI32 dwIoControlCode_p1, void* lpvInBuffer_p2, NI32 cbInBuffer_p3, void* lpvOutBuffer_p4, NI32 cbOutBuffer_p5, NI32* lpcbBytesReturned_p6, tyObject_OVERLAPPED__Id7yT9cbz9crJWrwAdWASzRQ* lpOverlapped_p7, tyProc__eBYhSq4X6b00Vn281WL0VA lpCompletionRoutine_p8);
typedef NI8 tyArray__RGsHGOi9bnu5uBb7LyMV9aPg[8];
struct tyObject_GUID__ufT9aylbui9bKLmnaWbVOtcw {
	NI32 D1;
	NI16 D2;
	NI16 D3;
	tyArray__RGsHGOi9bnu5uBb7LyMV9aPg D4;
};
typedef NIM_CHAR tyArray__AY9b9cftHbCDp9awOr5wvXtwg[14];
N_LIB_PRIVATE N_NIMCALL(void, initAll__pureZasyncdispatch_u4298)(void);
N_LIB_PRIVATE N_NIMCALL(NI, createNativeSocket__pureZnativesockets_u237)(tyEnum_Domain__Yif4bn0bsIUECeGYAvfo7w domain_p0, tyEnum_SockType__2ci9b9b9bxg1YFPV9bSnCQcfUA sockType_p1, tyEnum_Protocol__otnLl7OYkVO1z0YaRP55mg protocol_p2, NIM_BOOL inheritable_p3);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__stdZoserrors_u122)(NI32 errorCode_p0, NimStringV2 additionalInfo_p1);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__stdZoserrors_u125)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, initPointer__pureZasyncdispatch_u4273)(NI s_p0, void** fun_p1, tyObject_GUID__ufT9aylbui9bKLmnaWbVOtcw* guid_p2);
N_LIB_PRIVATE N_NIMCALL(void, close__pureZnativesockets_u224)(NI socket_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__gfe9a52b5gJr8GSrnr883iA_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__gfe9a52b5gJr8GSrnr883iA_3 = {0, (NimStrPayload*)&TM__gfe9a52b5gJr8GSrnr883iA_2};
static const NimStringV2 TM__gfe9a52b5gJr8GSrnr883iA_4 = {0, (NimStrPayload*)&TM__gfe9a52b5gJr8GSrnr883iA_2};
static const NimStringV2 TM__gfe9a52b5gJr8GSrnr883iA_5 = {0, (NimStrPayload*)&TM__gfe9a52b5gJr8GSrnr883iA_2};
static const NimStringV2 TM__gfe9a52b5gJr8GSrnr883iA_6 = {0, (NimStrPayload*)&TM__gfe9a52b5gJr8GSrnr883iA_2};
N_LIB_PRIVATE NIM_THREADVAR tyObject_PDispatchercolonObjectType___EER9aatfQpqfboxLu1DH6eQ* gDisp__pureZasyncdispatch_u1940;
N_LIB_PRIVATE tyProc__V1oBYOdLK9azVJpo9bTScxZg acceptEx__pureZasyncdispatch_u4270;
N_LIB_PRIVATE tyProc__9aGJdpoDOKW1Goi1Sjhfo6g connectEx__pureZasyncdispatch_u4271;
N_LIB_PRIVATE tyProc__RfWrpsP5a6EUaTJTWW0Rxw getAcceptExSockAddrs__pureZasyncdispatch_u4272;
extern tyProc__kjRSgSzgA0VEFV2tpYOkQw Dl_1912603350_;
extern tyObject_GUID__ufT9aylbui9bKLmnaWbVOtcw WSAID_CONNECTEX__windowsZwinlean_u723;
extern tyObject_GUID__ufT9aylbui9bKLmnaWbVOtcw WSAID_ACCEPTEX__windowsZwinlean_u724;
extern tyObject_GUID__ufT9aylbui9bKLmnaWbVOtcw WSAID_GETACCEPTEXSOCKADDRS__windowsZwinlean_u725;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4167;
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, initPointer__pureZasyncdispatch_u4273)(NI s_p0, void** fun_p1, tyObject_GUID__ufT9aylbui9bKLmnaWbVOtcw* guid_p2) {
	NIM_BOOL result;
	NI32 bytesRet_1;
	int T1_;
	bytesRet_1 = (NI32)0;
	(*fun_p1) = NIM_NIL;
	T1_ = (int)0;
	T1_ = Dl_1912603350_(s_p0, ((NI32)-939524090), ((void*) (guid_p2)), ((NI32)16), ((void*) (fun_p1)), ((NI32)8), (&bytesRet_1), ((tyObject_OVERLAPPED__Id7yT9cbz9crJWrwAdWASzRQ*) NIM_NIL), NIM_NIL);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4167);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, initAll__pureZasyncdispatch_u4298)(void) {
	NI dummySock_1;
	void* fun_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	dummySock_1 = createNativeSocket__pureZnativesockets_u237(((tyEnum_Domain__Yif4bn0bsIUECeGYAvfo7w)2), ((tyEnum_SockType__2ci9b9b9bxg1YFPV9bSnCQcfUA)1), ((tyEnum_Protocol__otnLl7OYkVO1z0YaRP55mg)6), NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI32 T5_;
		if (!(dummySock_1 == INVALID_SOCKET)) goto LA3_;
		T5_ = (NI32)0;
		T5_ = osLastError__stdZoserrors_u125();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_u122(T5_, TM__gfe9a52b5gJr8GSrnr883iA_3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	fun_1 = NIM_NIL;
	{
		NIM_BOOL T8_;
		NI32 T11_;
		T8_ = (NIM_BOOL)0;
		T8_ = initPointer__pureZasyncdispatch_u4273(dummySock_1, (&fun_1), (&WSAID_CONNECTEX__windowsZwinlean_u723));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T8_)) goto LA9_;
		T11_ = (NI32)0;
		T11_ = osLastError__stdZoserrors_u125();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_u122(T11_, TM__gfe9a52b5gJr8GSrnr883iA_4);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA9_: ;
	connectEx__pureZasyncdispatch_u4271 = ((tyProc__9aGJdpoDOKW1Goi1Sjhfo6g) (fun_1));
	{
		NIM_BOOL T14_;
		NI32 T17_;
		T14_ = (NIM_BOOL)0;
		T14_ = initPointer__pureZasyncdispatch_u4273(dummySock_1, (&fun_1), (&WSAID_ACCEPTEX__windowsZwinlean_u724));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T14_)) goto LA15_;
		T17_ = (NI32)0;
		T17_ = osLastError__stdZoserrors_u125();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_u122(T17_, TM__gfe9a52b5gJr8GSrnr883iA_5);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA15_: ;
	acceptEx__pureZasyncdispatch_u4270 = ((tyProc__V1oBYOdLK9azVJpo9bTScxZg) (fun_1));
	{
		NIM_BOOL T20_;
		NI32 T23_;
		T20_ = (NIM_BOOL)0;
		T20_ = initPointer__pureZasyncdispatch_u4273(dummySock_1, (&fun_1), (&WSAID_GETACCEPTEXSOCKADDRS__windowsZwinlean_u725));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T20_)) goto LA21_;
		T23_ = (NI32)0;
		T23_ = osLastError__stdZoserrors_u125();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_u122(T23_, TM__gfe9a52b5gJr8GSrnr883iA_6);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA21_: ;
	getAcceptExSockAddrs__pureZasyncdispatch_u4272 = ((tyProc__RfWrpsP5a6EUaTJTWW0Rxw) (fun_1));
	close__pureZnativesockets_u224(dummySock_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, atpasyncdispatchdotnim_Init000)(void) {
{
NIM_BOOL* nimErr_;
nimErr_ = nimErrorFlag();
	initAll__pureZasyncdispatch_u4298();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	BeforeRet_: ;
	nimTestErrorFlag();
}
}

