/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -IC:\Bar\nim\lib -Ic:\UserProgram\nim\pipet\src -o c:\UserProgram\nim\pipet\releasecache\@pbase64.nim.c.o c:\UserProgram\nim\pipet\releasecache\@pbase64.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NIM_CHAR tyArray__o9aRz9a9a9bzfUdxgetJHLgorg[64];
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2462)(NimStringV2* s_p0);
N_LIB_PRIVATE NIM_CONST tyArray__o9aRz9a9a9bzfUdxgetJHLgorg cb64safe__pureZbase64_u5 = {65,
66,
67,
68,
69,
70,
71,
72,
73,
74,
75,
76,
77,
78,
79,
80,
81,
82,
83,
84,
85,
86,
87,
88,
89,
90,
97,
98,
99,
100,
101,
102,
103,
104,
105,
106,
107,
108,
109,
110,
111,
112,
113,
114,
115,
116,
117,
118,
119,
120,
121,
122,
48,
49,
50,
51,
52,
53,
54,
55,
56,
57,
45,
95}
;
N_LIB_PRIVATE NIM_CONST tyArray__o9aRz9a9a9bzfUdxgetJHLgorg cb64__pureZbase64_u4 = {65,
66,
67,
68,
69,
70,
71,
72,
73,
74,
75,
76,
77,
78,
79,
80,
81,
82,
83,
84,
85,
86,
87,
88,
89,
90,
97,
98,
99,
100,
101,
102,
103,
104,
105,
106,
107,
108,
109,
110,
111,
112,
113,
114,
115,
116,
117,
118,
119,
120,
121,
122,
48,
49,
50,
51,
52,
53,
54,
55,
56,
57,
43,
47}
;
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2462(s_p0);
	}
LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, encode__pureZbase64_u42)(NIM_CHAR* s_p0, NI s_p0Len_0, NIM_BOOL safe_p1) {
	NimStringV2 result;
{	result.len = 0; result.p = NIM_NIL;
	{
		NI TM__2L6xrRPz7CWDB3T1R9cDN5A_2;
		NI TM__2L6xrRPz7CWDB3T1R9cDN5A_3;
		NI paddingX60gensym4__1;
		NI inputEndsX60gensym4__1;
		NI TM__2L6xrRPz7CWDB3T1R9cDN5A_4;
		NI inputIndexX60gensym4__1;
		NI outputIndexX60gensym4__1;
		NU32 nX60gensym4__1;
		NU32 bX60gensym4__1;
		if (!safe_p1) goto LA3_;
		if (nimAddInt((NI)((s_p0Len_0) / (((NI)3))), s_p0Len_0, &TM__2L6xrRPz7CWDB3T1R9cDN5A_2)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimAddInt((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_2), ((NI)6), &TM__2L6xrRPz7CWDB3T1R9cDN5A_3)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_3)) < ((NI)0) || ((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_3)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_3), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		setLengthStrV2((&result), ((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_3)));
		paddingX60gensym4__1 = (NI)((s_p0Len_0) % (((NI)3)));
		if (nimSubInt(s_p0Len_0, paddingX60gensym4__1, &TM__2L6xrRPz7CWDB3T1R9cDN5A_4)) { raiseOverflow(); goto BeforeRet_;
		};
		inputEndsX60gensym4__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_4);
		inputIndexX60gensym4__1 = ((NI)0);
		outputIndexX60gensym4__1 = ((NI)0);
		nX60gensym4__1 = (NU32)0;
		bX60gensym4__1 = (NU32)0;
		{
			while (1) {
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_5;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_6;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_7;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_8;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_9;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_10;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_11;
				if (!!((inputIndexX60gensym4__1 == inputEndsX60gensym4__1))) goto LA6;
				if (inputIndexX60gensym4__1 < 0 || inputIndexX60gensym4__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym4__1,s_p0Len_0-1); goto BeforeRet_;
				}
				bX60gensym4__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym4__1]))));
				nX60gensym4__1 = (NU32)((NU64)(bX60gensym4__1) << (NU64)(((NI)16) & (32 - 1)));
				if (nimAddInt(inputIndexX60gensym4__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_5)) { raiseOverflow(); goto BeforeRet_;
				};
				inputIndexX60gensym4__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_5);
				if (inputIndexX60gensym4__1 < 0 || inputIndexX60gensym4__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym4__1,s_p0Len_0-1); goto BeforeRet_;
				}
				bX60gensym4__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym4__1]))));
				nX60gensym4__1 = (NU32)(nX60gensym4__1 | (NU32)((NU64)(bX60gensym4__1) << (NU64)(((NI)8) & (32 - 1))));
				if (nimAddInt(inputIndexX60gensym4__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_6)) { raiseOverflow(); goto BeforeRet_;
				};
				inputIndexX60gensym4__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_6);
				if (inputIndexX60gensym4__1 < 0 || inputIndexX60gensym4__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym4__1,s_p0Len_0-1); goto BeforeRet_;
				}
				bX60gensym4__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym4__1]))));
				nX60gensym4__1 = (NU32)(nX60gensym4__1 | (NU32)((NU64)(bX60gensym4__1) << (NU64)(((NI)0) & (32 - 1))));
				if (nimAddInt(inputIndexX60gensym4__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_7)) { raiseOverflow(); goto BeforeRet_;
				};
				inputIndexX60gensym4__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_7);
				if (outputIndexX60gensym4__1 < 0 || outputIndexX60gensym4__1 >= result.len){ raiseIndexError2(outputIndexX60gensym4__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if ((NU)((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
				}
				result.p->data[outputIndexX60gensym4__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)))- 0];
				if (nimAddInt(outputIndexX60gensym4__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_8)) { raiseOverflow(); goto BeforeRet_;
				};
				outputIndexX60gensym4__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_8);
				if (outputIndexX60gensym4__1 < 0 || outputIndexX60gensym4__1 >= result.len){ raiseIndexError2(outputIndexX60gensym4__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if ((NU)((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
				}
				result.p->data[outputIndexX60gensym4__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)))- 0];
				if (nimAddInt(outputIndexX60gensym4__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_9)) { raiseOverflow(); goto BeforeRet_;
				};
				outputIndexX60gensym4__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_9);
				if (outputIndexX60gensym4__1 < 0 || outputIndexX60gensym4__1 >= result.len){ raiseIndexError2(outputIndexX60gensym4__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if ((NU)((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
				}
				result.p->data[outputIndexX60gensym4__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63)))- 0];
				if (nimAddInt(outputIndexX60gensym4__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_10)) { raiseOverflow(); goto BeforeRet_;
				};
				outputIndexX60gensym4__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_10);
				if (outputIndexX60gensym4__1 < 0 || outputIndexX60gensym4__1 >= result.len){ raiseIndexError2(outputIndexX60gensym4__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if ((NU)((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)0) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)0) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
				}
				result.p->data[outputIndexX60gensym4__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)0) & (32 - 1))) & ((NU32)63)))- 0];
				if (nimAddInt(outputIndexX60gensym4__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_11)) { raiseOverflow(); goto BeforeRet_;
				};
				outputIndexX60gensym4__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_11);
			} LA6: ;
		}
		{
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_12;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_13;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_14;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_15;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_16;
			if (!(paddingX60gensym4__1 == ((NI)1))) goto LA9_;
			if (inputIndexX60gensym4__1 < 0 || inputIndexX60gensym4__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym4__1,s_p0Len_0-1); goto BeforeRet_;
			}
			bX60gensym4__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym4__1]))));
			nX60gensym4__1 = (NU32)((NU64)(bX60gensym4__1) << (NU64)(((NI)16) & (32 - 1)));
			if (nimAddInt(inputIndexX60gensym4__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_12)) { raiseOverflow(); goto BeforeRet_;
			};
			inputIndexX60gensym4__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_12);
			if (outputIndexX60gensym4__1 < 0 || outputIndexX60gensym4__1 >= result.len){ raiseIndexError2(outputIndexX60gensym4__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			if ((NU)((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
			}
			result.p->data[outputIndexX60gensym4__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)))- 0];
			if (nimAddInt(outputIndexX60gensym4__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_13)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym4__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_13);
			if (outputIndexX60gensym4__1 < 0 || outputIndexX60gensym4__1 >= result.len){ raiseIndexError2(outputIndexX60gensym4__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			if ((NU)((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
			}
			result.p->data[outputIndexX60gensym4__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)))- 0];
			if (nimAddInt(outputIndexX60gensym4__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_14)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym4__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_14);
			if (outputIndexX60gensym4__1 < 0 || outputIndexX60gensym4__1 >= result.len){ raiseIndexError2(outputIndexX60gensym4__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndexX60gensym4__1] = 61;
			if (nimAddInt(outputIndexX60gensym4__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_15)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym4__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_15);
			if (outputIndexX60gensym4__1 < 0 || outputIndexX60gensym4__1 >= result.len){ raiseIndexError2(outputIndexX60gensym4__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndexX60gensym4__1] = 61;
			if (nimAddInt(outputIndexX60gensym4__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_16)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym4__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_16);
		}
		goto LA7_;
LA9_: ;
		{
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_17;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_18;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_19;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_20;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_21;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_22;
			if (!(paddingX60gensym4__1 == ((NI)2))) goto LA12_;
			if (inputIndexX60gensym4__1 < 0 || inputIndexX60gensym4__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym4__1,s_p0Len_0-1); goto BeforeRet_;
			}
			bX60gensym4__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym4__1]))));
			nX60gensym4__1 = (NU32)((NU64)(bX60gensym4__1) << (NU64)(((NI)16) & (32 - 1)));
			if (nimAddInt(inputIndexX60gensym4__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_17)) { raiseOverflow(); goto BeforeRet_;
			};
			inputIndexX60gensym4__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_17);
			if (inputIndexX60gensym4__1 < 0 || inputIndexX60gensym4__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym4__1,s_p0Len_0-1); goto BeforeRet_;
			}
			bX60gensym4__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym4__1]))));
			nX60gensym4__1 = (NU32)(nX60gensym4__1 | (NU32)((NU64)(bX60gensym4__1) << (NU64)(((NI)8) & (32 - 1))));
			if (nimAddInt(inputIndexX60gensym4__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_18)) { raiseOverflow(); goto BeforeRet_;
			};
			inputIndexX60gensym4__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_18);
			if (outputIndexX60gensym4__1 < 0 || outputIndexX60gensym4__1 >= result.len){ raiseIndexError2(outputIndexX60gensym4__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			if ((NU)((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
			}
			result.p->data[outputIndexX60gensym4__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)))- 0];
			if (nimAddInt(outputIndexX60gensym4__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_19)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym4__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_19);
			if (outputIndexX60gensym4__1 < 0 || outputIndexX60gensym4__1 >= result.len){ raiseIndexError2(outputIndexX60gensym4__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			if ((NU)((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
			}
			result.p->data[outputIndexX60gensym4__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)))- 0];
			if (nimAddInt(outputIndexX60gensym4__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_20)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym4__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_20);
			if (outputIndexX60gensym4__1 < 0 || outputIndexX60gensym4__1 >= result.len){ raiseIndexError2(outputIndexX60gensym4__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			if ((NU)((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
			}
			result.p->data[outputIndexX60gensym4__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym4__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63)))- 0];
			if (nimAddInt(outputIndexX60gensym4__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_21)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym4__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_21);
			if (outputIndexX60gensym4__1 < 0 || outputIndexX60gensym4__1 >= result.len){ raiseIndexError2(outputIndexX60gensym4__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndexX60gensym4__1] = 61;
			if (nimAddInt(outputIndexX60gensym4__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_22)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym4__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_22);
		}
		goto LA7_;
LA12_: ;
LA7_: ;
		if ((outputIndexX60gensym4__1) < ((NI)0) || (outputIndexX60gensym4__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(outputIndexX60gensym4__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		setLengthStrV2((&result), (outputIndexX60gensym4__1));
	}
	goto LA1_;
LA3_: ;
	{
		NI TM__2L6xrRPz7CWDB3T1R9cDN5A_23;
		NI TM__2L6xrRPz7CWDB3T1R9cDN5A_24;
		NI paddingX60gensym37__1;
		NI inputEndsX60gensym37__1;
		NI TM__2L6xrRPz7CWDB3T1R9cDN5A_25;
		NI inputIndexX60gensym37__1;
		NI outputIndexX60gensym37__1;
		NU32 nX60gensym37__1;
		NU32 bX60gensym37__1;
		if (nimAddInt((NI)((s_p0Len_0) / (((NI)3))), s_p0Len_0, &TM__2L6xrRPz7CWDB3T1R9cDN5A_23)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimAddInt((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_23), ((NI)6), &TM__2L6xrRPz7CWDB3T1R9cDN5A_24)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_24)) < ((NI)0) || ((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_24)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_24), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		setLengthStrV2((&result), ((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_24)));
		paddingX60gensym37__1 = (NI)((s_p0Len_0) % (((NI)3)));
		if (nimSubInt(s_p0Len_0, paddingX60gensym37__1, &TM__2L6xrRPz7CWDB3T1R9cDN5A_25)) { raiseOverflow(); goto BeforeRet_;
		};
		inputEndsX60gensym37__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_25);
		inputIndexX60gensym37__1 = ((NI)0);
		outputIndexX60gensym37__1 = ((NI)0);
		nX60gensym37__1 = (NU32)0;
		bX60gensym37__1 = (NU32)0;
		{
			while (1) {
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_26;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_27;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_28;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_29;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_30;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_31;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_32;
				if (!!((inputIndexX60gensym37__1 == inputEndsX60gensym37__1))) goto LA16;
				if (inputIndexX60gensym37__1 < 0 || inputIndexX60gensym37__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym37__1,s_p0Len_0-1); goto BeforeRet_;
				}
				bX60gensym37__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym37__1]))));
				nX60gensym37__1 = (NU32)((NU64)(bX60gensym37__1) << (NU64)(((NI)16) & (32 - 1)));
				if (nimAddInt(inputIndexX60gensym37__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_26)) { raiseOverflow(); goto BeforeRet_;
				};
				inputIndexX60gensym37__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_26);
				if (inputIndexX60gensym37__1 < 0 || inputIndexX60gensym37__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym37__1,s_p0Len_0-1); goto BeforeRet_;
				}
				bX60gensym37__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym37__1]))));
				nX60gensym37__1 = (NU32)(nX60gensym37__1 | (NU32)((NU64)(bX60gensym37__1) << (NU64)(((NI)8) & (32 - 1))));
				if (nimAddInt(inputIndexX60gensym37__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_27)) { raiseOverflow(); goto BeforeRet_;
				};
				inputIndexX60gensym37__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_27);
				if (inputIndexX60gensym37__1 < 0 || inputIndexX60gensym37__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym37__1,s_p0Len_0-1); goto BeforeRet_;
				}
				bX60gensym37__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym37__1]))));
				nX60gensym37__1 = (NU32)(nX60gensym37__1 | (NU32)((NU64)(bX60gensym37__1) << (NU64)(((NI)0) & (32 - 1))));
				if (nimAddInt(inputIndexX60gensym37__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_28)) { raiseOverflow(); goto BeforeRet_;
				};
				inputIndexX60gensym37__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_28);
				if (outputIndexX60gensym37__1 < 0 || outputIndexX60gensym37__1 >= result.len){ raiseIndexError2(outputIndexX60gensym37__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if ((NU)((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
				}
				result.p->data[outputIndexX60gensym37__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)))- 0];
				if (nimAddInt(outputIndexX60gensym37__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_29)) { raiseOverflow(); goto BeforeRet_;
				};
				outputIndexX60gensym37__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_29);
				if (outputIndexX60gensym37__1 < 0 || outputIndexX60gensym37__1 >= result.len){ raiseIndexError2(outputIndexX60gensym37__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if ((NU)((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
				}
				result.p->data[outputIndexX60gensym37__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)))- 0];
				if (nimAddInt(outputIndexX60gensym37__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_30)) { raiseOverflow(); goto BeforeRet_;
				};
				outputIndexX60gensym37__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_30);
				if (outputIndexX60gensym37__1 < 0 || outputIndexX60gensym37__1 >= result.len){ raiseIndexError2(outputIndexX60gensym37__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if ((NU)((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
				}
				result.p->data[outputIndexX60gensym37__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63)))- 0];
				if (nimAddInt(outputIndexX60gensym37__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_31)) { raiseOverflow(); goto BeforeRet_;
				};
				outputIndexX60gensym37__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_31);
				if (outputIndexX60gensym37__1 < 0 || outputIndexX60gensym37__1 >= result.len){ raiseIndexError2(outputIndexX60gensym37__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if ((NU)((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)0) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)0) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
				}
				result.p->data[outputIndexX60gensym37__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)0) & (32 - 1))) & ((NU32)63)))- 0];
				if (nimAddInt(outputIndexX60gensym37__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_32)) { raiseOverflow(); goto BeforeRet_;
				};
				outputIndexX60gensym37__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_32);
			} LA16: ;
		}
		{
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_33;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_34;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_35;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_36;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_37;
			if (!(paddingX60gensym37__1 == ((NI)1))) goto LA19_;
			if (inputIndexX60gensym37__1 < 0 || inputIndexX60gensym37__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym37__1,s_p0Len_0-1); goto BeforeRet_;
			}
			bX60gensym37__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym37__1]))));
			nX60gensym37__1 = (NU32)((NU64)(bX60gensym37__1) << (NU64)(((NI)16) & (32 - 1)));
			if (nimAddInt(inputIndexX60gensym37__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_33)) { raiseOverflow(); goto BeforeRet_;
			};
			inputIndexX60gensym37__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_33);
			if (outputIndexX60gensym37__1 < 0 || outputIndexX60gensym37__1 >= result.len){ raiseIndexError2(outputIndexX60gensym37__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			if ((NU)((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
			}
			result.p->data[outputIndexX60gensym37__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)))- 0];
			if (nimAddInt(outputIndexX60gensym37__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_34)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym37__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_34);
			if (outputIndexX60gensym37__1 < 0 || outputIndexX60gensym37__1 >= result.len){ raiseIndexError2(outputIndexX60gensym37__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			if ((NU)((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
			}
			result.p->data[outputIndexX60gensym37__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)))- 0];
			if (nimAddInt(outputIndexX60gensym37__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_35)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym37__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_35);
			if (outputIndexX60gensym37__1 < 0 || outputIndexX60gensym37__1 >= result.len){ raiseIndexError2(outputIndexX60gensym37__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndexX60gensym37__1] = 61;
			if (nimAddInt(outputIndexX60gensym37__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_36)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym37__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_36);
			if (outputIndexX60gensym37__1 < 0 || outputIndexX60gensym37__1 >= result.len){ raiseIndexError2(outputIndexX60gensym37__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndexX60gensym37__1] = 61;
			if (nimAddInt(outputIndexX60gensym37__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_37)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym37__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_37);
		}
		goto LA17_;
LA19_: ;
		{
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_38;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_39;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_40;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_41;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_42;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_43;
			if (!(paddingX60gensym37__1 == ((NI)2))) goto LA22_;
			if (inputIndexX60gensym37__1 < 0 || inputIndexX60gensym37__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym37__1,s_p0Len_0-1); goto BeforeRet_;
			}
			bX60gensym37__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym37__1]))));
			nX60gensym37__1 = (NU32)((NU64)(bX60gensym37__1) << (NU64)(((NI)16) & (32 - 1)));
			if (nimAddInt(inputIndexX60gensym37__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_38)) { raiseOverflow(); goto BeforeRet_;
			};
			inputIndexX60gensym37__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_38);
			if (inputIndexX60gensym37__1 < 0 || inputIndexX60gensym37__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym37__1,s_p0Len_0-1); goto BeforeRet_;
			}
			bX60gensym37__1 = ((NU32) (((NU8)(s_p0[inputIndexX60gensym37__1]))));
			nX60gensym37__1 = (NU32)(nX60gensym37__1 | (NU32)((NU64)(bX60gensym37__1) << (NU64)(((NI)8) & (32 - 1))));
			if (nimAddInt(inputIndexX60gensym37__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_39)) { raiseOverflow(); goto BeforeRet_;
			};
			inputIndexX60gensym37__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_39);
			if (outputIndexX60gensym37__1 < 0 || outputIndexX60gensym37__1 >= result.len){ raiseIndexError2(outputIndexX60gensym37__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			if ((NU)((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
			}
			result.p->data[outputIndexX60gensym37__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)))- 0];
			if (nimAddInt(outputIndexX60gensym37__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_40)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym37__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_40);
			if (outputIndexX60gensym37__1 < 0 || outputIndexX60gensym37__1 >= result.len){ raiseIndexError2(outputIndexX60gensym37__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			if ((NU)((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
			}
			result.p->data[outputIndexX60gensym37__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)))- 0];
			if (nimAddInt(outputIndexX60gensym37__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_41)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym37__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_41);
			if (outputIndexX60gensym37__1 < 0 || outputIndexX60gensym37__1 >= result.len){ raiseIndexError2(outputIndexX60gensym37__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			if ((NU)((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
			}
			result.p->data[outputIndexX60gensym37__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym37__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63)))- 0];
			if (nimAddInt(outputIndexX60gensym37__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_42)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym37__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_42);
			if (outputIndexX60gensym37__1 < 0 || outputIndexX60gensym37__1 >= result.len){ raiseIndexError2(outputIndexX60gensym37__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			result.p->data[outputIndexX60gensym37__1] = 61;
			if (nimAddInt(outputIndexX60gensym37__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_43)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym37__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_43);
		}
		goto LA17_;
LA22_: ;
LA17_: ;
		if ((outputIndexX60gensym37__1) < ((NI)0) || (outputIndexX60gensym37__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(outputIndexX60gensym37__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		setLengthStrV2((&result), (outputIndexX60gensym37__1));
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
