/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -IC:\Bar\nim\lib -Ic:\UserProgram\nim\pipet\src -o c:\UserProgram\nim\pipet\releasecache\@pdynlib.nim.c.o c:\UserProgram\nim\pipet\releasecache\@pdynlib.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <windows.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_LibraryError__wQ8HJvjvvAFBKQzcDhTzGw tyObject_LibraryError__wQ8HJvjvvAFBKQzcDhTzGw;
typedef struct tyObject_OSError__qn9bWnNu0ljekqVDarrpanQ tyObject_OSError__qn9bWnNu0ljekqVDarrpanQ;
typedef struct tyObject_CatchableError__5X2CqDk7Ldk7h9a22Zsg5kg tyObject_CatchableError__5X2CqDk7Ldk7h9a22Zsg5kg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__xIN54dE1a4ZyAUnTpAuU2g tySequence__xIN54dE1a4ZyAUnTpAuU2g;
typedef struct tySequence__xIN54dE1a4ZyAUnTpAuU2g_Content tySequence__xIN54dE1a4ZyAUnTpAuU2g_Content;
typedef struct tyObject_StackTraceEntry__2ELMRvKL5HlwpyV9cRIuTmw tyObject_StackTraceEntry__2ELMRvKL5HlwpyV9cRIuTmw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__xIN54dE1a4ZyAUnTpAuU2g {
  NI len; tySequence__xIN54dE1a4ZyAUnTpAuU2g_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__xIN54dE1a4ZyAUnTpAuU2g trace;
	Exception* up;
};
struct tyObject_CatchableError__5X2CqDk7Ldk7h9a22Zsg5kg {
	Exception Sup;
};
struct tyObject_OSError__qn9bWnNu0ljekqVDarrpanQ {
	tyObject_CatchableError__5X2CqDk7Ldk7h9a22Zsg5kg Sup;
	NI32 errorCode;
};
struct tyObject_LibraryError__wQ8HJvjvvAFBKQzcDhTzGw {
	tyObject_OSError__qn9bWnNu0ljekqVDarrpanQ Sup;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__2ELMRvKL5HlwpyV9cRIuTmw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__xIN54dE1a4ZyAUnTpAuU2g_Content { NI cap; tyObject_StackTraceEntry__2ELMRvKL5HlwpyV9cRIuTmw data[SEQ_DECL_SIZE]; };
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, newSeq__stdZsyncio_u668)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(void, libCandidates__pureZdynlib_u81)(NimStringV2 s_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ* dest_p1);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u9113)(NimStringV2 s_p0, NI first_p1, NI last_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u9126)(NimStringV2 s_p0, NI first_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2729)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u70)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2726)(NimStringV2 src_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void*, loadLib__pureZdynlib_u3)(NimStringV2 path_p0, NIM_BOOL globalSymbols_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5522)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
static const struct {
  NI cap; NIM_CHAR data[90+1];
} TM__Vbi6rBBOqdMySprhH3iUcg_11 = { 90 | NIM_STRLIT_FLAG, "iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__Vbi6rBBOqdMySprhH3iUcg_12 = {90, (NimStrPayload*)&TM__Vbi6rBBOqdMySprhH3iUcg_11};
extern TNimTypeV2 NTIv2__wQ8HJvjvvAFBKQzcDhTzGw_;
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__Vbi6rBBOqdMySprhH3iUcg_13 = { 23 | NIM_STRLIT_FLAG, "could not find symbol: " };
static const NimStringV2 TM__Vbi6rBBOqdMySprhH3iUcg_14 = {23, (NimStrPayload*)&TM__Vbi6rBBOqdMySprhH3iUcg_13};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4167;
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, loadLib__pureZdynlib_u3)(NimStringV2 path_p0, NIM_BOOL globalSymbols_p1) {
	void* result;
	HMODULE T1_;
	T1_ = (HMODULE)0;
	T1_ = LoadLibraryA(nimToCStringConv(path_p0));
	result = ((void*) (T1_));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, symAddr__pureZdynlib_u74)(void* lib_p0, NCSTRING name_p1) {
	void* result;
	FARPROC T1_;
	T1_ = (FARPROC)0;
	T1_ = GetProcAddress(((HMODULE) (lib_p0)), name_p1);
	result = ((void*) (T1_));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, loadLib__pureZdynlib_u6)(void) {
	void* result;
	HMODULE T1_;
	T1_ = (HMODULE)0;
	T1_ = LoadLibraryA(((NCSTRING) NIM_NIL));
	result = ((void*) (T1_));
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4167);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, libCandidates__pureZdynlib_u81)(NimStringV2 s_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ* dest_p1) {
	NI le_1;
	NI ri_1;
	NI TM__Vbi6rBBOqdMySprhH3iUcg_2;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	le_1 = nsuFindChar(s_p0, 40, ((NI)0), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimAddInt(le_1, ((NI)1), &TM__Vbi6rBBOqdMySprhH3iUcg_2)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__Vbi6rBBOqdMySprhH3iUcg_2)) < ((NI)0) || ((NI)(TM__Vbi6rBBOqdMySprhH3iUcg_2)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__Vbi6rBBOqdMySprhH3iUcg_2), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	ri_1 = nsuFindChar(s_p0, 41, ((NI)(TM__Vbi6rBBOqdMySprhH3iUcg_2)), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NIM_BOOL T3_;
		NimStringV2 prefix_1;
		NimStringV2 suffix_1;
		NI TM__Vbi6rBBOqdMySprhH3iUcg_3;
		NI TM__Vbi6rBBOqdMySprhH3iUcg_4;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= le_1);
		if (!(T3_)) goto LA4_;
		T3_ = (le_1 < ri_1);
LA4_: ;
		if (!T3_) goto LA5_;
		prefix_1.len = 0; prefix_1.p = NIM_NIL;
		suffix_1.len = 0; suffix_1.p = NIM_NIL;
		if (nimSubInt(le_1, ((NI)1), &TM__Vbi6rBBOqdMySprhH3iUcg_3)) { raiseOverflow(); goto LA7_;
		};
		prefix_1 = substr__system_u9113(s_p0, ((NI)0), (NI)(TM__Vbi6rBBOqdMySprhH3iUcg_3));
		if (nimAddInt(ri_1, ((NI)1), &TM__Vbi6rBBOqdMySprhH3iUcg_4)) { raiseOverflow(); goto LA7_;
		};
		suffix_1 = substr__system_u9126(s_p0, (NI)(TM__Vbi6rBBOqdMySprhH3iUcg_4));
		{
			NimStringV2 middle_1;
			NimStringV2 colontmp_;
			NI TM__Vbi6rBBOqdMySprhH3iUcg_5;
			NI TM__Vbi6rBBOqdMySprhH3iUcg_6;
			NI lastX60gensym34__1;
			NI splitsX60gensym34__1;
			middle_1.len = 0; middle_1.p = NIM_NIL;
			colontmp_.len = 0; colontmp_.p = NIM_NIL;
			if (nimAddInt(le_1, ((NI)1), &TM__Vbi6rBBOqdMySprhH3iUcg_5)) { raiseOverflow(); goto LA9_;
			};
			if (nimSubInt(ri_1, ((NI)1), &TM__Vbi6rBBOqdMySprhH3iUcg_6)) { raiseOverflow(); goto LA9_;
			};
			colontmp_ = substr__system_u9113(s_p0, (NI)(TM__Vbi6rBBOqdMySprhH3iUcg_5), (NI)(TM__Vbi6rBBOqdMySprhH3iUcg_6));
			lastX60gensym34__1 = ((NI)0);
			splitsX60gensym34__1 = ((NI)-1);
			{
				while (1) {
					NimStringV2 colontmpD_;
					NI firstX60gensym34__1;
					NI TM__Vbi6rBBOqdMySprhH3iUcg_8;
					NimStringV2 T21_;
					NimStringV2 T22_;
					NI TM__Vbi6rBBOqdMySprhH3iUcg_9;
					NI TM__Vbi6rBBOqdMySprhH3iUcg_10;
					if (!(lastX60gensym34__1 <= colontmp_.len)) goto LA11;
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
					firstX60gensym34__1 = lastX60gensym34__1;
					{
						while (1) {
							NIM_BOOL T15_;
							NI TM__Vbi6rBBOqdMySprhH3iUcg_7;
							T15_ = (NIM_BOOL)0;
							T15_ = (lastX60gensym34__1 < colontmp_.len);
							if (!(T15_)) goto LA16_;
							if (lastX60gensym34__1 < 0 || lastX60gensym34__1 >= colontmp_.len){ raiseIndexError2(lastX60gensym34__1,colontmp_.len-1); goto LA12_;
							}
							T15_ = !(((NU8)(colontmp_.p->data[lastX60gensym34__1]) == (NU8)(124)));
LA16_: ;
							if (!T15_) goto LA14;
							if (nimAddInt(lastX60gensym34__1, ((NI)1), &TM__Vbi6rBBOqdMySprhH3iUcg_7)) { raiseOverflow(); goto LA12_;
							};
							lastX60gensym34__1 = (NI)(TM__Vbi6rBBOqdMySprhH3iUcg_7);
						} LA14: ;
					}
					{
						if (!(splitsX60gensym34__1 == ((NI)0))) goto LA19_;
						lastX60gensym34__1 = colontmp_.len;
					}
LA19_: ;
					if (nimSubInt(lastX60gensym34__1, ((NI)1), &TM__Vbi6rBBOqdMySprhH3iUcg_8)) { raiseOverflow(); goto LA12_;
					};
					T21_.len = 0; T21_.p = NIM_NIL;
					T21_ = substr__system_u9113(colontmp_, firstX60gensym34__1, (NI)(TM__Vbi6rBBOqdMySprhH3iUcg_8));
					eqsink___system_u2729((&middle_1), T21_);
					T22_.len = 0; T22_.p = NIM_NIL;
					T22_ = rawNewString(prefix_1.len + middle_1.len + suffix_1.len + 0);
appendString((&T22_), prefix_1);
appendString((&T22_), middle_1);
appendString((&T22_), suffix_1);
					colontmpD_ = T22_;
					libCandidates__pureZdynlib_u81(colontmpD_, dest_p1);
					if (NIM_UNLIKELY(*nimErr_)) goto LA12_;
					{
						if (!(splitsX60gensym34__1 == ((NI)0))) goto LA25_;
						if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
						goto LA10;
					}
LA25_: ;
					if (nimSubInt(splitsX60gensym34__1, ((NI)1), &TM__Vbi6rBBOqdMySprhH3iUcg_9)) { raiseOverflow(); goto LA12_;
					};
					splitsX60gensym34__1 = (NI)(TM__Vbi6rBBOqdMySprhH3iUcg_9);
					if (nimAddInt(lastX60gensym34__1, ((NI)1), &TM__Vbi6rBBOqdMySprhH3iUcg_10)) { raiseOverflow(); goto LA12_;
					};
					lastX60gensym34__1 = (NI)(TM__Vbi6rBBOqdMySprhH3iUcg_10);
					{
						LA12_:;
					}
					{
						if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA9_;
				} LA11: ;
			} LA10: ;
			{
				LA9_:;
			}
			{
				if (colontmp_.p && !(colontmp_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmp_.p);
}
				if (middle_1.p && !(middle_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(middle_1.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
		}
		{
			LA7_:;
		}
		{
			if (suffix_1.p && !(suffix_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(suffix_1.p);
}
			if (prefix_1.p && !(prefix_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(prefix_1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA5_: ;
	{
		NimStringV2 colontmpD__2;
		colontmpD__2 = eqdup___system_u2726(s_p0);
		add__stdZenumutils_u70((&(*dest_p1)), colontmpD__2);
	}
LA1_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void*, loadLibPattern__pureZdynlib_u93)(NimStringV2 pattern_p0, NIM_BOOL globalSymbols_p1) {
	void* result;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ candidates_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	candidates_1.len = 0; candidates_1.p = NIM_NIL;
	result = 0;
	candidates_1 = newSeq__stdZsyncio_u668(((NI)0));
	libCandidates__pureZdynlib_u81(pattern_p0, (&candidates_1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NimStringV2* c_1;
		NI i_1;
		NI L_1;
		NI T3_;
		c_1 = (NimStringV2*)0;
		i_1 = ((NI)0);
		T3_ = candidates_1.len;
		L_1 = T3_;
		{
			while (1) {
				if (!(i_1 < L_1)) goto LA5;
				if (i_1 < 0 || i_1 >= candidates_1.len){ raiseIndexError2(i_1,candidates_1.len-1); goto LA1_;
				}
				c_1 = (&candidates_1.p->data[i_1]);
				result = loadLib__pureZdynlib_u3((*c_1), globalSymbols_p1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				{
					if (!!((result == 0))) goto LA8_;
					goto LA2;
				}
LA8_: ;
				i_1 += ((NI)1);
				{
					NI T12_;
					T12_ = candidates_1.len;
					if (!!((T12_ == L_1))) goto LA13_;
					failedAssertImpl__stdZassertions_u95(TM__Vbi6rBBOqdMySprhH3iUcg_12);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
LA13_: ;
			} LA5: ;
		}
	} LA2: ;
	{
		LA1_:;
	}
	{
		eqdestroy___system_u5522(candidates_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseInvalidLibrary__pureZdynlib_u9)(NCSTRING name_p0) {
	NimStringV2 colontmpD_;
	tyObject_LibraryError__wQ8HJvjvvAFBKQzcDhTzGw* T2_;
	NimStringV2 T3_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T2_ = NIM_NIL;
	T2_ = (tyObject_LibraryError__wQ8HJvjvvAFBKQzcDhTzGw*) nimNewObj(sizeof(tyObject_LibraryError__wQ8HJvjvvAFBKQzcDhTzGw), NIM_ALIGNOF(tyObject_LibraryError__wQ8HJvjvvAFBKQzcDhTzGw));
	(*T2_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__wQ8HJvjvvAFBKQzcDhTzGw_);
	(*T2_).Sup.Sup.Sup.name = "LibraryError";
	T3_.len = 0; T3_.p = NIM_NIL;
	colontmpD_ = cstrToNimstr(name_p0);
	T3_ = rawNewString(colontmpD_.len + 23);
appendString((&T3_), TM__Vbi6rBBOqdMySprhH3iUcg_14);
appendString((&T3_), colontmpD_);
	(*T2_).Sup.Sup.Sup.message = T3_;
	(*T2_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
	raiseExceptionEx((Exception*)T2_, "LibraryError", "raiseInvalidLibrary", "dynlib.nim", 64);
goto LA1_;
	{
		LA1_:;
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
