/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -IC:\Bar\nim\lib -Ic:\UserProgram\nim\pipet\src -o c:\UserProgram\nim\pipet\releasecache\@pnativesockets.nim.c.o c:\UserProgram\nim\pipet\releasecache\@pnativesockets.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include "winsock2.h"
#include "ws2tcpip.h"
#include <string.h>
#include <time.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_Option__9cUC4e6LkhW2GXJRqvR40EA tyObject_Option__9cUC4e6LkhW2GXJRqvR40EA;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g tySequence__qwqHTkRvwhrRyENtudHQ7g;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content tySequence__qwqHTkRvwhrRyENtudHQ7g_Content;
typedef struct tyObject_TFdSet__7mAQXWFm20ZkUPyr58HWoQ tyObject_TFdSet__7mAQXWFm20ZkUPyr58HWoQ;
typedef NIM_CHAR tyArray__M1MIhyWfJiK2kKGZ3KroNQ[257];
typedef NIM_CHAR tyArray__Ncq6UF9bjTzftMKrv7nlG9bw[129];
typedef N_STDCALL_PTR(int, tyProc__7M7qTcL63tl4tTDq1F5YkA) (NI16 wVersionRequired_p0, WSADATA* WSData_p1);
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_Domain__Yif4bn0bsIUECeGYAvfo7w;
typedef NU8 tyEnum_SockType__2ci9b9b9bxg1YFPV9bSnCQcfUA;
typedef NU8 tyEnum_Protocol__otnLl7OYkVO1z0YaRP55mg;
typedef N_STDCALL_PTR(NI, tyProc__obvX9aCjUSOug1OhDFxNY5w) (int af_p0, int typ_p1, int protocol_p2);
typedef N_STDCALL_PTR(int, tyProc__8AQYtdBfYYnjlMVglJvZFw) (NI s_p0);
typedef N_STDCALL_PTR(int, tyProc__bE3vFIdpPKgMtseRoKfolQ) (NCSTRING nodename_p0, NCSTRING servname_p1, ADDRINFOA* hints_p2, ADDRINFOA** res_p3);
struct tyObject_Option__9cUC4e6LkhW2GXJRqvR40EA {
	tyEnum_Domain__Yif4bn0bsIUECeGYAvfo7w val;
	NIM_BOOL has;
};
struct tySequence__qwqHTkRvwhrRyENtudHQ7g {
  NI len; tySequence__qwqHTkRvwhrRyENtudHQ7g_Content* p;
};
typedef NI tyArray__55HWHOKdXPx6AXLoT9boTtA[64];
struct tyObject_TFdSet__7mAQXWFm20ZkUPyr58HWoQ {
	int fd_count;
	tyArray__55HWHOKdXPx6AXLoT9boTtA fd_array;
};
typedef N_STDCALL_PTR(int, tyProc__JGG9a0M9aJHXz4XU7BR6cfTg) (int nfds_p0, tyObject_TFdSet__7mAQXWFm20ZkUPyr58HWoQ* readfds_p1, tyObject_TFdSet__7mAQXWFm20ZkUPyr58HWoQ* writefds_p2, tyObject_TFdSet__7mAQXWFm20ZkUPyr58HWoQ* exceptfds_p3, struct timeval* timeout_p4);
typedef NIM_CHAR tyArray__AY9b9cftHbCDp9awOr5wvXtwg[14];
struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content { NI cap; NI data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__stdZoserrors_u122)(NI32 errorCode_p0, NimStringV2 additionalInfo_p1);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__stdZoserrors_u125)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NI, createNativeSocket__pureZnativesockets_u230)(int domain_p0, int sockType_p1, int protocol_p2, NIM_BOOL inheritable_p3);
static N_INLINE(NIM_BOOL, setInheritable__pureZnativesockets_u226)(NI s_p0, NIM_BOOL inheritable_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, setInheritable__stdZsyncio_u307)(NI f_p0, NIM_BOOL inheritable_p1);
N_LIB_PRIVATE N_NIMCALL(void, close__pureZnativesockets_u224)(NI socket_p0);
N_LIB_PRIVATE N_NIMCALL(int, toInt__pureZnativesockets_u74)(tyEnum_Domain__Yif4bn0bsIUECeGYAvfo7w domain_p0);
N_LIB_PRIVATE N_NIMCALL(int, toInt__pureZnativesockets_u76)(tyEnum_SockType__2ci9b9b9bxg1YFPV9bSnCQcfUA typ_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(int, toInt__pureZnativesockets_u78)(tyEnum_Protocol__otnLl7OYkVO1z0YaRP55mg p_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(ADDRINFOA*, getAddrInfo__pureZnativesockets_u252)(NimStringV2 address_p0, NU16 port_p1, ADDRINFOA hints_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u49)(NU16 xX60gensym7__p0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(tyObject_Option__9cUC4e6LkhW2GXJRqvR40EA, some__pureZnativesockets_u95)(tyEnum_Domain__Yif4bn0bsIUECeGYAvfo7w val_p0);
static N_INLINE(tyObject_Option__9cUC4e6LkhW2GXJRqvR40EA, none__pureZnativesockets_u146)(void);
N_LIB_PRIVATE N_NIMCALL(struct timeval, timeValFromMilliseconds__pureZnativesockets_u813)(NI timeout_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, createFdSet__pureZnativesockets_u841)(tyObject_TFdSet__7mAQXWFm20ZkUPyr58HWoQ* fd_p0, tySequence__qwqHTkRvwhrRyENtudHQ7g s_p1, NI* m_p2);
N_LIB_PRIVATE N_NIMCALL(void, FD_ZERO__windowsZwinlean_u538)(tyObject_TFdSet__7mAQXWFm20ZkUPyr58HWoQ* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, FD_SET__windowsZwinlean_u512)(NI socket_p0, tyObject_TFdSet__7mAQXWFm20ZkUPyr58HWoQ* s_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, pruneSocketSet__pureZnativesockets_u988)(tySequence__qwqHTkRvwhrRyENtudHQ7g* s_p0, tyObject_TFdSet__7mAQXWFm20ZkUPyr58HWoQ* fd_p1);
N_LIB_PRIVATE N_NIMCALL(int, FD_ISSET__windowsZwinlean_u508)(NI socket_p0, tyObject_TFdSet__7mAQXWFm20ZkUPyr58HWoQ* set_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLen__pureZnativesockets_u910)(tySequence__qwqHTkRvwhrRyENtudHQ7g* s_p0, NI newlen_p1);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__f9bP3LqjpgpB9cXL8Nnak7tQ_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__f9bP3LqjpgpB9cXL8Nnak7tQ_3 = {0, (NimStrPayload*)&TM__f9bP3LqjpgpB9cXL8Nnak7tQ_2};
static const NimStringV2 TM__f9bP3LqjpgpB9cXL8Nnak7tQ_4 = {0, (NimStrPayload*)&TM__f9bP3LqjpgpB9cXL8Nnak7tQ_2};
static const NimStringV2 TM__f9bP3LqjpgpB9cXL8Nnak7tQ_5 = {0, (NimStrPayload*)&TM__f9bP3LqjpgpB9cXL8Nnak7tQ_2};
static const struct {
  NI cap; NIM_CHAR data[90+1];
} TM__f9bP3LqjpgpB9cXL8Nnak7tQ_9 = { 90 | NIM_STRLIT_FLAG, "iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__f9bP3LqjpgpB9cXL8Nnak7tQ_10 = {90, (NimStrPayload*)&TM__f9bP3LqjpgpB9cXL8Nnak7tQ_9};
N_LIB_PRIVATE NI osInvalidSocket__pureZnativesockets_u48;
N_LIB_PRIVATE WSADATA wsa__pureZnativesockets_u1105;
extern tyProc__7M7qTcL63tl4tTDq1F5YkA Dl_1912603164_;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4167;
extern tyProc__obvX9aCjUSOug1OhDFxNY5w Dl_1912603045_;
extern tyProc__8AQYtdBfYYnjlMVglJvZFw Dl_1912603049_;
extern tyProc__bE3vFIdpPKgMtseRoKfolQ Dl_1912603167_;
extern tyProc__JGG9a0M9aJHXz4XU7BR6cfTg Dl_1912603098_;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4167);
	return result;
}
static N_INLINE(NIM_BOOL, setInheritable__pureZnativesockets_u226)(NI s_p0, NIM_BOOL inheritable_p1) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	result = setInheritable__stdZsyncio_u307(s_p0, inheritable_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, close__pureZnativesockets_u224)(NI socket_p0) {
	int T1_;
	T1_ = (int)0;
	T1_ = Dl_1912603049_(socket_p0);
	(void)(T1_);
}
N_LIB_PRIVATE N_NIMCALL(NI, createNativeSocket__pureZnativesockets_u230)(int domain_p0, int sockType_p1, int protocol_p2, NIM_BOOL inheritable_p3) {
	NI result;
	int sockType_2;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	sockType_2 = sockType_p1;
	result = Dl_1912603045_(domain_p0, sockType_2, protocol_p2);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = setInheritable__pureZnativesockets_u226(result, inheritable_p3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T3_)) goto LA4_;
		close__pureZnativesockets_u224(result);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = osInvalidSocket__pureZnativesockets_u48;
		goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, toInt__pureZnativesockets_u74)(tyEnum_Domain__Yif4bn0bsIUECeGYAvfo7w domain_p0) {
	int result;
	result = (int)0;
	result = ((int) (((NU32) (domain_p0))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, toInt__pureZnativesockets_u76)(tyEnum_SockType__2ci9b9b9bxg1YFPV9bSnCQcfUA typ_p0) {
	int result;
{	result = (int)0;
	if ((typ_p0) < ((int)(-2147483647 -1)) || (typ_p0) > ((int)2147483647)){ raiseRangeErrorI(typ_p0, ((int)(-2147483647 -1)), ((int)2147483647)); goto BeforeRet_;
	}
	result = ((int) (typ_p0));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, toInt__pureZnativesockets_u78)(tyEnum_Protocol__otnLl7OYkVO1z0YaRP55mg p_p0) {
	int result;
{	result = (int)0;
	switch (p_p0) {
	case ((tyEnum_Protocol__otnLl7OYkVO1z0YaRP55mg)18):
	{
		result = ((int)0);
	}
	break;
	case ((tyEnum_Protocol__otnLl7OYkVO1z0YaRP55mg)21):
	{
		result = ((int)1);
	}
	break;
	case ((tyEnum_Protocol__otnLl7OYkVO1z0YaRP55mg)6):
	{
		result = ((int)6);
	}
	break;
	case ((tyEnum_Protocol__otnLl7OYkVO1z0YaRP55mg)17):
	{
		result = ((int)17);
	}
	break;
	case ((tyEnum_Protocol__otnLl7OYkVO1z0YaRP55mg)19):
	{
		result = ((int)41);
	}
	break;
	case ((tyEnum_Protocol__otnLl7OYkVO1z0YaRP55mg)22):
	{
		result = ((int)58);
	}
	break;
	default:
	{
		if ((p_p0) < ((int)(-2147483647 -1)) || (p_p0) > ((int)2147483647)){ raiseRangeErrorI(p_p0, ((int)(-2147483647 -1)), ((int)2147483647)); goto BeforeRet_;
		}
		result = ((int) (p_p0));
	}
	break;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, createNativeSocket__pureZnativesockets_u237)(tyEnum_Domain__Yif4bn0bsIUECeGYAvfo7w domain_p0, tyEnum_SockType__2ci9b9b9bxg1YFPV9bSnCQcfUA sockType_p1, tyEnum_Protocol__otnLl7OYkVO1z0YaRP55mg protocol_p2, NIM_BOOL inheritable_p3) {
	NI result;
	int T1_;
	int T2_;
	int T3_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	T1_ = (int)0;
	T1_ = toInt__pureZnativesockets_u74(domain_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = (int)0;
	T2_ = toInt__pureZnativesockets_u76(sockType_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T3_ = (int)0;
	T3_ = toInt__pureZnativesockets_u78(protocol_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = createNativeSocket__pureZnativesockets_u230(T1_, T2_, T3_, inheritable_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_SockType__2ci9b9b9bxg1YFPV9bSnCQcfUA, toSockType__pureZnativesockets_u170)(tyEnum_Protocol__otnLl7OYkVO1z0YaRP55mg protocol_p0) {
	tyEnum_SockType__2ci9b9b9bxg1YFPV9bSnCQcfUA result;
	tyEnum_SockType__2ci9b9b9bxg1YFPV9bSnCQcfUA T1_;
	T1_ = (tyEnum_SockType__2ci9b9b9bxg1YFPV9bSnCQcfUA)0;
	switch (protocol_p0) {
	case ((tyEnum_Protocol__otnLl7OYkVO1z0YaRP55mg)6):
	{
		result = ((tyEnum_SockType__2ci9b9b9bxg1YFPV9bSnCQcfUA)1);
	}
	break;
	case ((tyEnum_Protocol__otnLl7OYkVO1z0YaRP55mg)17):
	{
		result = ((tyEnum_SockType__2ci9b9b9bxg1YFPV9bSnCQcfUA)2);
	}
	break;
	case ((tyEnum_Protocol__otnLl7OYkVO1z0YaRP55mg)18):
	case ((tyEnum_Protocol__otnLl7OYkVO1z0YaRP55mg)19):
	case ((tyEnum_Protocol__otnLl7OYkVO1z0YaRP55mg)20):
	case ((tyEnum_Protocol__otnLl7OYkVO1z0YaRP55mg)21):
	case ((tyEnum_Protocol__otnLl7OYkVO1z0YaRP55mg)22):
	{
		result = ((tyEnum_SockType__2ci9b9b9bxg1YFPV9bSnCQcfUA)3);
	}
	break;
	default: __builtin_unreachable();
	}
	return result;
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(ADDRINFOA*, getAddrInfo__pureZnativesockets_u252)(NimStringV2 address_p0, NU16 port_p1, ADDRINFOA hints_p2) {
	ADDRINFOA* result;
	NimStringV2 socketPort_1;
	NimStringV2 T2_;
	int gaiResult_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (ADDRINFOA*)0;
	socketPort_1.len = 0; socketPort_1.p = NIM_NIL;
	result = ((ADDRINFOA*) NIM_NIL);
	T2_.len = 0; T2_.p = NIM_NIL;
	{
		int T5_;
		T5_ = (int)0;
		T5_ = toInt__pureZnativesockets_u76(((tyEnum_SockType__2ci9b9b9bxg1YFPV9bSnCQcfUA)3));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!(hints_p2.ai_socktype == T5_)) goto LA6_;
		socketPort_1 = TM__f9bP3LqjpgpB9cXL8Nnak7tQ_4;
	}
	goto LA3_;
LA6_: ;
	{
		socketPort_1 = dollar___systemZdollars_u49(port_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA3_: ;
	gaiResult_1 = Dl_1912603167_(nimToCStringConv(address_p0), nimToCStringConv(socketPort_1), (&hints_p2), &result);
	{
		NI32 T13_;
		if (!!((gaiResult_1 == ((NI32)0)))) goto LA11_;
		T13_ = (NI32)0;
		T13_ = osLastError__stdZoserrors_u125();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		raiseOSError__stdZoserrors_u122(T13_, TM__f9bP3LqjpgpB9cXL8Nnak7tQ_5);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA11_: ;
	{
		LA1_:;
	}
	{
		if (socketPort_1.p && !(socketPort_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(socketPort_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(ADDRINFOA*, getAddrInfo__pureZnativesockets_u278)(NimStringV2 address_p0, NU16 port_p1, tyEnum_Domain__Yif4bn0bsIUECeGYAvfo7w domain_p2, tyEnum_SockType__2ci9b9b9bxg1YFPV9bSnCQcfUA sockType_p3, tyEnum_Protocol__otnLl7OYkVO1z0YaRP55mg protocol_p4) {
	ADDRINFOA* result;
	ADDRINFOA hints_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (ADDRINFOA*)0;
	nimZeroMem((void*)(&hints_1), sizeof(ADDRINFOA));
	hints_1.ai_family = toInt__pureZnativesockets_u74(domain_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	hints_1.ai_socktype = toInt__pureZnativesockets_u76(sockType_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	hints_1.ai_protocol = toInt__pureZnativesockets_u78(protocol_p4);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(domain_p2 == ((tyEnum_Domain__Yif4bn0bsIUECeGYAvfo7w)23))) goto LA3_;
		hints_1.ai_flags = ((int)8);
	}
LA3_: ;
	result = getAddrInfo__pureZnativesockets_u252(address_p0, port_p1, hints_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(tyObject_Option__9cUC4e6LkhW2GXJRqvR40EA, some__pureZnativesockets_u95)(tyEnum_Domain__Yif4bn0bsIUECeGYAvfo7w val_p0) {
	tyObject_Option__9cUC4e6LkhW2GXJRqvR40EA result;
	nimZeroMem((void*)(&result), sizeof(tyObject_Option__9cUC4e6LkhW2GXJRqvR40EA));
	result.has = NIM_TRUE;
	result.val = val_p0;
	return result;
}
static N_INLINE(tyObject_Option__9cUC4e6LkhW2GXJRqvR40EA, none__pureZnativesockets_u146)(void) {
	tyObject_Option__9cUC4e6LkhW2GXJRqvR40EA result;
	nimZeroMem((void*)(&result), sizeof(tyObject_Option__9cUC4e6LkhW2GXJRqvR40EA));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Option__9cUC4e6LkhW2GXJRqvR40EA, toKnownDomain__pureZnativesockets_u87)(int family_p0) {
	tyObject_Option__9cUC4e6LkhW2GXJRqvR40EA result;
	tyObject_Option__9cUC4e6LkhW2GXJRqvR40EA T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Option__9cUC4e6LkhW2GXJRqvR40EA));
	{
		if (!(family_p0 == ((NI32)0))) goto LA4_;
		result = some__pureZnativesockets_u95(((tyEnum_Domain__Yif4bn0bsIUECeGYAvfo7w)0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA2_;
LA4_: ;
	{
		if (!(family_p0 == ((NI32)2))) goto LA7_;
		result = some__pureZnativesockets_u95(((tyEnum_Domain__Yif4bn0bsIUECeGYAvfo7w)2));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA2_;
LA7_: ;
	{
		if (!(family_p0 == ((NI32)23))) goto LA10_;
		result = some__pureZnativesockets_u95(((tyEnum_Domain__Yif4bn0bsIUECeGYAvfo7w)23));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA2_;
LA10_: ;
	{
		result = none__pureZnativesockets_u146();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA2_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(struct timeval, timeValFromMilliseconds__pureZnativesockets_u813)(NI timeout_p0) {
	struct timeval result;
{	nimZeroMem((void*)(&result), sizeof(struct timeval));
	{
		NI seconds_1;
		NI TM__f9bP3LqjpgpB9cXL8Nnak7tQ_6;
		NI TM__f9bP3LqjpgpB9cXL8Nnak7tQ_7;
		NI TM__f9bP3LqjpgpB9cXL8Nnak7tQ_8;
		if (!!((timeout_p0 == ((NI)-1)))) goto LA3_;
		seconds_1 = (NI)((timeout_p0) / (((NI)1000)));
		if ((seconds_1) < ((NI32)(-2147483647 -1)) || (seconds_1) > ((NI32)2147483647)){ raiseRangeErrorI(seconds_1, ((NI32)(-2147483647 -1)), ((NI32)2147483647)); goto BeforeRet_;
		}
		result.tv_sec = ((NI32) (seconds_1));
		if (nimMulInt(seconds_1, ((NI)1000), &TM__f9bP3LqjpgpB9cXL8Nnak7tQ_6)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimSubInt(timeout_p0, (NI)(TM__f9bP3LqjpgpB9cXL8Nnak7tQ_6), &TM__f9bP3LqjpgpB9cXL8Nnak7tQ_7)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimMulInt((NI)(TM__f9bP3LqjpgpB9cXL8Nnak7tQ_7), ((NI)1000), &TM__f9bP3LqjpgpB9cXL8Nnak7tQ_8)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__f9bP3LqjpgpB9cXL8Nnak7tQ_8)) < ((NI32)(-2147483647 -1)) || ((NI)(TM__f9bP3LqjpgpB9cXL8Nnak7tQ_8)) > ((NI32)2147483647)){ raiseRangeErrorI((NI)(TM__f9bP3LqjpgpB9cXL8Nnak7tQ_8), ((NI32)(-2147483647 -1)), ((NI32)2147483647)); goto BeforeRet_;
		}
		result.tv_usec = ((NI32) ((NI)(TM__f9bP3LqjpgpB9cXL8Nnak7tQ_8)));
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, createFdSet__pureZnativesockets_u841)(tyObject_TFdSet__7mAQXWFm20ZkUPyr58HWoQ* fd_p0, tySequence__qwqHTkRvwhrRyENtudHQ7g s_p1, NI* m_p2) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	FD_ZERO__windowsZwinlean_u538(fd_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI* i_1;
		NI i_2;
		NI L_1;
		NI T2_;
		i_1 = (NI*)0;
		i_2 = ((NI)0);
		T2_ = s_p1.len;
		L_1 = T2_;
		{
			while (1) {
				if (!(i_2 < L_1)) goto LA4;
				if (i_2 < 0 || i_2 >= s_p1.len){ raiseIndexError2(i_2,s_p1.len-1); goto BeforeRet_;
				}
				i_1 = (&s_p1.p->data[i_2]);
				(*m_p2) = (((*m_p2) >= (*i_1)) ? (*m_p2) : (*i_1));
				FD_SET__windowsZwinlean_u512((*i_1), fd_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				i_2 += ((NI)1);
				{
					NI T7_;
					T7_ = s_p1.len;
					if (!!((T7_ == L_1))) goto LA8_;
					failedAssertImpl__stdZassertions_u95(TM__f9bP3LqjpgpB9cXL8Nnak7tQ_10);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA8_: ;
			} LA4: ;
		}
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, pruneSocketSet__pureZnativesockets_u988)(tySequence__qwqHTkRvwhrRyENtudHQ7g* s_p0, tyObject_TFdSet__7mAQXWFm20ZkUPyr58HWoQ* fd_p1) {
	NI i_1;
	NI L_1;
	NI T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	i_1 = ((NI)0);
	T1_ = (*s_p0).len;
	L_1 = T1_;
	{
		while (1) {
			if (!(i_1 < L_1)) goto LA3;
			{
				int T6_;
				NI TM__f9bP3LqjpgpB9cXL8Nnak7tQ_13;
				NI TM__f9bP3LqjpgpB9cXL8Nnak7tQ_14;
				if (i_1 < 0 || i_1 >= (*s_p0).len){ raiseIndexError2(i_1,(*s_p0).len-1); goto BeforeRet_;
				}
				T6_ = (int)0;
				T6_ = FD_ISSET__windowsZwinlean_u508((*s_p0).p->data[i_1], fd_p1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!(T6_ == ((NI32)0))) goto LA7_;
				if (i_1 < 0 || i_1 >= (*s_p0).len){ raiseIndexError2(i_1,(*s_p0).len-1); goto BeforeRet_;
				}
				if (nimSubInt(L_1, ((NI)1), &TM__f9bP3LqjpgpB9cXL8Nnak7tQ_13)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__f9bP3LqjpgpB9cXL8Nnak7tQ_13) < 0 || (NI)(TM__f9bP3LqjpgpB9cXL8Nnak7tQ_13) >= (*s_p0).len){ raiseIndexError2((NI)(TM__f9bP3LqjpgpB9cXL8Nnak7tQ_13),(*s_p0).len-1); goto BeforeRet_;
				}
				(*s_p0).p->data[i_1] = (*s_p0).p->data[(NI)(TM__f9bP3LqjpgpB9cXL8Nnak7tQ_13)];
				if (nimSubInt(L_1, ((NI)1), &TM__f9bP3LqjpgpB9cXL8Nnak7tQ_14)) { raiseOverflow(); goto BeforeRet_;
				};
				L_1 = (NI)(TM__f9bP3LqjpgpB9cXL8Nnak7tQ_14);
			}
			goto LA4_;
LA7_: ;
			{
				NI TM__f9bP3LqjpgpB9cXL8Nnak7tQ_15;
				if (nimAddInt(i_1, ((NI)1), &TM__f9bP3LqjpgpB9cXL8Nnak7tQ_15)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__f9bP3LqjpgpB9cXL8Nnak7tQ_15);
			}
LA4_: ;
		} LA3: ;
	}
	if ((L_1) < ((NI)0) || (L_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(L_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	setLen__pureZnativesockets_u910((&(*s_p0)), (L_1));
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, selectRead__pureZnativesockets_u1010)(tySequence__qwqHTkRvwhrRyENtudHQ7g* readfds_p0, NI timeout_p1) {
	NI result;
	struct timeval tv_1;
	tyObject_TFdSet__7mAQXWFm20ZkUPyr58HWoQ rd_1;
	NI m_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	tv_1 = timeValFromMilliseconds__pureZnativesockets_u813(timeout_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&rd_1), sizeof(tyObject_TFdSet__7mAQXWFm20ZkUPyr58HWoQ));
	nimZeroMem((void*)(&rd_1), sizeof(tyObject_TFdSet__7mAQXWFm20ZkUPyr58HWoQ));
	m_1 = ((NI)0);
	createFdSet__pureZnativesockets_u841((&rd_1), (*readfds_p0), (&m_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI TM__f9bP3LqjpgpB9cXL8Nnak7tQ_11;
		int T5_;
		if (!!((timeout_p1 == ((NI)-1)))) goto LA3_;
		if (nimAddInt(m_1, ((NI)1), &TM__f9bP3LqjpgpB9cXL8Nnak7tQ_11)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__f9bP3LqjpgpB9cXL8Nnak7tQ_11)) < ((int)(-2147483647 -1)) || ((NI)(TM__f9bP3LqjpgpB9cXL8Nnak7tQ_11)) > ((int)2147483647)){ raiseRangeErrorI((NI)(TM__f9bP3LqjpgpB9cXL8Nnak7tQ_11), ((int)(-2147483647 -1)), ((int)2147483647)); goto BeforeRet_;
		}
		T5_ = (int)0;
		T5_ = Dl_1912603098_(((int) ((NI)(TM__f9bP3LqjpgpB9cXL8Nnak7tQ_11))), (&rd_1), ((tyObject_TFdSet__7mAQXWFm20ZkUPyr58HWoQ*) NIM_NIL), ((tyObject_TFdSet__7mAQXWFm20ZkUPyr58HWoQ*) NIM_NIL), (&tv_1));
		result = ((NI) (T5_));
	}
	goto LA1_;
LA3_: ;
	{
		NI TM__f9bP3LqjpgpB9cXL8Nnak7tQ_12;
		int T7_;
		if (nimAddInt(m_1, ((NI)1), &TM__f9bP3LqjpgpB9cXL8Nnak7tQ_12)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__f9bP3LqjpgpB9cXL8Nnak7tQ_12)) < ((int)(-2147483647 -1)) || ((NI)(TM__f9bP3LqjpgpB9cXL8Nnak7tQ_12)) > ((int)2147483647)){ raiseRangeErrorI((NI)(TM__f9bP3LqjpgpB9cXL8Nnak7tQ_12), ((int)(-2147483647 -1)), ((int)2147483647)); goto BeforeRet_;
		}
		T7_ = (int)0;
		T7_ = Dl_1912603098_(((int) ((NI)(TM__f9bP3LqjpgpB9cXL8Nnak7tQ_12))), (&rd_1), ((tyObject_TFdSet__7mAQXWFm20ZkUPyr58HWoQ*) NIM_NIL), ((tyObject_TFdSet__7mAQXWFm20ZkUPyr58HWoQ*) NIM_NIL), ((struct timeval*) NIM_NIL));
		result = ((NI) (T7_));
	}
LA1_: ;
	pruneSocketSet__pureZnativesockets_u988(readfds_p0, (&rd_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZnativesockets_u890)(tySequence__qwqHTkRvwhrRyENtudHQ7g dest_p0) {
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(NI));
}
}
N_LIB_PRIVATE N_NIMCALL(void, atpnativesocketsdotnim_Init000)(void) {
{
NIM_BOOL* nimErr_;
nimErr_ = nimErrorFlag();
	osInvalidSocket__pureZnativesockets_u48 = INVALID_SOCKET;
	{
		int T3_;
		NI32 T6_;
		T3_ = (int)0;
		T3_ = Dl_1912603164_(((NI16)257), (&wsa__pureZnativesockets_u1105));
		if (!!((T3_ == ((NI32)0)))) goto LA4_;
		T6_ = (NI32)0;
		T6_ = osLastError__stdZoserrors_u125();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_u122(T6_, TM__f9bP3LqjpgpB9cXL8Nnak7tQ_3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	BeforeRet_: ;
	nimTestErrorFlag();
}
}

