/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -IC:\Bar\nim\lib -Ic:\UserProgram\nim\pipet\src -o c:\UserProgram\nim\pipet\releasecache\@pos.nim.c.o c:\UserProgram\nim\pipet\releasecache\@pos.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg tyTuple__7q7q3E6Oj24ZNVJb9aonhAg;
typedef struct tyObject_WideCStringObj__bFQqwXHGjLs9ce89aYpQn9brg tyObject_WideCStringObj__bFQqwXHGjLs9ce89aYpQn9brg;
typedef struct tyObject_WIN32_FIND_DATA__ulD27v0fv4hg9bIsy64801A tyObject_WIN32_FIND_DATA__ulD27v0fv4hg9bIsy64801A;
typedef struct tyObject_FILETIME__5tqos9a9by0xzVmQAXgvHTCQ tyObject_FILETIME__5tqos9a9by0xzVmQAXgvHTCQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg {
	NimStringV2 Field0;
	NimStringV2 Field1;
	NimStringV2 Field2;
};
struct tyObject_WideCStringObj__bFQqwXHGjLs9ce89aYpQn9brg {
	NI bytes;
	NI16* data;
};
typedef N_STDCALL_PTR(NI32, tyProc__G0MNqLrkAnRVz4cDlgVcRg) (NI handle_p0, NI16* buf_p1, NI32 size_p2);
typedef NI16 tyUncheckedArray__Tyd4y3haUOOHTj71TPIRag[1];
struct tyObject_FILETIME__5tqos9a9by0xzVmQAXgvHTCQ {
	NI32 dwLowDateTime;
	NI32 dwHighDateTime;
};
typedef NI16 tyArray__LoJqvPSqEF5orHITImkM3w[260];
typedef NI16 tyArray__J4EPyC6TWXoweaYf82ytWw[14];
struct tyObject_WIN32_FIND_DATA__ulD27v0fv4hg9bIsy64801A {
	NI32 dwFileAttributes;
	tyObject_FILETIME__5tqos9a9by0xzVmQAXgvHTCQ ftCreationTime;
	tyObject_FILETIME__5tqos9a9by0xzVmQAXgvHTCQ ftLastAccessTime;
	tyObject_FILETIME__5tqos9a9by0xzVmQAXgvHTCQ ftLastWriteTime;
	NI32 nFileSizeHigh;
	NI32 nFileSizeLow;
	NI32 dwReserved0;
	NI32 dwReserved1;
	tyArray__LoJqvPSqEF5orHITImkM3w cFileName;
	tyArray__J4EPyC6TWXoweaYf82ytWw cAlternateFileName;
};
typedef N_STDCALL_PTR(void, tyProc__ofoySXaAAlxxs9bQS9a1etlg) (NI hFindFile_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, nossplitFile)(NimStringV2 path_p0, tyTuple__7q7q3E6Oj24ZNVJb9aonhAg* Result);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetAppFilename)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__bFQqwXHGjLs9ce89aYpQn9brg, newWideCString__stdZwidestrs_u278)(NI size_p0);
static N_INLINE(NI16*, toWideCString__stdZwidestrs_u49)(tyObject_WideCStringObj__bFQqwXHGjLs9ce89aYpQn9brg x_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2729)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___stdZwidestrs_u35)(tyObject_WideCStringObj__bFQqwXHGjLs9ce89aYpQn9brg* a_p0, tyObject_WideCStringObj__bFQqwXHGjLs9ce89aYpQn9brg b_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZwidestrs_u7)(tyObject_WideCStringObj__bFQqwXHGjLs9ce89aYpQn9brg a_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___stdZwidestrs_u397)(tyObject_WideCStringObj__bFQqwXHGjLs9ce89aYpQn9brg s_p0, NI estimate_p1, NI replacement_p2);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2720)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZprivateZosdirs_u85)(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(NI, findFirstFile__stdZprivateZoscommon_u24)(NimStringV2 a_p0, tyObject_WIN32_FIND_DATA__ulD27v0fv4hg9bIsy64801A* b_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__stdZoserrors_u122)(NI32 errorCode_p0, NimStringV2 additionalInfo_p1);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__stdZoserrors_u125)(void);
N_LIB_PRIVATE N_NIMCALL(NI64, rdFileSize__windowsZwinlean_u289)(tyObject_WIN32_FIND_DATA__ulD27v0fv4hg9bIsy64801A* f_p0);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_3 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_2};
extern tyProc__G0MNqLrkAnRVz4cDlgVcRg Dl_1912602819_;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4167;
extern tyProc__ofoySXaAAlxxs9bQS9a1etlg Dl_1912602879_;
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NI16*, toWideCString__stdZwidestrs_u49)(tyObject_WideCStringObj__bFQqwXHGjLs9ce89aYpQn9brg x_p0) {
	NI16* result;
	result = x_p0.data;
	return result;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4167);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetAppFilename)(void) {
	NimStringV2 result;
	tyObject_WideCStringObj__bFQqwXHGjLs9ce89aYpQn9brg buf_1;
	NI32 bufsize_1;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimZeroMem((void*)(&buf_1), sizeof(tyObject_WideCStringObj__bFQqwXHGjLs9ce89aYpQn9brg));
	bufsize_1 = ((NI32)260);
	buf_1 = newWideCString__stdZwidestrs_u278(((NI) (bufsize_1)));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		while (1) {
			NI32 L_1;
			NI16* T4_;
			T4_ = (NI16*)0;
			T4_ = toWideCString__stdZwidestrs_u49(buf_1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			L_1 = Dl_1912602819_(((NI)0), T4_, bufsize_1);
			{
				if (!(L_1 == ((NI32)0))) goto LA7_;
				eqsink___system_u2729((&result), TM__yu6cxgKBBXbNsTkT9cyMd4g_3);
				goto LA2;
			}
			goto LA5_;
LA7_: ;
			{
				tyObject_WideCStringObj__bFQqwXHGjLs9ce89aYpQn9brg T12_;
				if (!(bufsize_1 < L_1)) goto LA10_;
				T12_ = newWideCString__stdZwidestrs_u278(((NI) (L_1)));
				if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___stdZwidestrs_u7(T12_); goto LA1_;}
				eqsink___stdZwidestrs_u35((&buf_1), T12_);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				bufsize_1 = L_1;
			}
			goto LA5_;
LA10_: ;
			{
				NimStringV2 T14_;
				T14_.len = 0; T14_.p = NIM_NIL;
				T14_ = dollar___stdZwidestrs_u397(buf_1, ((NI) (L_1)), ((NI)65533));
				if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T14_); goto LA1_;}
				eqsink___system_u2729((&result), T14_);
				goto LA2;
			}
LA5_: ;
		}
	} LA2: ;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___stdZwidestrs_u7(buf_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetAppDir)(void) {
	NimStringV2 result;
	tyTuple__7q7q3E6Oj24ZNVJb9aonhAg colontmpD_;
	NimStringV2 colontmpD__2;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimZeroMem((void*)(&colontmpD_), sizeof(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg));
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__2 = nosgetAppFilename();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nossplitFile(colontmpD__2, (&colontmpD_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = colontmpD_.Field0;
	eqwasMoved___system_u2720((&colontmpD_.Field0));
	if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
	eqdestroy___stdZprivateZosdirs_u85((&colontmpD_));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI64, nosgetFileSize)(NimStringV2 file_p0) {
	NI64 result;
	tyObject_WIN32_FIND_DATA__ulD27v0fv4hg9bIsy64801A a_1;
	NI resA_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI64)0;
	nimZeroMem((void*)(&a_1), sizeof(tyObject_WIN32_FIND_DATA__ulD27v0fv4hg9bIsy64801A));
	resA_1 = findFirstFile__stdZprivateZoscommon_u24(file_p0, (&a_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI32 T5_;
		if (!(resA_1 == ((NI)-1))) goto LA3_;
		T5_ = (NI32)0;
		T5_ = osLastError__stdZoserrors_u125();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_u122(T5_, file_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	result = rdFileSize__windowsZwinlean_u289((&a_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	Dl_1912602879_(resA_1);
	}BeforeRet_: ;
	return result;
}
