/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -IC:\Bar\nim\lib -Ic:\UserProgram\nim\pipet\src -o c:\UserProgram\nim\pipet\releasecache\@pparsecsv.nim.c.o c:\UserProgram\nim\pipet\releasecache\@pparsecsv.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_CsvParser__Te9b9cfNRUXkZxVA3nziwzGg tyObject_CsvParser__Te9b9cfNRUXkZxVA3nziwzGg;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_BaseLexer__DYlxS0NMFFvXig9bf59clM8g tyObject_BaseLexer__DYlxS0NMFFvXig9bf59clM8g;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_StreamObj__8LPgbR9amdAB22cblxKrICw tyObject_StreamObj__8LPgbR9amdAB22cblxKrICw;
typedef struct tyObject_RefHeader__o81VrNKMHlunlyoM3ZBjsA tyObject_RefHeader__o81VrNKMHlunlyoM3ZBjsA;
typedef struct tyObject_GcEnv__dfLj9cJKxY1182u9cKLmUHQQ tyObject_GcEnv__dfLj9cJKxY1182u9cKLmUHQQ;
typedef struct tyObject_CellSeq__aDGfh0VAJEN6RssjiTIRzA tyObject_CellSeq__aDGfh0VAJEN6RssjiTIRzA;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__H7XKrvr6v2cNjON3PXTaOg tyObject_CellSeq__H7XKrvr6v2cNjON3PXTaOg;
typedef struct tyTuple__HQOTPzS3RQ0QiMx9bwSn6Gw tyTuple__HQOTPzS3RQ0QiMx9bwSn6Gw;
typedef struct tyObject_CsvError__gKB0H0V9ce9cmvQncayAJOgg tyObject_CsvError__gKB0H0V9ce9cmvQncayAJOgg;
typedef struct tyObject_IOError__ALOnqndH9aDQS9csnW9c9a9bSUg tyObject_IOError__ALOnqndH9aDQS9csnW9c9a9bSUg;
typedef struct tyObject_CatchableError__5X2CqDk7Ldk7h9a22Zsg5kg tyObject_CatchableError__5X2CqDk7Ldk7h9a22Zsg5kg;
typedef struct Exception Exception;
typedef struct tySequence__xIN54dE1a4ZyAUnTpAuU2g tySequence__xIN54dE1a4ZyAUnTpAuU2g;
typedef struct tySequence__xIN54dE1a4ZyAUnTpAuU2g_Content tySequence__xIN54dE1a4ZyAUnTpAuU2g_Content;
typedef struct tyObject_KeyError__lMqmQfnmk57agJesML1viQ tyObject_KeyError__lMqmQfnmk57agJesML1viQ;
typedef struct tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw;
typedef struct tyObject_StackTraceEntry__2ELMRvKL5HlwpyV9cRIuTmw tyObject_StackTraceEntry__2ELMRvKL5HlwpyV9cRIuTmw;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_BaseLexer__DYlxS0NMFFvXig9bf59clM8g {
	RootObj Sup;
	NI bufpos;
	NimStringV2 buf;
	tyObject_StreamObj__8LPgbR9amdAB22cblxKrICw* input;
	NI lineNumber;
	NI sentinel;
	NI lineStart;
	NI offsetBase;
	tySet_tyChar__nmiMWKVIe46vacnhAFrQvw refillChars;
};
struct tyObject_CsvParser__Te9b9cfNRUXkZxVA3nziwzGg {
	tyObject_BaseLexer__DYlxS0NMFFvXig9bf59clM8g Sup;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ row;
	NimStringV2 filename;
	NIM_CHAR sep;
	NIM_CHAR quote;
	NIM_CHAR esc;
	NIM_BOOL skipWhite;
	NI currRow;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ headers;
};
struct tyObject_RefHeader__o81VrNKMHlunlyoM3ZBjsA {
	NI rc;
	NI rootIdx;
};
struct tyObject_CellSeq__aDGfh0VAJEN6RssjiTIRzA {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__H7XKrvr6v2cNjON3PXTaOg {
	NI len;
	NI cap;
	tyTuple__HQOTPzS3RQ0QiMx9bwSn6Gw* d;
};
struct tyObject_GcEnv__dfLj9cJKxY1182u9cKLmUHQQ {
	tyObject_CellSeq__aDGfh0VAJEN6RssjiTIRzA traceStack;
	tyObject_CellSeq__H7XKrvr6v2cNjON3PXTaOg toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
struct tySequence__xIN54dE1a4ZyAUnTpAuU2g {
  NI len; tySequence__xIN54dE1a4ZyAUnTpAuU2g_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__xIN54dE1a4ZyAUnTpAuU2g trace;
	Exception* up;
};
struct tyObject_CatchableError__5X2CqDk7Ldk7h9a22Zsg5kg {
	Exception Sup;
};
struct tyObject_IOError__ALOnqndH9aDQS9csnW9c9a9bSUg {
	tyObject_CatchableError__5X2CqDk7Ldk7h9a22Zsg5kg Sup;
};
struct tyObject_CsvError__gKB0H0V9ce9cmvQncayAJOgg {
	tyObject_IOError__ALOnqndH9aDQS9csnW9c9a9bSUg Sup;
};
struct tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw {
	tyObject_CatchableError__5X2CqDk7Ldk7h9a22Zsg5kg Sup;
};
struct tyObject_KeyError__lMqmQfnmk57agJesML1viQ {
	tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw Sup;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__2ELMRvKL5HlwpyV9cRIuTmw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__xIN54dE1a4ZyAUnTpAuU2g_Content { NI cap; tyObject_StackTraceEntry__2ELMRvKL5HlwpyV9cRIuTmw data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pureZparsecsv_u266)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecsv_u91)(tyObject_CsvParser__Te9b9cfNRUXkZxVA3nziwzGg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5522)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3522)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__o81VrNKMHlunlyoM3ZBjsA* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZparsecsv_u103)(tyObject_CsvParser__Te9b9cfNRUXkZxVA3nziwzGg* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u3043)(tyObject_CellSeq__aDGfh0VAJEN6RssjiTIRzA* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u3051)(tyObject_CellSeq__aDGfh0VAJEN6RssjiTIRzA* s_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, open__pureZlexbase_u144)(tyObject_BaseLexer__DYlxS0NMFFvXig9bf59clM8g* L_p0, tyObject_StreamObj__8LPgbR9amdAB22cblxKrICw* input_p1, NI bufLen_p2, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw refillChars_p3);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2723)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readRow__pureZparsecsv_u207)(tyObject_CsvParser__Te9b9cfNRUXkZxVA3nziwzGg* self_p0, NI columns_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(NI, handleCR__pureZlexbase_u91)(tyObject_BaseLexer__DYlxS0NMFFvXig9bf59clM8g* L_p0, NI pos_p1);
N_LIB_PRIVATE N_NIMCALL(NI, handleLF__pureZlexbase_u105)(tyObject_BaseLexer__DYlxS0NMFFvXig9bf59clM8g* L_p0, NI pos_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, setLen__system_u5426)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* s_p0, NI newlen_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2729)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, parseField__pureZparsecsv_u155)(tyObject_CsvParser__Te9b9cfNRUXkZxVA3nziwzGg* self_p0, NimStringV2* a_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, error__pureZparsecsv_u84)(tyObject_CsvParser__Te9b9cfNRUXkZxVA3nziwzGg* self_p0, NI pos_p1, NimStringV2 msg_p2);
N_LIB_PRIVATE N_NIMCALL(void, raiseEInvalidCsv__pureZparsecsv_u14)(NimStringV2 filename_p0, NI line_p1, NI col_p2, NimStringV2 msg_p3);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecsv_u26)(tyObject_CsvError__gKB0H0V9ce9cmvQncayAJOgg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pureZparsecsv_u282)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecsv_u46)(tyObject_CsvError__gKB0H0V9ce9cmvQncayAJOgg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3726)(tySequence__xIN54dE1a4ZyAUnTpAuU2g dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZparsecsv_u58)(tyObject_CsvError__gKB0H0V9ce9cmvQncayAJOgg* dest_p0, void* env_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
static N_INLINE(void, nimMarkCyclic)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pureZparsecsv_u23)(tyObject_CsvError__gKB0H0V9ce9cmvQncayAJOgg** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(NI, getColNumber__pureZlexbase_u163)(tyObject_BaseLexer__DYlxS0NMFFvXig9bf59clM8g* L_p0, NI pos_p1);
static N_INLINE(void, appendChar)(NimStringV2* dest_p0, NIM_CHAR c_p1);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u5525)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* dest_p0, tySequence__sM4lkSb7zS6F7OVMvW9cffQ src_p1);
static N_INLINE(NI, find__pureZparsecsv_u249)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ a_p0, NimStringV2 item_p1);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE TNimTypeV2 NTIv2__Te9b9cfNRUXkZxVA3nziwzGg_;
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__3rBY6NOHI29c34PPPPzLAdQ_3 = {
0x00, 0x24, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__3rBY6NOHI29c34PPPPzLAdQ_6 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__3rBY6NOHI29c34PPPPzLAdQ_7 = {0, (NimStrPayload*)&TM__3rBY6NOHI29c34PPPPzLAdQ_6};
N_LIB_PRIVATE TNimTypeV2 NTIv2__gKB0H0V9ce9cmvQncayAJOgg_;
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__3rBY6NOHI29c34PPPPzLAdQ_11 = { 7 | NIM_STRLIT_FLAG, "Error: " };
static const NimStringV2 TM__3rBY6NOHI29c34PPPPzLAdQ_12 = {7, (NimStrPayload*)&TM__3rBY6NOHI29c34PPPPzLAdQ_11};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__3rBY6NOHI29c34PPPPzLAdQ_13 = { 1 | NIM_STRLIT_FLAG, "(" };
static const NimStringV2 TM__3rBY6NOHI29c34PPPPzLAdQ_14 = {1, (NimStrPayload*)&TM__3rBY6NOHI29c34PPPPzLAdQ_13};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__3rBY6NOHI29c34PPPPzLAdQ_15 = { 2 | NIM_STRLIT_FLAG, ", " };
static const NimStringV2 TM__3rBY6NOHI29c34PPPPzLAdQ_16 = {2, (NimStrPayload*)&TM__3rBY6NOHI29c34PPPPzLAdQ_15};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__3rBY6NOHI29c34PPPPzLAdQ_17 = { 9 | NIM_STRLIT_FLAG, ") Error: " };
static const NimStringV2 TM__3rBY6NOHI29c34PPPPzLAdQ_18 = {9, (NimStrPayload*)&TM__3rBY6NOHI29c34PPPPzLAdQ_17};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__3rBY6NOHI29c34PPPPzLAdQ_19 = { 9 | NIM_STRLIT_FLAG, " expected" };
static const NimStringV2 TM__3rBY6NOHI29c34PPPPzLAdQ_20 = {9, (NimStrPayload*)&TM__3rBY6NOHI29c34PPPPzLAdQ_19};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__3rBY6NOHI29c34PPPPzLAdQ_26 = { 1 | NIM_STRLIT_FLAG, "\012" };
static const NimStringV2 TM__3rBY6NOHI29c34PPPPzLAdQ_27 = {1, (NimStrPayload*)&TM__3rBY6NOHI29c34PPPPzLAdQ_26};
static const NimStringV2 TM__3rBY6NOHI29c34PPPPzLAdQ_28 = {1, (NimStrPayload*)&TM__3rBY6NOHI29c34PPPPzLAdQ_26};
static const NimStringV2 TM__3rBY6NOHI29c34PPPPzLAdQ_33 = {9, (NimStrPayload*)&TM__3rBY6NOHI29c34PPPPzLAdQ_19};
static const struct {
  NI cap; NIM_CHAR data[29+1];
} TM__3rBY6NOHI29c34PPPPzLAdQ_35 = { 29 | NIM_STRLIT_FLAG, " columns expected, but found " };
static const NimStringV2 TM__3rBY6NOHI29c34PPPPzLAdQ_36 = {29, (NimStrPayload*)&TM__3rBY6NOHI29c34PPPPzLAdQ_35};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__3rBY6NOHI29c34PPPPzLAdQ_37 = { 8 | NIM_STRLIT_FLAG, " columns" };
static const NimStringV2 TM__3rBY6NOHI29c34PPPPzLAdQ_38 = {8, (NimStrPayload*)&TM__3rBY6NOHI29c34PPPPzLAdQ_37};
static const struct {
  NI cap; NIM_CHAR data[90+1];
} TM__3rBY6NOHI29c34PPPPzLAdQ_41 = { 90 | NIM_STRLIT_FLAG, "iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__3rBY6NOHI29c34PPPPzLAdQ_42 = {90, (NimStrPayload*)&TM__3rBY6NOHI29c34PPPPzLAdQ_41};
extern TNimTypeV2 NTIv2__lMqmQfnmk57agJesML1viQ_;
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__3rBY6NOHI29c34PPPPzLAdQ_43 = { 7 | NIM_STRLIT_FLAG, "Entry `" };
static const NimStringV2 TM__3rBY6NOHI29c34PPPPzLAdQ_44 = {7, (NimStrPayload*)&TM__3rBY6NOHI29c34PPPPzLAdQ_43};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__3rBY6NOHI29c34PPPPzLAdQ_45 = { 15 | NIM_STRLIT_FLAG, "` doesn\'t exist" };
static const NimStringV2 TM__3rBY6NOHI29c34PPPPzLAdQ_46 = {15, (NimStrPayload*)&TM__3rBY6NOHI29c34PPPPzLAdQ_45};
static NIM_CONST NU32 TM__3rBY6NOHI29c34PPPPzLAdQ_2[3] = {3701606400, 2305903360, 4022303744};
N_LIB_PRIVATE TNimTypeV2 NTIv2__Te9b9cfNRUXkZxVA3nziwzGg_ = {.destructor = (void*)rttiDestroy__pureZparsecsv_u266, .size = sizeof(tyObject_CsvParser__Te9b9cfNRUXkZxVA3nziwzGg), .align = (NI16) NIM_ALIGNOF(tyObject_CsvParser__Te9b9cfNRUXkZxVA3nziwzGg), .depth = 2, .display = TM__3rBY6NOHI29c34PPPPzLAdQ_2, .traceImpl = (void*)eqtrace___pureZparsecsv_u103, .flags = 0};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4167;
static NIM_CONST NU32 TM__3rBY6NOHI29c34PPPPzLAdQ_10[5] = {3701606400, 1285336064, 2105714688, 3014109696, 2691964672};
N_LIB_PRIVATE TNimTypeV2 NTIv2__gKB0H0V9ce9cmvQncayAJOgg_ = {.destructor = (void*)rttiDestroy__pureZparsecsv_u282, .size = sizeof(tyObject_CsvError__gKB0H0V9ce9cmvQncayAJOgg), .align = (NI16) NIM_ALIGNOF(tyObject_CsvError__gKB0H0V9ce9cmvQncayAJOgg), .depth = 4, .display = TM__3rBY6NOHI29c34PPPPzLAdQ_10, .traceImpl = (void*)eqtrace___pureZparsecsv_u58, .flags = 0};
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__o81VrNKMHlunlyoM3ZBjsA* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__o81VrNKMHlunlyoM3ZBjsA*) (T5_));
		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		rememberCycle__system_u3522(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecsv_u91)(tyObject_CsvParser__Te9b9cfNRUXkZxVA3nziwzGg* dest_p0) {
	eqdestroy___system_u5522((*dest_p0).headers);
	if ((*dest_p0).filename.p && !((*dest_p0).filename.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).filename.p);
}
	eqdestroy___system_u5522((*dest_p0).row);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.input);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.input);
	}
LA4_: ;
	if ((*dest_p0).Sup.buf.p && !((*dest_p0).Sup.buf.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.buf.p);
}
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pureZparsecsv_u266)(void* dest_p0) {
	eqdestroy___pureZparsecsv_u91(((tyObject_CsvParser__Te9b9cfNRUXkZxVA3nziwzGg*) (dest_p0)));
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(void, add__system_u3043)(tyObject_CellSeq__aDGfh0VAJEN6RssjiTIRzA* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		resize__system_u3051(s_p0);
	}
LA3_: ;
	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	(*s_p0).len = pluspercent___system_u793((*s_p0).len, ((NI)1));
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	p_1 = ((void**) (q_p0));
	{
		tyObject_GcEnv__dfLj9cJKxY1182u9cKLmUHQQ* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		j_1 = ((tyObject_GcEnv__dfLj9cJKxY1182u9cKLmUHQQ*) (env_p1));
		add__system_u3043((&(*j_1).traceStack), p_1, (*((TNimTypeV2**) ((*p_1)))));
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZparsecsv_u103)(tyObject_CsvParser__Te9b9cfNRUXkZxVA3nziwzGg* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.input, env_p1);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4167);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, open__pureZparsecsv_u135)(tyObject_CsvParser__Te9b9cfNRUXkZxVA3nziwzGg* self_p0, tyObject_StreamObj__8LPgbR9amdAB22cblxKrICw* input_p1, NimStringV2 filename_p2, NIM_CHAR separator_p3, NIM_CHAR quote_p4, NIM_CHAR escape_p5, NIM_BOOL skipInitialSpace_p6) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	open__pureZlexbase_u144(&self_p0->Sup, input_p1, ((NI)8192), TM__3rBY6NOHI29c34PPPPzLAdQ_3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqcopy___system_u2723((&(*self_p0).filename), filename_p2);
	(*self_p0).sep = separator_p3;
	(*self_p0).quote = quote_p4;
	(*self_p0).esc = escape_p5;
	(*self_p0).skipWhite = skipInitialSpace_p6;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecsv_u26)(tyObject_CsvError__gKB0H0V9ce9cmvQncayAJOgg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(dest_p0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(dest_p0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecsv_u46)(tyObject_CsvError__gKB0H0V9ce9cmvQncayAJOgg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3726((*dest_p0).Sup.Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pureZparsecsv_u282)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___pureZparsecsv_u46(((tyObject_CsvError__gKB0H0V9ce9cmvQncayAJOgg*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZparsecsv_u58)(tyObject_CsvError__gKB0H0V9ce9cmvQncayAJOgg* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(void, nimMarkCyclic)(void* p_p0) {
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pureZparsecsv_u23)(tyObject_CsvError__gKB0H0V9ce9cmvQncayAJOgg** dest_p0) {
	(*dest_p0) = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, raiseEInvalidCsv__pureZparsecsv_u14)(NimStringV2 filename_p0, NI line_p1, NI col_p2, NimStringV2 msg_p3) {
	tyObject_CsvError__gKB0H0V9ce9cmvQncayAJOgg* e_1;
	tyObject_CsvError__gKB0H0V9ce9cmvQncayAJOgg* blitTmp_1;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	e_1 = NIM_NIL;
	eqdestroy___pureZparsecsv_u26(e_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	e_1 = (tyObject_CsvError__gKB0H0V9ce9cmvQncayAJOgg*) nimNewObj(sizeof(tyObject_CsvError__gKB0H0V9ce9cmvQncayAJOgg), NIM_ALIGNOF(tyObject_CsvError__gKB0H0V9ce9cmvQncayAJOgg));
	(*e_1).Sup.Sup.Sup.Sup.m_type = (&NTIv2__gKB0H0V9ce9cmvQncayAJOgg_);
	(*e_1).Sup.Sup.Sup.name = "CsvError";
	{
		NimStringV2 T6_;
		if (!(filename_p0.len == ((NI)0))) goto LA4_;
		T6_.len = 0; T6_.p = NIM_NIL;
		T6_ = rawNewString(msg_p3.len + 7);
appendString((&T6_), TM__3rBY6NOHI29c34PPPPzLAdQ_12);
appendString((&T6_), msg_p3);
		eqsink___system_u2729((&(*e_1).Sup.Sup.Sup.message), T6_);
	}
	goto LA2_;
LA4_: ;
	{
		NimStringV2 colontmpD_;
		NimStringV2 colontmpD__2;
		NimStringV2 T8_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		T8_.len = 0; T8_.p = NIM_NIL;
		colontmpD_ = dollar___systemZdollars_u14(line_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		colontmpD__2 = dollar___systemZdollars_u14(col_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T8_ = rawNewString(filename_p0.len + colontmpD_.len + colontmpD__2.len + msg_p3.len + 12);
appendString((&T8_), filename_p0);
appendString((&T8_), TM__3rBY6NOHI29c34PPPPzLAdQ_14);
appendString((&T8_), colontmpD_);
appendString((&T8_), TM__3rBY6NOHI29c34PPPPzLAdQ_16);
appendString((&T8_), colontmpD__2);
appendString((&T8_), TM__3rBY6NOHI29c34PPPPzLAdQ_18);
appendString((&T8_), msg_p3);
		eqsink___system_u2729((&(*e_1).Sup.Sup.Sup.message), T8_);
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
LA2_: ;
	blitTmp_1 = e_1;
	nimMarkCyclic(e_1);
	eqwasMoved___pureZparsecsv_u23(&e_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	raiseExceptionEx((Exception*)blitTmp_1, "CsvError", "raiseEInvalidCsv", "parsecsv.nim", 102);
goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___pureZparsecsv_u26(e_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, error__pureZparsecsv_u84)(tyObject_CsvParser__Te9b9cfNRUXkZxVA3nziwzGg* self_p0, NI pos_p1, NimStringV2 msg_p2) {
	NI T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (NI)0;
	T1_ = getColNumber__pureZlexbase_u163((&(*self_p0).Sup), pos_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	raiseEInvalidCsv__pureZparsecsv_u14((*self_p0).filename, (*self_p0).Sup.lineNumber, T1_, msg_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, appendChar)(NimStringV2* dest_p0, NIM_CHAR c_p1) {
	(*(*dest_p0).p).data[(*dest_p0).len] = c_p1;
	(*dest_p0).len += ((NI)1);
	(*(*dest_p0).p).data[(*dest_p0).len] = 0;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	(*s_p0).len += ((NI)1);
	(*(*s_p0).p).data[(*s_p0).len] = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, parseField__pureZparsecsv_u155)(tyObject_CsvParser__Te9b9cfNRUXkZxVA3nziwzGg* self_p0, NimStringV2* a_p1) {
	NI pos_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	pos_1 = (*self_p0).Sup.bufpos;
	{
		if (!(*self_p0).skipWhite) goto LA3_;
		{
			while (1) {
				NI TM__3rBY6NOHI29c34PPPPzLAdQ_8;
				if (pos_1 < 0 || pos_1 >= (*self_p0).Sup.buf.len){ raiseIndexError2(pos_1,(*self_p0).Sup.buf.len-1); goto BeforeRet_;
				}
				if (!(((NU8)((*self_p0).Sup.buf.p->data[pos_1])) == ((NU8)(32)) || ((NU8)((*self_p0).Sup.buf.p->data[pos_1])) == ((NU8)(9)))) goto LA6;
				if (nimAddInt(pos_1, ((NI)1), &TM__3rBY6NOHI29c34PPPPzLAdQ_8)) { raiseOverflow(); goto BeforeRet_;
				};
				pos_1 = (NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_8);
			} LA6: ;
		}
	}
LA3_: ;
	setLengthStrV2((&(*a_p1)), ((NI)0));
	{
		NIM_BOOL T9_;
		NI TM__3rBY6NOHI29c34PPPPzLAdQ_9;
		T9_ = (NIM_BOOL)0;
		if (pos_1 < 0 || pos_1 >= (*self_p0).Sup.buf.len){ raiseIndexError2(pos_1,(*self_p0).Sup.buf.len-1); goto BeforeRet_;
		}
		T9_ = ((NU8)((*self_p0).Sup.buf.p->data[pos_1]) == (NU8)((*self_p0).quote));
		if (!(T9_)) goto LA10_;
		T9_ = !(((NU8)((*self_p0).quote) == (NU8)(0)));
LA10_: ;
		if (!T9_) goto LA11_;
		if (nimAddInt(pos_1, ((NI)1), &TM__3rBY6NOHI29c34PPPPzLAdQ_9)) { raiseOverflow(); goto BeforeRet_;
		};
		pos_1 = (NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_9);
		{
			while (1) {
				NIM_CHAR c_1;
				if (pos_1 < 0 || pos_1 >= (*self_p0).Sup.buf.len){ raiseIndexError2(pos_1,(*self_p0).Sup.buf.len-1); goto BeforeRet_;
				}
				c_1 = (*self_p0).Sup.buf.p->data[pos_1];
				{
					NimStringV2 colontmpD_;
					NimStringV2 T20_;
					if (!((NU8)(c_1) == (NU8)(0))) goto LA17_;
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
					(*self_p0).Sup.bufpos = pos_1;
					T20_.len = 0; T20_.p = NIM_NIL;
					T20_ = rawNewString(10);
appendChar((&T20_), (*self_p0).quote);
appendString((&T20_), TM__3rBY6NOHI29c34PPPPzLAdQ_20);
					colontmpD_ = T20_;
					error__pureZparsecsv_u84((&(*self_p0)), pos_1, colontmpD_);
					if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
					if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
					goto LA13;
					{
						LA19_:;
					}
					{
						if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
					}
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				goto LA15_;
LA17_: ;
				{
					if (!((NU8)(c_1) == (NU8)((*self_p0).quote))) goto LA24_;
					{
						NIM_BOOL T28_;
						NI TM__3rBY6NOHI29c34PPPPzLAdQ_21;
						NI TM__3rBY6NOHI29c34PPPPzLAdQ_22;
						T28_ = (NIM_BOOL)0;
						T28_ = ((NU8)((*self_p0).esc) == (NU8)(0));
						if (!(T28_)) goto LA29_;
						if (nimAddInt(pos_1, ((NI)1), &TM__3rBY6NOHI29c34PPPPzLAdQ_21)) { raiseOverflow(); goto BeforeRet_;
						};
						if ((NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_21) < 0 || (NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_21) >= (*self_p0).Sup.buf.len){ raiseIndexError2((NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_21),(*self_p0).Sup.buf.len-1); goto BeforeRet_;
						}
						T28_ = ((NU8)((*self_p0).Sup.buf.p->data[(NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_21)]) == (NU8)((*self_p0).quote));
LA29_: ;
						if (!T28_) goto LA30_;
						nimAddCharV1((&(*a_p1)), (*self_p0).quote);
						if (nimAddInt(pos_1, ((NI)2), &TM__3rBY6NOHI29c34PPPPzLAdQ_22)) { raiseOverflow(); goto BeforeRet_;
						};
						pos_1 = (NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_22);
					}
					goto LA26_;
LA30_: ;
					{
						NI TM__3rBY6NOHI29c34PPPPzLAdQ_23;
						if (nimAddInt(pos_1, ((NI)1), &TM__3rBY6NOHI29c34PPPPzLAdQ_23)) { raiseOverflow(); goto BeforeRet_;
						};
						pos_1 = (NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_23);
						goto LA13;
					}
LA26_: ;
				}
				goto LA15_;
LA24_: ;
				{
					NI TM__3rBY6NOHI29c34PPPPzLAdQ_24;
					NI TM__3rBY6NOHI29c34PPPPzLAdQ_25;
					if (!((NU8)(c_1) == (NU8)((*self_p0).esc))) goto LA34_;
					if (nimAddInt(pos_1, ((NI)1), &TM__3rBY6NOHI29c34PPPPzLAdQ_24)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_24) < 0 || (NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_24) >= (*self_p0).Sup.buf.len){ raiseIndexError2((NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_24),(*self_p0).Sup.buf.len-1); goto BeforeRet_;
					}
					nimAddCharV1((&(*a_p1)), (*self_p0).Sup.buf.p->data[(NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_24)]);
					if (nimAddInt(pos_1, ((NI)2), &TM__3rBY6NOHI29c34PPPPzLAdQ_25)) { raiseOverflow(); goto BeforeRet_;
					};
					pos_1 = (NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_25);
				}
				goto LA15_;
LA34_: ;
				{
					switch (((NU8)(c_1))) {
					case 13:
					{
						pos_1 = handleCR__pureZlexbase_u91(&self_p0->Sup, pos_1);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						prepareAdd((&(*a_p1)), 1);
appendString((&(*a_p1)), TM__3rBY6NOHI29c34PPPPzLAdQ_27);
					}
					break;
					case 10:
					{
						pos_1 = handleLF__pureZlexbase_u105(&self_p0->Sup, pos_1);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						prepareAdd((&(*a_p1)), 1);
appendString((&(*a_p1)), TM__3rBY6NOHI29c34PPPPzLAdQ_28);
					}
					break;
					default:
					{
						NI TM__3rBY6NOHI29c34PPPPzLAdQ_29;
						nimAddCharV1((&(*a_p1)), c_1);
						if (nimAddInt(pos_1, ((NI)1), &TM__3rBY6NOHI29c34PPPPzLAdQ_29)) { raiseOverflow(); goto BeforeRet_;
						};
						pos_1 = (NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_29);
					}
					break;
					}
				}
LA15_: ;
			}
		} LA13: ;
	}
	goto LA7_;
LA11_: ;
	{
		{
			while (1) {
				NIM_CHAR c_2;
				NI TM__3rBY6NOHI29c34PPPPzLAdQ_30;
				if (pos_1 < 0 || pos_1 >= (*self_p0).Sup.buf.len){ raiseIndexError2(pos_1,(*self_p0).Sup.buf.len-1); goto BeforeRet_;
				}
				c_2 = (*self_p0).Sup.buf.p->data[pos_1];
				{
					if (!((NU8)(c_2) == (NU8)((*self_p0).sep))) goto LA45_;
					goto LA41;
				}
LA45_: ;
				{
					if (!(((NU8)(c_2)) == ((NU8)(13)) || ((NU8)(c_2)) == ((NU8)(10)) || ((NU8)(c_2)) == ((NU8)(0)))) goto LA49_;
					goto LA41;
				}
LA49_: ;
				nimAddCharV1((&(*a_p1)), c_2);
				if (nimAddInt(pos_1, ((NI)1), &TM__3rBY6NOHI29c34PPPPzLAdQ_30)) { raiseOverflow(); goto BeforeRet_;
				};
				pos_1 = (NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_30);
			}
		} LA41: ;
	}
LA7_: ;
	(*self_p0).Sup.bufpos = pos_1;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readRow__pureZparsecsv_u207)(tyObject_CsvParser__Te9b9cfNRUXkZxVA3nziwzGg* self_p0, NI columns_p1) {
	NIM_BOOL result;
	NI col_1;
	NI oldpos_1;
	NI TM__3rBY6NOHI29c34PPPPzLAdQ_39;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	col_1 = ((NI)0);
	oldpos_1 = (*self_p0).Sup.bufpos;
	{
		while (1) {
			if ((*self_p0).Sup.bufpos < 0 || (*self_p0).Sup.bufpos >= (*self_p0).Sup.buf.len){ raiseIndexError2((*self_p0).Sup.bufpos,(*self_p0).Sup.buf.len-1); goto BeforeRet_;
			}
			switch (((NU8)((*self_p0).Sup.buf.p->data[(*self_p0).Sup.bufpos]))) {
			case 13:
			{
				NI T4_;
				T4_ = (NI)0;
				T4_ = handleCR__pureZlexbase_u91(&self_p0->Sup, (*self_p0).Sup.bufpos);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				(*self_p0).Sup.bufpos = T4_;
			}
			break;
			case 10:
			{
				NI T6_;
				T6_ = (NI)0;
				T6_ = handleLF__pureZlexbase_u105(&self_p0->Sup, (*self_p0).Sup.bufpos);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				(*self_p0).Sup.bufpos = T6_;
			}
			break;
			default:
			{
				goto LA1;
			}
			break;
			}
		}
	} LA1: ;
	{
		while (1) {
			NI oldlen_1;
			NI T10_;
			tyObject_CsvParser__Te9b9cfNRUXkZxVA3nziwzGg* T15_;
			NI TM__3rBY6NOHI29c34PPPPzLAdQ_31;
			if ((*self_p0).Sup.bufpos < 0 || (*self_p0).Sup.bufpos >= (*self_p0).Sup.buf.len){ raiseIndexError2((*self_p0).Sup.bufpos,(*self_p0).Sup.buf.len-1); goto BeforeRet_;
			}
			if (!!(((NU8)((*self_p0).Sup.buf.p->data[(*self_p0).Sup.bufpos]) == (NU8)(0)))) goto LA9;
			T10_ = (*self_p0).row.len;
			oldlen_1 = T10_;
			{
				NI TM__3rBY6NOHI29c34PPPPzLAdQ_4;
				NI TM__3rBY6NOHI29c34PPPPzLAdQ_5;
				if (nimAddInt(col_1, ((NI)1), &TM__3rBY6NOHI29c34PPPPzLAdQ_4)) { raiseOverflow(); goto BeforeRet_;
				};
				if (!(oldlen_1 < (NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_4))) goto LA13_;
				if (nimAddInt(col_1, ((NI)1), &TM__3rBY6NOHI29c34PPPPzLAdQ_5)) { raiseOverflow(); goto BeforeRet_;
				};
				if (((NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_5)) < ((NI)0) || ((NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_5)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_5), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
				}
				setLen__system_u5426((&(*self_p0).row), ((NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_5)));
				if (col_1 < 0 || col_1 >= (*self_p0).row.len){ raiseIndexError2(col_1,(*self_p0).row.len-1); goto BeforeRet_;
				}
				eqsink___system_u2729((&(*self_p0).row.p->data[col_1]), TM__3rBY6NOHI29c34PPPPzLAdQ_7);
			}
LA13_: ;
			T15_ = (tyObject_CsvParser__Te9b9cfNRUXkZxVA3nziwzGg*)0;
			T15_ = self_p0;
			if (col_1 < 0 || col_1 >= (*self_p0).row.len){ raiseIndexError2(col_1,(*self_p0).row.len-1); goto BeforeRet_;
			}
			parseField__pureZparsecsv_u155(T15_, (&(*self_p0).row.p->data[col_1]));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (nimAddInt(col_1, ((NI)1), &TM__3rBY6NOHI29c34PPPPzLAdQ_31)) { raiseOverflow(); goto BeforeRet_;
			};
			col_1 = (NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_31);
			{
				NI TM__3rBY6NOHI29c34PPPPzLAdQ_32;
				if ((*self_p0).Sup.bufpos < 0 || (*self_p0).Sup.bufpos >= (*self_p0).Sup.buf.len){ raiseIndexError2((*self_p0).Sup.bufpos,(*self_p0).Sup.buf.len-1); goto BeforeRet_;
				}
				if (!((NU8)((*self_p0).Sup.buf.p->data[(*self_p0).Sup.bufpos]) == (NU8)((*self_p0).sep))) goto LA18_;
				if (nimAddInt((*self_p0).Sup.bufpos, ((NI)1), &TM__3rBY6NOHI29c34PPPPzLAdQ_32)) { raiseOverflow(); goto BeforeRet_;
				};
				(*self_p0).Sup.bufpos = (NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_32);
			}
			goto LA16_;
LA18_: ;
			{
				if ((*self_p0).Sup.bufpos < 0 || (*self_p0).Sup.bufpos >= (*self_p0).Sup.buf.len){ raiseIndexError2((*self_p0).Sup.bufpos,(*self_p0).Sup.buf.len-1); goto BeforeRet_;
				}
				switch (((NU8)((*self_p0).Sup.buf.p->data[(*self_p0).Sup.bufpos]))) {
				case 13:
				case 10:
				{
					{
						while (1) {
							if ((*self_p0).Sup.bufpos < 0 || (*self_p0).Sup.bufpos >= (*self_p0).Sup.buf.len){ raiseIndexError2((*self_p0).Sup.bufpos,(*self_p0).Sup.buf.len-1); goto BeforeRet_;
							}
							switch (((NU8)((*self_p0).Sup.buf.p->data[(*self_p0).Sup.bufpos]))) {
							case 13:
							{
								NI T25_;
								T25_ = (NI)0;
								T25_ = handleCR__pureZlexbase_u91(&self_p0->Sup, (*self_p0).Sup.bufpos);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								(*self_p0).Sup.bufpos = T25_;
							}
							break;
							case 10:
							{
								NI T27_;
								T27_ = (NI)0;
								T27_ = handleLF__pureZlexbase_u105(&self_p0->Sup, (*self_p0).Sup.bufpos);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								(*self_p0).Sup.bufpos = T27_;
							}
							break;
							default:
							{
								goto LA22;
							}
							break;
							}
						}
					} LA22: ;
				}
				break;
				case 0:
				{
				}
				break;
				default:
				{
					NimStringV2 colontmpD_;
					NimStringV2 T32_;
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
					T32_.len = 0; T32_.p = NIM_NIL;
					T32_ = rawNewString(10);
appendChar((&T32_), (*self_p0).sep);
appendString((&T32_), TM__3rBY6NOHI29c34PPPPzLAdQ_33);
					colontmpD_ = T32_;
					error__pureZparsecsv_u84((&(*self_p0)), (*self_p0).Sup.bufpos, colontmpD_);
					if (NIM_UNLIKELY(*nimErr_)) goto LA31_;
					{
						LA31_:;
					}
					{
						if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
					}
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				break;
				}
				goto LA8;
			}
LA16_: ;
		} LA9: ;
	} LA8: ;
	if ((col_1) < ((NI)0) || (col_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(col_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	setLen__system_u5426((&(*self_p0).row), (col_1));
	result = (((NI)0) < col_1);
	{
		NIM_BOOL T37_;
		NIM_BOOL T38_;
		NimStringV2 colontmpD__2;
		NimStringV2 colontmpD__3;
		NimStringV2 colontmpD__4;
		NI TM__3rBY6NOHI29c34PPPPzLAdQ_34;
		NimStringV2 T44_;
		T37_ = (NIM_BOOL)0;
		T38_ = (NIM_BOOL)0;
		T38_ = result;
		if (!(T38_)) goto LA39_;
		T38_ = !((col_1 == columns_p1));
LA39_: ;
		T37_ = T38_;
		if (!(T37_)) goto LA40_;
		T37_ = (((NI)0) < columns_p1);
LA40_: ;
		if (!T37_) goto LA41_;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
		colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
		if (nimAddInt(oldpos_1, ((NI)1), &TM__3rBY6NOHI29c34PPPPzLAdQ_34)) { raiseOverflow(); goto LA43_;
		};
		T44_.len = 0; T44_.p = NIM_NIL;
		colontmpD__2 = dollar___systemZdollars_u14(columns_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA43_;
		colontmpD__3 = dollar___systemZdollars_u14(col_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA43_;
		T44_ = rawNewString(colontmpD__2.len + colontmpD__3.len + 37);
appendString((&T44_), colontmpD__2);
appendString((&T44_), TM__3rBY6NOHI29c34PPPPzLAdQ_36);
appendString((&T44_), colontmpD__3);
appendString((&T44_), TM__3rBY6NOHI29c34PPPPzLAdQ_38);
		colontmpD__4 = T44_;
		error__pureZparsecsv_u84((&(*self_p0)), (NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_34), colontmpD__4);
		if (NIM_UNLIKELY(*nimErr_)) goto LA43_;
		{
			LA43_:;
		}
		{
			if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
			if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
			if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA41_: ;
	if (nimAddInt((*self_p0).currRow, ((NI)1), &TM__3rBY6NOHI29c34PPPPzLAdQ_39)) { raiseOverflow(); goto BeforeRet_;
	};
	(*self_p0).currRow = (NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_39);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, readHeaderRow__pureZparsecsv_u242)(tyObject_CsvParser__Te9b9cfNRUXkZxVA3nziwzGg* self_p0) {
	NIM_BOOL present_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	present_1 = readRow__pureZparsecsv_u207(self_p0, ((NI)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!present_1) goto LA3_;
		eqcopy___system_u5525((&(*self_p0).headers), (*self_p0).row);
	}
LA3_: ;
	}BeforeRet_: ;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
{	result = NIM_FALSE;
	alen_1 = a_p0.len;
	blen_1 = b_p1.len;
	{
		if (!(alen_1 == blen_1)) goto LA3_;
		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		result = equalMem__system_u1763(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, find__pureZparsecsv_u249)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ a_p0, NimStringV2 item_p1) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = ((NI)0);
	{
		NimStringV2* i_1;
		NI i_2;
		NI L_1;
		NI T2_;
		i_1 = (NimStringV2*)0;
		i_2 = ((NI)0);
		T2_ = a_p0.len;
		L_1 = T2_;
		{
			while (1) {
				NI TM__3rBY6NOHI29c34PPPPzLAdQ_40;
				if (!(i_2 < L_1)) goto LA4;
				if (i_2 < 0 || i_2 >= a_p0.len){ raiseIndexError2(i_2,a_p0.len-1); goto BeforeRet_;
				}
				i_1 = (&a_p0.p->data[i_2]);
				{
					if (!eqStrings((*i_1), item_p1)) goto LA7_;
					goto BeforeRet_;
				}
LA7_: ;
				if (nimAddInt(result, ((NI)1), &TM__3rBY6NOHI29c34PPPPzLAdQ_40)) { raiseOverflow(); goto BeforeRet_;
				};
				result = (NI)(TM__3rBY6NOHI29c34PPPPzLAdQ_40);
				i_2 += ((NI)1);
				{
					NI T11_;
					T11_ = a_p0.len;
					if (!!((T11_ == L_1))) goto LA12_;
					failedAssertImpl__stdZassertions_u95(TM__3rBY6NOHI29c34PPPPzLAdQ_42);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA12_: ;
			} LA4: ;
		}
	}
	result = ((NI)-1);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2*, rowEntry__pureZparsecsv_u245)(tyObject_CsvParser__Te9b9cfNRUXkZxVA3nziwzGg* self_p0, NimStringV2 entry_p1) {
	NimStringV2* result;
	NI index_1;
{	result = (NimStringV2*)0;
	index_1 = find__pureZparsecsv_u249((*self_p0).headers, entry_p1);
	{
		if (!(((NI)0) <= index_1)) goto LA3_;
		if (index_1 < 0 || index_1 >= (*self_p0).row.len){ raiseIndexError2(index_1,(*self_p0).row.len-1); goto BeforeRet_;
		}
		result = (&(*self_p0).row.p->data[index_1]);
	}
	goto LA1_;
LA3_: ;
	{
		tyObject_KeyError__lMqmQfnmk57agJesML1viQ* T6_;
		NimStringV2 T7_;
		T6_ = NIM_NIL;
		T6_ = (tyObject_KeyError__lMqmQfnmk57agJesML1viQ*) nimNewObj(sizeof(tyObject_KeyError__lMqmQfnmk57agJesML1viQ), NIM_ALIGNOF(tyObject_KeyError__lMqmQfnmk57agJesML1viQ));
		(*T6_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__lMqmQfnmk57agJesML1viQ_);
		(*T6_).Sup.Sup.Sup.name = "KeyError";
		T7_.len = 0; T7_.p = NIM_NIL;
		T7_ = rawNewString(entry_p1.len + 22);
appendString((&T7_), TM__3rBY6NOHI29c34PPPPzLAdQ_44);
appendString((&T7_), entry_p1);
appendString((&T7_), TM__3rBY6NOHI29c34PPPPzLAdQ_46);
		(*T6_).Sup.Sup.Sup.message = T7_;
		(*T6_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T6_, "KeyError", "rowEntry", "parsecsv.nim", 349);
goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
