/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -IC:\Bar\nim\lib -Ic:\UserProgram\nim\pipet\src -o c:\UserProgram\nim\pipet\releasecache\@prandom.nim.c.o c:\UserProgram\nim\pipet\releasecache\@prandom.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <windows.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_Rand__vDsXjV8SzLjmhP8xucyslg tyObject_Rand__vDsXjV8SzLjmhP8xucyslg;
struct tyObject_Rand__vDsXjV8SzLjmhP8xucyslg {
	NU64 a0;
	NU64 a1;
};
static N_INLINE(void, initLock__coreZlocks_u7)(CRITICAL_SECTION* lock_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NI, rand__pureZrandom_u114)(tyObject_Rand__vDsXjV8SzLjmhP8xucyslg* r_p0, NI max_p1);
N_LIB_PRIVATE N_NIMCALL(NU64, rand__pureZrandom_u118)(tyObject_Rand__vDsXjV8SzLjmhP8xucyslg* r_p0, NU64 max_p1);
N_LIB_PRIVATE N_NIMCALL(NU64, next__pureZrandom_u36)(tyObject_Rand__vDsXjV8SzLjmhP8xucyslg* r_p0);
N_LIB_PRIVATE N_NIMCALL(NU64, rotl__pureZrandom_u24)(NU64 x_p0, NU64 k_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE NIM_CONST tyObject_Rand__vDsXjV8SzLjmhP8xucyslg DefaultRandSeed__pureZrandom_u14 = {7616934476015405061ULL, 15122295919272093642ULL}
;
N_LIB_PRIVATE tyObject_Rand__vDsXjV8SzLjmhP8xucyslg state__pureZrandom_u15;
N_LIB_PRIVATE CRITICAL_SECTION baseSeedLock__pureZrandom_u313;
N_LIB_PRIVATE tyObject_Rand__vDsXjV8SzLjmhP8xucyslg baseState__pureZrandom_u314;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4167;
static N_INLINE(void, initLock__coreZlocks_u7)(CRITICAL_SECTION* lock_p0) {
	InitializeCriticalSection(lock_p0);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4167);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU64, rotl__pureZrandom_u24)(NU64 x_p0, NU64 k_p1) {
	NU64 result;
	result = (NU64)((NU64)((NU64)(x_p0) << (NU64)(k_p1 & (64 - 1))) | (NU64)((NU64)(x_p0) >> (NU64)((NU64)((NU64)(64ULL) - (NU64)(k_p1)) & (64 - 1))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU64, next__pureZrandom_u36)(tyObject_Rand__vDsXjV8SzLjmhP8xucyslg* r_p0) {
	NU64 result;
	NU64 s0_1;
	NU64 s1_1;
	NU64 T1_;
	NU64 T2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	s0_1 = (*r_p0).a0;
	s1_1 = (*r_p0).a1;
	result = (NU64)((NU64)(s0_1) + (NU64)(s1_1));
	s1_1 = (NU64)(s1_1 ^ s0_1);
	T1_ = (NU64)0;
	T1_ = rotl__pureZrandom_u24(s0_1, 55ULL);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*r_p0).a0 = (NU64)((NU64)(T1_ ^ s1_1) ^ (NU64)((NU64)(s1_1) << (NU64)(((NI)14) & (64 - 1))));
	T2_ = (NU64)0;
	T2_ = rotl__pureZrandom_u24(s1_1, 36ULL);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*r_p0).a1 = T2_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU64, rand__pureZrandom_u118)(tyObject_Rand__vDsXjV8SzLjmhP8xucyslg* r_p0, NU64 max_p1) {
	NU64 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU64)0;
	{
		if (!(max_p1 == 0ULL)) goto LA3_;
		goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		NU64 max_2;
		NI iters_1;
		max_2 = max_p1;
		{
			if (!(max_2 == 18446744073709551615ULL)) goto LA8_;
			result = next__pureZrandom_u36(r_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			goto BeforeRet_;
		}
LA8_: ;
		iters_1 = ((NI)0);
		{
			while (1) {
				NU64 x_1;
				x_1 = next__pureZrandom_u36(r_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				{
					NIM_BOOL T14_;
					T14_ = (NIM_BOOL)0;
					T14_ = ((NU64)(x_1) <= (NU64)((NU64)((NU64)(18446744073709551615ULL) - (NU64)((NU64)((NU64)(18446744073709551615ULL) % (NU64)(max_2))))));
					if (T14_) goto LA15_;
					T14_ = (((NI)20) < iters_1);
LA15_: ;
					if (!T14_) goto LA16_;
					result = (NU64)((NU64)(x_1) % (NU64)((NU64)((NU64)(max_2) + (NU64)(1ULL))));
					goto BeforeRet_;
				}
				goto LA12_;
LA16_: ;
				{
					NI TM__AIKkgex03Z1j45JceakCTA_2;
					if (nimAddInt(iters_1, ((NI)1), &TM__AIKkgex03Z1j45JceakCTA_2)) { raiseOverflow(); goto BeforeRet_;
					};
					iters_1 = (NI)(TM__AIKkgex03Z1j45JceakCTA_2);
				}
LA12_: ;
			}
		}
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, rand__pureZrandom_u114)(tyObject_Rand__vDsXjV8SzLjmhP8xucyslg* r_p0, NI max_p1) {
	NI result;
	NU64 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	T1_ = (NU64)0;
	T1_ = rand__pureZrandom_u118(r_p0, ((NU64) (max_p1)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((NI) (T1_));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, rand__pureZrandom_u143)(NI max_p0) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	if ((max_p0) < ((NI)0) || (max_p0) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(max_p0, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = rand__pureZrandom_u114((&state__pureZrandom_u15), (max_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atprandomdotnim_Init000)(void) {
{
NIM_BOOL* nimErr_;
nimErr_ = nimErrorFlag();
	state__pureZrandom_u15 = DefaultRandSeed__pureZrandom_u14;
	initLock__coreZlocks_u7((&baseSeedLock__pureZrandom_u313));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	BeforeRet_: ;
	nimTestErrorFlag();
}
}

