/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -IC:\Bar\nim\lib -Ic:\UserProgram\nim\pipet\src -o c:\UserProgram\nim\pipet\releasecache\@psets.nim.c.o c:\UserProgram\nim\pipet\releasecache\@psets.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tySequence__8Np6tlClE5az1CyqZdN19bQ tySequence__8Np6tlClE5az1CyqZdN19bQ;
typedef struct tySequence__8Np6tlClE5az1CyqZdN19bQ_Content tySequence__8Np6tlClE5az1CyqZdN19bQ_Content;
typedef struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyObject_HashSet__aUXywX6kFlGK2z1H73Lmpg tyObject_HashSet__aUXywX6kFlGK2z1H73Lmpg;
struct tySequence__8Np6tlClE5az1CyqZdN19bQ {
  NI len; tySequence__8Np6tlClE5az1CyqZdN19bQ_Content* p;
};
struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ {
	NI Field0;
	NI Field1;
};
struct tyObject_HashSet__aUXywX6kFlGK2z1H73Lmpg {
	tySequence__8Np6tlClE5az1CyqZdN19bQ data;
	NI counter;
};
struct tySequence__8Np6tlClE5az1CyqZdN19bQ_Content { NI cap; tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, init__pureZnet_u1566)(tyObject_HashSet__aUXywX6kFlGK2z1H73Lmpg* s_p0, NI initialSize_p1);
static N_INLINE(NI, slotsNeeded__pureZcollectionsZsets_u50)(NI count_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_u249)(NI x_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, newSeq__pureZnet_u1192)(tySequence__8Np6tlClE5az1CyqZdN19bQ* s_p0, NI len_p1);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4167;
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZnet_u324)(tySequence__8Np6tlClE5az1CyqZdN19bQ dest_p0) {
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ));
}
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4167);
	return result;
}
static N_INLINE(NI, slotsNeeded__pureZcollectionsZsets_u50)(NI count_p0) {
	NI result;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_2;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_3;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	if (nimAddInt((NI)((count_p0) / (((NI)2))), count_p0, &TM__0JXiWyhP5OCO8jWMA6sb1w_2)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_2), ((NI)4), &TM__0JXiWyhP5OCO8jWMA6sb1w_3)) { raiseOverflow(); goto BeforeRet_;
	};
	result = nextPowerOfTwo__pureZmath_u249((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_3));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, init__pureZnet_u1566)(tyObject_HashSet__aUXywX6kFlGK2z1H73Lmpg* s_p0, NI initialSize_p1) {
	NI correctSizeX60gensym93__1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	if ((initialSize_p1) < ((NI)0) || (initialSize_p1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(initialSize_p1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	correctSizeX60gensym93__1 = slotsNeeded__pureZcollectionsZsets_u50((initialSize_p1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*s_p0).counter = ((NI)0);
	if ((correctSizeX60gensym93__1) < ((NI)0) || (correctSizeX60gensym93__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym93__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	newSeq__pureZnet_u1192((&(*s_p0).data), (correctSizeX60gensym93__1));
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_HashSet__aUXywX6kFlGK2z1H73Lmpg, initHashSet__pureZnet_u1552)(NI initialSize_p0) {
	tyObject_HashSet__aUXywX6kFlGK2z1H73Lmpg result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_HashSet__aUXywX6kFlGK2z1H73Lmpg));
	init__pureZnet_u1566((&result), initialSize_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
