/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -IC:\Bar\nim\lib -Ic:\UserProgram\nim\pipet\src -o c:\UserProgram\nim\pipet\releasecache\@pstd@sprivate@sosdirs.nim.c.o c:\UserProgram\nim\pipet\releasecache\@pstd@sprivate@sosdirs.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_WideCStringObj__bFQqwXHGjLs9ce89aYpQn9brg tyObject_WideCStringObj__bFQqwXHGjLs9ce89aYpQn9brg;
typedef struct tyObject_IOError__ALOnqndH9aDQS9csnW9c9a9bSUg tyObject_IOError__ALOnqndH9aDQS9csnW9c9a9bSUg;
typedef struct tyObject_CatchableError__5X2CqDk7Ldk7h9a22Zsg5kg tyObject_CatchableError__5X2CqDk7Ldk7h9a22Zsg5kg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__xIN54dE1a4ZyAUnTpAuU2g tySequence__xIN54dE1a4ZyAUnTpAuU2g;
typedef struct tySequence__xIN54dE1a4ZyAUnTpAuU2g_Content tySequence__xIN54dE1a4ZyAUnTpAuU2g_Content;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
typedef struct tyObject_StackTraceEntry__2ELMRvKL5HlwpyV9cRIuTmw tyObject_StackTraceEntry__2ELMRvKL5HlwpyV9cRIuTmw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_WideCStringObj__bFQqwXHGjLs9ce89aYpQn9brg {
	NI bytes;
	NI16* data;
};
typedef N_STDCALL_PTR(NI32, tyProc__uBkkHOkdpyfFusi9cbg9cHww) (NI16* pathName_p0, void* security_p1);
typedef NI16 tyUncheckedArray__Tyd4y3haUOOHTj71TPIRag[1];
typedef N_STDCALL_PTR(NI32, tyProc__9bXer9a4ps9aSGctILcxWReVw) (void);
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__xIN54dE1a4ZyAUnTpAuU2g {
  NI len; tySequence__xIN54dE1a4ZyAUnTpAuU2g_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__xIN54dE1a4ZyAUnTpAuU2g trace;
	Exception* up;
};
struct tyObject_CatchableError__5X2CqDk7Ldk7h9a22Zsg5kg {
	Exception Sup;
};
struct tyObject_IOError__ALOnqndH9aDQS9csnW9c9a9bSUg {
	tyObject_CatchableError__5X2CqDk7Ldk7h9a22Zsg5kg Sup;
};
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
	NimStringV2 Field0;
	NimStringV2 Field1;
};
struct tyObject_StackTraceEntry__2ELMRvKL5HlwpyV9cRIuTmw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__xIN54dE1a4ZyAUnTpAuU2g_Content { NI cap; tyObject_StackTraceEntry__2ELMRvKL5HlwpyV9cRIuTmw data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosisAbsolute)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2723)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosexistsOrCreateDir)(NimStringV2 dir_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, rawCreateDir__stdZprivateZosdirs_u449)(NimStringV2 dir_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NI16*, toWideCString__stdZwidestrs_u49)(tyObject_WideCStringObj__bFQqwXHGjLs9ce89aYpQn9brg x_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__bFQqwXHGjLs9ce89aYpQn9brg, newWideCString__stdZwidestrs_u325)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__stdZoserrors_u122)(NI32 errorCode_p0, NimStringV2 additionalInfo_p1);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__stdZoserrors_u125)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZwidestrs_u7)(tyObject_WideCStringObj__bFQqwXHGjLs9ce89aYpQn9brg a_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosdirExists)(NimStringV2 dir_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosisRootDir)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2729)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosparentDir)(NimStringV2 path_p0);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, splitDrive__stdZprivateZntpath_u2)(NimStringV2 p_p0, tyTuple__UV3llMMYFckfui8YMBuUZA* Result);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u9113)(NimStringV2 s_p0, NI first_p1, NI last_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZprivateZntpath_u119)(tyTuple__UV3llMMYFckfui8YMBuUZA* dest_p0);
extern TNimTypeV2 NTIv2__ALOnqndH9aDQS9csnW9c9a9bSUg_;
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__UhMx4BhJKblm8VrPrbmAGA_2 = { 18 | NIM_STRLIT_FLAG, "Failed to create \'" };
static const NimStringV2 TM__UhMx4BhJKblm8VrPrbmAGA_3 = {18, (NimStrPayload*)&TM__UhMx4BhJKblm8VrPrbmAGA_2};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__UhMx4BhJKblm8VrPrbmAGA_4 = { 1 | NIM_STRLIT_FLAG, "\'" };
static const NimStringV2 TM__UhMx4BhJKblm8VrPrbmAGA_5 = {1, (NimStrPayload*)&TM__UhMx4BhJKblm8VrPrbmAGA_4};
extern tyProc__uBkkHOkdpyfFusi9cbg9cHww Dl_1912602811_;
extern tyProc__9bXer9a4ps9aSGctILcxWReVw Dl_1912602793_;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4167;
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NI16*, toWideCString__stdZwidestrs_u49)(tyObject_WideCStringObj__bFQqwXHGjLs9ce89aYpQn9brg x_p0) {
	NI16* result;
	result = x_p0.data;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4167);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, rawCreateDir__stdZprivateZosdirs_u449)(NimStringV2 dir_p0) {
	NIM_BOOL result;
	tyObject_WideCStringObj__bFQqwXHGjLs9ce89aYpQn9brg colontmpD_;
	NI32 res_1;
	NI16* T2_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_WideCStringObj__bFQqwXHGjLs9ce89aYpQn9brg));
	colontmpD_ = newWideCString__stdZwidestrs_u325(dir_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_ = (NI16*)0;
	T2_ = toWideCString__stdZwidestrs_u49(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	res_1 = Dl_1912602811_(T2_, NIM_NIL);
	{
		if (!!((res_1 == ((NI32)0)))) goto LA5_;
		result = NIM_TRUE;
	}
	goto LA3_;
LA5_: ;
	{
		NI32 T8_;
		T8_ = (NI32)0;
		T8_ = Dl_1912602793_();
		if (!(T8_ == ((NI32)183))) goto LA9_;
		result = NIM_FALSE;
	}
	goto LA3_;
LA9_: ;
	{
		NI32 T12_;
		T12_ = (NI32)0;
		T12_ = osLastError__stdZoserrors_u125();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		raiseOSError__stdZoserrors_u122(T12_, dir_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA3_: ;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___stdZwidestrs_u7(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosexistsOrCreateDir)(NimStringV2 dir_p0) {
	NIM_BOOL result;
	NIM_BOOL T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	T1_ = (NIM_BOOL)0;
	T1_ = rawCreateDir__stdZprivateZosdirs_u449(dir_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = !(T1_);
	{
		if (!result) goto LA4_;
		{
			NIM_BOOL T8_;
			tyObject_IOError__ALOnqndH9aDQS9csnW9c9a9bSUg* T11_;
			NimStringV2 T12_;
			T8_ = (NIM_BOOL)0;
			T8_ = nosdirExists(dir_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T8_)) goto LA9_;
			T11_ = NIM_NIL;
			T11_ = (tyObject_IOError__ALOnqndH9aDQS9csnW9c9a9bSUg*) nimNewObj(sizeof(tyObject_IOError__ALOnqndH9aDQS9csnW9c9a9bSUg), NIM_ALIGNOF(tyObject_IOError__ALOnqndH9aDQS9csnW9c9a9bSUg));
			(*T11_).Sup.Sup.Sup.m_type = (&NTIv2__ALOnqndH9aDQS9csnW9c9a9bSUg_);
			(*T11_).Sup.Sup.name = "IOError";
			T12_.len = 0; T12_.p = NIM_NIL;
			T12_ = rawNewString(dir_p0.len + 19);
appendString((&T12_), TM__UhMx4BhJKblm8VrPrbmAGA_3);
appendString((&T12_), dir_p0);
appendString((&T12_), TM__UhMx4BhJKblm8VrPrbmAGA_5);
			(*T11_).Sup.Sup.message = T12_;
			(*T11_).Sup.Sup.parent = ((Exception*) NIM_NIL);
			raiseExceptionEx((Exception*)T11_, "IOError", "existsOrCreateDir", "osdirs.nim", 416);
goto BeforeRet_;
		}
LA9_: ;
	}
LA4_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
}
N_LIB_PRIVATE N_NIMCALL(void, noscreateDir)(NimStringV2 dir_p0) {
	NIM_BOOL omitNext_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!(dir_p0.len == 0)) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	omitNext_1 = nosisAbsolute(dir_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NimStringV2 p_1;
		p_1.len = 0; p_1.p = NIM_NIL;
		{
			NimStringV2 current_1;
			if (!NIM_FALSE) goto LA9_;
			current_1.len = 0; current_1.p = NIM_NIL;
			eqcopy___system_u2723((&current_1), dir_p0);
			{
				if (!NIM_TRUE) goto LA14_;
				eqcopy___system_u2723((&p_1), dir_p0);
				{
					if (!omitNext_1) goto LA18_;
					omitNext_1 = NIM_FALSE;
				}
				goto LA16_;
LA18_: ;
				{
					NIM_BOOL T21_;
					T21_ = (NIM_BOOL)0;
					T21_ = nosexistsOrCreateDir(p_1);
					if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
					(void)(T21_);
				}
LA16_: ;
			}
LA14_: ;
			{
				while (1) {
					NimStringV2 T29_;
					{
						NIM_BOOL T26_;
						T26_ = (NIM_BOOL)0;
						T26_ = nosisRootDir(current_1);
						if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
						if (!T26_) goto LA27_;
						goto LA22;
					}
LA27_: ;
					T29_.len = 0; T29_.p = NIM_NIL;
					T29_ = nosparentDir(current_1);
					if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T29_); goto LA11_;}
					eqsink___system_u2729((&current_1), T29_);
					eqcopy___system_u2723((&p_1), current_1);
					{
						if (!omitNext_1) goto LA32_;
						omitNext_1 = NIM_FALSE;
					}
					goto LA30_;
LA32_: ;
					{
						NIM_BOOL T35_;
						T35_ = (NIM_BOOL)0;
						T35_ = nosexistsOrCreateDir(p_1);
						if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
						(void)(T35_);
					}
LA30_: ;
				}
			} LA22: ;
			{
				LA11_:;
			}
			{
				if (current_1.p && !(current_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(current_1.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		}
		goto LA7_;
LA9_: ;
		{
			tyTuple__UV3llMMYFckfui8YMBuUZA colontmpD_;
			NI start_1;
			nimZeroMem((void*)(&colontmpD_), sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA));
			splitDrive__stdZprivateZntpath_u2(dir_p0, (&colontmpD_));
			if (NIM_UNLIKELY(*nimErr_)) goto LA39_;
			start_1 = colontmpD_.Field0.len;
			{
				NI i_1;
				NI colontmp_;
				NI TM__UhMx4BhJKblm8VrPrbmAGA_6;
				NI res_1;
				i_1 = (NI)0;
				colontmp_ = (NI)0;
				if (nimSubInt(dir_p0.len, ((NI)2), &TM__UhMx4BhJKblm8VrPrbmAGA_6)) { raiseOverflow(); goto LA39_;
				};
				colontmp_ = (NI)(TM__UhMx4BhJKblm8VrPrbmAGA_6);
				res_1 = start_1;
				{
					while (1) {
						NI TM__UhMx4BhJKblm8VrPrbmAGA_8;
						if (!(res_1 <= colontmp_)) goto LA42;
						i_1 = ((NI) (res_1));
						{
							NIM_BOOL T45_;
							NIM_BOOL T47_;
							NI TM__UhMx4BhJKblm8VrPrbmAGA_7;
							NimStringV2 T51_;
							T45_ = (NIM_BOOL)0;
							if (i_1 < 0 || i_1 >= dir_p0.len){ raiseIndexError2(i_1,dir_p0.len-1); goto LA39_;
							}
							T45_ = (((NU8)(dir_p0.p->data[i_1])) == ((NU8)(92)) || ((NU8)(dir_p0.p->data[i_1])) == ((NU8)(47)));
							if (!(T45_)) goto LA46_;
							T47_ = (NIM_BOOL)0;
							T47_ = (i_1 == ((NI)0));
							if (T47_) goto LA48_;
							if (nimSubInt(i_1, ((NI)1), &TM__UhMx4BhJKblm8VrPrbmAGA_7)) { raiseOverflow(); goto LA39_;
							};
							if ((NI)(TM__UhMx4BhJKblm8VrPrbmAGA_7) < 0 || (NI)(TM__UhMx4BhJKblm8VrPrbmAGA_7) >= dir_p0.len){ raiseIndexError2((NI)(TM__UhMx4BhJKblm8VrPrbmAGA_7),dir_p0.len-1); goto LA39_;
							}
							T47_ = !((((NU8)(dir_p0.p->data[(NI)(TM__UhMx4BhJKblm8VrPrbmAGA_7)])) == ((NU8)(92)) || ((NU8)(dir_p0.p->data[(NI)(TM__UhMx4BhJKblm8VrPrbmAGA_7)])) == ((NU8)(47))));
LA48_: ;
							T45_ = T47_;
LA46_: ;
							if (!T45_) goto LA49_;
							T51_.len = 0; T51_.p = NIM_NIL;
							T51_ = substr__system_u9113(dir_p0, ((NI)0), i_1);
							eqsink___system_u2729((&p_1), T51_);
							{
								if (!omitNext_1) goto LA54_;
								omitNext_1 = NIM_FALSE;
							}
							goto LA52_;
LA54_: ;
							{
								NIM_BOOL T57_;
								T57_ = (NIM_BOOL)0;
								T57_ = nosexistsOrCreateDir(p_1);
								if (NIM_UNLIKELY(*nimErr_)) goto LA39_;
								(void)(T57_);
							}
LA52_: ;
						}
LA49_: ;
						if (nimAddInt(res_1, ((NI)1), &TM__UhMx4BhJKblm8VrPrbmAGA_8)) { raiseOverflow(); goto LA39_;
						};
						res_1 = (NI)(TM__UhMx4BhJKblm8VrPrbmAGA_8);
					} LA42: ;
				}
			}
			{
				if (!NIM_TRUE) goto LA60_;
				eqcopy___system_u2723((&p_1), dir_p0);
				{
					if (!omitNext_1) goto LA64_;
					omitNext_1 = NIM_FALSE;
				}
				goto LA62_;
LA64_: ;
				{
					NIM_BOOL T67_;
					T67_ = (NIM_BOOL)0;
					T67_ = nosexistsOrCreateDir(p_1);
					if (NIM_UNLIKELY(*nimErr_)) goto LA39_;
					(void)(T67_);
				}
LA62_: ;
			}
LA60_: ;
			{
				LA39_:;
			}
			{
				eqdestroy___stdZprivateZntpath_u119((&colontmpD_));
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		}
LA7_: ;
		{
			LA6_:;
		}
		{
			if (p_1.p && !(p_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(p_1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	}BeforeRet_: ;
}
