/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -IC:\Bar\nim\lib -Ic:\UserProgram\nim\pipet\src -o c:\UserProgram\nim\pipet\releasecache\@pstrutils.nim.c.o c:\UserProgram\nim\pipet\releasecache\@pstrutils.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw;
typedef struct tyObject_CatchableError__5X2CqDk7Ldk7h9a22Zsg5kg tyObject_CatchableError__5X2CqDk7Ldk7h9a22Zsg5kg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__xIN54dE1a4ZyAUnTpAuU2g tySequence__xIN54dE1a4ZyAUnTpAuU2g;
typedef struct tySequence__xIN54dE1a4ZyAUnTpAuU2g_Content tySequence__xIN54dE1a4ZyAUnTpAuU2g_Content;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_StackTraceEntry__2ELMRvKL5HlwpyV9cRIuTmw tyObject_StackTraceEntry__2ELMRvKL5HlwpyV9cRIuTmw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__xIN54dE1a4ZyAUnTpAuU2g {
  NI len; tySequence__xIN54dE1a4ZyAUnTpAuU2g_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__xIN54dE1a4ZyAUnTpAuU2g trace;
	Exception* up;
};
struct tyObject_CatchableError__5X2CqDk7Ldk7h9a22Zsg5kg {
	Exception Sup;
};
struct tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw {
	tyObject_CatchableError__5X2CqDk7Ldk7h9a22Zsg5kg Sup;
};
typedef NI tyArray__9cc9aPiDa8VaWjVcFLabEDZQ[256];
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
typedef NU8 tyEnum_FloatFormatMode__NktTD9agsSu9bXX0rEiwGseg;
typedef NIM_CHAR tyArray__Dz6OE1kpzz8bnx9batFy1Cw[6];
typedef NIM_CHAR tyArray__WALV5e0ysjOIjCclEgOBNg[2501];
typedef NIM_CHAR tyArray__M7uRMNNATXhAugkFnFh7iQ[3];
struct tyObject_StackTraceEntry__2ELMRvKL5HlwpyV9cRIuTmw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__xIN54dE1a4ZyAUnTpAuU2g_Content { NI cap; tyObject_StackTraceEntry__2ELMRvKL5HlwpyV9cRIuTmw data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2729)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, appendChar)(NimStringV2* dest_p0, NIM_CHAR c_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHexImpl__pureZstrutils_u783)(NU64 x_p0, NI len_p1, NIM_BOOL handleNegative_p2);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2462)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorNoArgs)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToUpperAsciiChar)(NIM_CHAR c_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u9113)(NimStringV2 s_p0, NI first_p1, NI last_p2);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHex__pureZstrutils_u2174)(NI x_p0, NI len_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(NI, parseBiggestInt__pureZparseutils_u915)(NimStringV2 s_p0, NI64* number_p1, NI start_p2);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(NI, parseFloat__pureZparseutils_u945)(NimStringV2 s_p0, NF* number_p1, NI start_p2);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2723)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u9126)(NimStringV2 s_p0, NI first_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, nsuInitNewSkipTable)(NimStringV2 sub_p0, tyArray__9cc9aPiDa8VaWjVcFLabEDZQ Result);
N_LIB_PRIVATE N_NIMCALL(void, nsuInitSkipTable)(NI* a_p0, NimStringV2 sub_p1);
N_LIB_PRIVATE N_NIMCALL(void, fill__pureZstrutils_u1634)(NI* a_p0, NI a_p0Len_0, NI value_p1);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStrA)(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ a_p0, NimStringV2 s_p1, NimStringV2 sub_p2, NI start_p3, NI last_p4);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindCharSet)(NimStringV2 s_p0, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p1, NI start_p2, NI last_p3);
N_LIB_PRIVATE N_NIMCALL(void, nsuAddf)(NimStringV2* s_p0, NimStringV2 formatstr_p1, NimStringV2* a_p2, NI a_p2Len_0);
N_LIB_PRIVATE N_NOINLINE(void, invalidFormatString__pureZstrutils_u2654)(NimStringV2 formatstr_p0);
N_LIB_PRIVATE N_NIMCALL(NI, findNormalized__pureZstrutils_u2641)(NimStringV2 x_p0, NimStringV2* inArray_p1, NI inArray_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_CHAR, toLowerAscii__stdZprivateZstrimpl_u1)(NIM_CHAR c_p0);
N_LIB_PRIVATE N_NIMCALL(NI, parseInt__pureZparseutils_u920)(NimStringV2 s_p0, NI* number_p1, NI start_p2);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u70)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2720)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToLowerAsciiChar)(NIM_CHAR c_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NI start_p2, NI last_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuformatBiggestFloat)(NF f_p0, tyEnum_FloatFormatMode__NktTD9agsSu9bXX0rEiwGseg format_p1, NI precision_p2, NIM_CHAR decimalSep_p3);
static N_INLINE(NIM_CHAR*, X5BX5D___system_u8588)(NimStringV2* s_p0, NI i_p1);
static N_INLINE(void, X5BX5Deq___system_u8603)(NimStringV2* s_p0, NI i_p1, NIM_CHAR x_p2);
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_7 = { 16 | NIM_STRLIT_FLAG, "0123456789ABCDEF" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_8 = {16, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_7};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_21 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_22 = {0, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_21};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_26 = { 2 | NIM_STRLIT_FLAG, "\\x" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_27 = {2, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_26};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_28 = { 2 | NIM_STRLIT_FLAG, "\\\\" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_29 = {2, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_28};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_30 = { 2 | NIM_STRLIT_FLAG, "\\\'" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_31 = {2, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_30};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_32 = { 2 | NIM_STRLIT_FLAG, "\\\"" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_33 = {2, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_32};
static const struct {
  NI cap; NIM_CHAR data[93+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_34 = { 93 | NIM_STRLIT_FLAG, "iterators.nim(272, 11) `len(a) == L` the length of the string changed while iterating over it" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_35 = {93, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_34};
extern TNimTypeV2 NTIv2__jLnwc41Xd9aFjddYhlZ15cw_;
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_36 = { 17 | NIM_STRLIT_FLAG, "invalid integer: " };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_37 = {17, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_36};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_38 = { 15 | NIM_STRLIT_FLAG, "invalid float: " };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_39 = {15, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_38};
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_45 = {0, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_21};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_64 = { 23 | NIM_STRLIT_FLAG, "invalid format string: " };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_65 = {23, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_64};
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_97 = {17, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_36};
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_110 = {16, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_7};
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_112 = {16, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_7};
static const struct {
  NI cap; NIM_CHAR data[93+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_113 = { 93 | NIM_STRLIT_FLAG, "iterators.nim(206, 11) `len(a) == L` the length of the string changed while iterating over it" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_114 = {93, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_113};
N_LIB_PRIVATE NIM_CONST tyArray__M7uRMNNATXhAugkFnFh7iQ floatFormatToChar__pureZstrutils_u2252 = {103,
102,
101}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4167;
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI last_2;
	NI length_1;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_2;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_3;
{	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	result = ((NI)-1);
	{
		if (!(last_p3 < ((NI)0))) goto LA3_;
		colontmpD_ = (s_p0.len-1);
		last_2 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = last_p3;
		last_2 = colontmpD__2;
	}
LA1_: ;
	if (nimSubInt(last_2, start_p2, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_2)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_2), ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_3)) { raiseOverflow(); goto BeforeRet_;
	};
	length_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_3);
	{
		void* found_1;
		if (!(((NI)0) < length_1)) goto LA8_;
		if (start_p2 < 0 || start_p2 >= s_p0.len){ raiseIndexError2(start_p2,s_p0.len-1); goto BeforeRet_;
		}
		found_1 = memchr(((void*) ((&s_p0.p->data[start_p2]))), ((int) (((NU8)(sub_p1)))), ((size_t) (length_1)));
		{
			if (!!((found_1 == 0))) goto LA12_;
			result = minuspercent___system_u813(((NI) (ptrdiff_t) (found_1)), ((NI) (nimToCStringConv(s_p0))));
			goto BeforeRet_;
		}
LA12_: ;
	}
LA8_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, appendChar)(NimStringV2* dest_p0, NIM_CHAR c_p1) {
	(*(*dest_p0).p).data[(*dest_p0).len] = c_p1;
	(*dest_p0).len += ((NI)1);
	(*(*dest_p0).p).data[(*dest_p0).len] = 0;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4167);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuIntToStr)(NI x_p0, NI minchars_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	if (x_p0 == (IL64(-9223372036854775807) - IL64(1))){ raiseOverflow(); goto BeforeRet_;
	}
	result = dollar___systemZdollars_u14((x_p0 > 0? (x_p0) : -(x_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI i_1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_4;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		if (nimSubInt(minchars_p1, result.len, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_4)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_4);
		res_1 = ((NI)1);
		{
			while (1) {
				NimStringV2 T4_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_5;
				if (!(res_1 <= colontmp_)) goto LA3;
				i_1 = ((NI) (res_1));
				T4_.len = 0; T4_.p = NIM_NIL;
				T4_ = rawNewString(result.len + 1);
appendChar((&T4_), 48);
appendString((&T4_), result);
				eqsink___system_u2729((&result), T4_);
				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_5)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_5);
			} LA3: ;
		}
	}
	{
		NimStringV2 T9_;
		if (!(x_p0 < ((NI)0))) goto LA7_;
		T9_.len = 0; T9_.p = NIM_NIL;
		T9_ = rawNewString(result.len + 1);
appendChar((&T9_), 45);
appendString((&T9_), result);
		eqsink___system_u2729((&result), T9_);
	}
LA7_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2462(s_p0);
	}
LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHexImpl__pureZstrutils_u783)(NU64 x_p0, NI len_p1, NIM_BOOL handleNegative_p2) {
	NimStringV2 result;
	NU64 n_1;
{	n_1 = x_p0;
	result = mnewString(len_p1);
	{
		NI j_1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_6;
		NI res_1;
		j_1 = (NI)0;
		colontmp_ = (NI)0;
		if (nimSubInt(len_p1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_6)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_6);
		res_1 = colontmp_;
		{
			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_9;
				if (!(((NI)0) <= res_1)) goto LA3;
				j_1 = ((NI) (res_1));
				if (j_1 < 0 || j_1 >= result.len){ raiseIndexError2(j_1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if ((NU64)(n_1 & 15ULL) > (NU64)(((NI)IL64(9223372036854775807)))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
				}
				if (((NI) ((NU64)(n_1 & 15ULL))) < 0 || ((NI) ((NU64)(n_1 & 15ULL))) >= TM__JGc9b9bh2D3nTdUR7TGyq8aA_8.len){ raiseIndexError2(((NI) ((NU64)(n_1 & 15ULL))),TM__JGc9b9bh2D3nTdUR7TGyq8aA_8.len-1); goto BeforeRet_;
				}
				result.p->data[j_1] = TM__JGc9b9bh2D3nTdUR7TGyq8aA_8.p->data[((NI) ((NU64)(n_1 & 15ULL)))];
				n_1 = (NU64)((NU64)(n_1) >> (NU64)(((NI)4) & (64 - 1)));
				{
					NIM_BOOL T6_;
					T6_ = (NIM_BOOL)0;
					T6_ = (n_1 == 0ULL);
					if (!(T6_)) goto LA7_;
					T6_ = handleNegative_p2;
LA7_: ;
					if (!T6_) goto LA8_;
					n_1 = 18446744073709551615ULL;
				}
LA8_: ;
				if (nimSubInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_9)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_9);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHex__pureZstrutils_u2174)(NI x_p0, NI len_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = toHexImpl__pureZstrutils_u783(((NU64) (((NI64) (x_p0)))), len_p1, (x_p0 < ((NI)0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuReplaceChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NIM_CHAR by_p2) {
	NimStringV2 result;
	NI i_1;
{	result.len = 0; result.p = NIM_NIL;
	if ((s_p0.len) < ((NI)0) || (s_p0.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(s_p0.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((s_p0.len));
	i_1 = ((NI)0);
	{
		while (1) {
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_10;
			if (!(i_1 < s_p0.len)) goto LA2;
			{
				if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
				}
				if (!((NU8)(s_p0.p->data[i_1]) == (NU8)(sub_p1))) goto LA5_;
				if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				result.p->data[i_1] = by_p2;
			}
			goto LA3_;
LA5_: ;
			{
				if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
				}
				result.p->data[i_1] = s_p0.p->data[i_1];
			}
LA3_: ;
			if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_10)) { raiseOverflow(); goto BeforeRet_;
			};
			i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_10);
		} LA2: ;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToUpperAsciiChar)(NIM_CHAR c_p0) {
	NIM_CHAR result;
	{
		if (!(((NU8)(c_p0)) >= ((NU8)(97)) && ((NU8)(c_p0)) <= ((NU8)(122)))) goto LA3_;
		result = ((NIM_CHAR) ((NU8)(((NU8) (((NU8)(c_p0)))) ^ ((NU8)32))));
	}
	goto LA1_;
LA3_: ;
	{
		result = c_p0;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuToUpperAsciiStr)(NimStringV2 s_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	if ((s_p0.len) < ((NI)0) || (s_p0.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(s_p0.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((s_p0.len));
	{
		NI iX60gensym11__1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_11;
		NI res_1;
		iX60gensym11__1 = (NI)0;
		colontmp_ = (NI)0;
		if (nimSubInt(s_p0.len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_11)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_11);
		res_1 = ((NI)0);
		{
			while (1) {
				NIM_CHAR T4_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_12;
				if (!(res_1 <= colontmp_)) goto LA3;
				iX60gensym11__1 = ((NI) (res_1));
				if (iX60gensym11__1 < 0 || iX60gensym11__1 >= result.len){ raiseIndexError2(iX60gensym11__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (iX60gensym11__1 < 0 || iX60gensym11__1 >= s_p0.len){ raiseIndexError2(iX60gensym11__1,s_p0.len-1); goto BeforeRet_;
				}
				T4_ = (NIM_CHAR)0;
				T4_ = nsuToUpperAsciiChar(s_p0.p->data[iX60gensym11__1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				result.p->data[iX60gensym11__1] = T4_;
				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_12)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_12);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuStrip)(NimStringV2 s_p0, NIM_BOOL leading_p1, NIM_BOOL trailing_p2, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p3) {
	NimStringV2 result;
	NI first_1;
	NI last_1;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_13;
{	result.len = 0; result.p = NIM_NIL;
	first_1 = ((NI)0);
	if (nimSubInt(s_p0.len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_13)) { raiseOverflow(); goto BeforeRet_;
	};
	last_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_13);
	{
		if (!leading_p1) goto LA3_;
		{
			while (1) {
				NIM_BOOL T7_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_14;
				T7_ = (NIM_BOOL)0;
				T7_ = (first_1 <= last_1);
				if (!(T7_)) goto LA8_;
				if (first_1 < 0 || first_1 >= s_p0.len){ raiseIndexError2(first_1,s_p0.len-1); goto BeforeRet_;
				}
				T7_ = ((chars_p3[(NU)((((NU8)(s_p0.p->data[first_1]))))>>3] &(1U<<((NU)((((NU8)(s_p0.p->data[first_1]))))&7U)))!=0);
LA8_: ;
				if (!T7_) goto LA6;
				if (nimAddInt(first_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_14)) { raiseOverflow(); goto BeforeRet_;
				};
				first_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_14);
			} LA6: ;
		}
	}
LA3_: ;
	{
		if (!trailing_p2) goto LA11_;
		{
			while (1) {
				NIM_BOOL T15_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_15;
				T15_ = (NIM_BOOL)0;
				T15_ = (first_1 <= last_1);
				if (!(T15_)) goto LA16_;
				if (last_1 < 0 || last_1 >= s_p0.len){ raiseIndexError2(last_1,s_p0.len-1); goto BeforeRet_;
				}
				T15_ = ((chars_p3[(NU)((((NU8)(s_p0.p->data[last_1]))))>>3] &(1U<<((NU)((((NU8)(s_p0.p->data[last_1]))))&7U)))!=0);
LA16_: ;
				if (!T15_) goto LA14;
				if (nimSubInt(last_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_15)) { raiseOverflow(); goto BeforeRet_;
				};
				last_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_15);
			} LA14: ;
		}
	}
LA11_: ;
	result = substr__system_u9113(s_p0, first_1, last_1);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuJoinSep)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 sep_p1) {
	NimStringV2 result;
{	result.len = 0; result.p = NIM_NIL;
	{
		NI L_1;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_16;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_17;
		if (!(((NI)0) < a_p0Len_0)) goto LA3_;
		if (nimSubInt(a_p0Len_0, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_16)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimMulInt(sep_p1.len, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_16), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_17)) { raiseOverflow(); goto BeforeRet_;
		};
		L_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_17);
		{
			NI i_1;
			NI colontmp_;
			NI res_1;
			i_1 = (NI)0;
			colontmp_ = (NI)0;
			colontmp_ = (a_p0Len_0-1);
			res_1 = ((NI)0);
			{
				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_18;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_19;
					if (!(res_1 <= colontmp_)) goto LA7;
					i_1 = ((NI) (res_1));
					if (i_1 < 0 || i_1 >= a_p0Len_0){ raiseIndexError2(i_1,a_p0Len_0-1); goto BeforeRet_;
					}
					if (nimAddInt(L_1, a_p0[i_1].len, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_18)) { raiseOverflow(); goto BeforeRet_;
					};
					L_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_18);
					if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_19)) { raiseOverflow(); goto BeforeRet_;
					};
					res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_19);
				} LA7: ;
			}
		}
		if ((L_1) < ((NI)0) || (L_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(L_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		result = rawNewString((L_1));
		if (((NI)0) < 0 || ((NI)0) >= a_p0Len_0){ raiseIndexError2(((NI)0),a_p0Len_0-1); goto BeforeRet_;
		}
		prepareAdd((&result), a_p0[((NI)0)].len + 0);
appendString((&result), a_p0[((NI)0)]);
		{
			NI i_2;
			NI colontmp__2;
			NI res_2;
			i_2 = (NI)0;
			colontmp__2 = (NI)0;
			colontmp__2 = (a_p0Len_0-1);
			res_2 = ((NI)1);
			{
				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_20;
					if (!(res_2 <= colontmp__2)) goto LA10;
					i_2 = ((NI) (res_2));
					prepareAdd((&result), sep_p1.len + 0);
appendString((&result), sep_p1);
					if (i_2 < 0 || i_2 >= a_p0Len_0){ raiseIndexError2(i_2,a_p0Len_0-1); goto BeforeRet_;
					}
					prepareAdd((&result), a_p0[i_2].len + 0);
appendString((&result), a_p0[i_2]);
					if (nimAddInt(res_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_20)) { raiseOverflow(); goto BeforeRet_;
					};
					res_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_20);
				} LA10: ;
			}
		}
	}
	goto LA1_;
LA3_: ;
	{
		result = TM__JGc9b9bh2D3nTdUR7TGyq8aA_22;
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuRepeatChar)(NIM_CHAR c_p0, NI count_p1) {
	NimStringV2 result;
{	result = mnewString(count_p1);
	{
		NI i_1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_23;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		if (nimSubInt(count_p1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_23)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_23);
		res_1 = ((NI)0);
		{
			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_24;
				if (!(res_1 <= colontmp_)) goto LA3;
				i_1 = ((NI) (res_1));
				if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				result.p->data[i_1] = c_p0;
				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_24)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_24);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	(*s_p0).len += ((NI)1);
	(*(*s_p0).p).data[(*s_p0).len] = 0;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuEscape)(NimStringV2 s_p0, NimStringV2 prefix_p1, NimStringV2 suffix_p2) {
	NimStringV2 result;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_25;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	if (nimAddInt(s_p0.len, (NI)((NI64)(s_p0.len) >> (NU64)(((NI)2) & (64 - 1))), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_25)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_25)) < ((NI)0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_25)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_25), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = rawNewString(((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_25)));
	prepareAdd((&result), prefix_p1.len + 0);
appendString((&result), prefix_p1);
	{
		NIM_CHAR c_1;
		NI i_1;
		NI L_1;
		c_1 = (NIM_CHAR)0;
		i_1 = ((NI)0);
		L_1 = s_p0.len;
		{
			while (1) {
				if (!(i_1 < L_1)) goto LA3;
				if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
				}
				c_1 = s_p0.p->data[i_1];
				switch (((NU8)(c_1))) {
				case 0 ... 31:
				case 127 ... 255:
				{
					NimStringV2 colontmpD_;
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
					prepareAdd((&result), 2);
appendString((&result), TM__JGc9b9bh2D3nTdUR7TGyq8aA_27);
					colontmpD_ = toHex__pureZstrutils_u2174(((NU8)(c_1)), ((NI)2));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					prepareAdd((&result), colontmpD_.len + 0);
appendString((&result), colontmpD_);
					if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
				}
				break;
				case 92:
				{
					prepareAdd((&result), 2);
appendString((&result), TM__JGc9b9bh2D3nTdUR7TGyq8aA_29);
				}
				break;
				case 39:
				{
					prepareAdd((&result), 2);
appendString((&result), TM__JGc9b9bh2D3nTdUR7TGyq8aA_31);
				}
				break;
				case 34:
				{
					prepareAdd((&result), 2);
appendString((&result), TM__JGc9b9bh2D3nTdUR7TGyq8aA_33);
				}
				break;
				default:
				{
					nimAddCharV1((&result), c_1);
				}
				break;
				}
				i_1 += ((NI)1);
				{
					if (!!((s_p0.len == L_1))) goto LA11_;
					failedAssertImpl__stdZassertions_u95(TM__JGc9b9bh2D3nTdUR7TGyq8aA_35);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA11_: ;
			} LA3: ;
		}
	}
	prepareAdd((&result), suffix_p2.len + 0);
appendString((&result), suffix_p2);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI64, nsuParseBiggestInt)(NimStringV2 s_p0) {
	NI64 result;
	NI L_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = IL64(0);
	L_1 = parseBiggestInt__pureZparseutils_u915(s_p0, (&result), ((NI)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NIM_BOOL T3_;
		tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw* T7_;
		NimStringV2 T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((L_1 == s_p0.len));
		if (T3_) goto LA4_;
		T3_ = (L_1 == ((NI)0));
LA4_: ;
		if (!T3_) goto LA5_;
		T7_ = NIM_NIL;
		T7_ = (tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw*) nimNewObj(sizeof(tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw), NIM_ALIGNOF(tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw));
		(*T7_).Sup.Sup.Sup.m_type = (&NTIv2__jLnwc41Xd9aFjddYhlZ15cw_);
		(*T7_).Sup.Sup.name = "ValueError";
		T8_.len = 0; T8_.p = NIM_NIL;
		T8_ = rawNewString(s_p0.len + 17);
appendString((&T8_), TM__JGc9b9bh2D3nTdUR7TGyq8aA_37);
appendString((&T8_), s_p0);
		(*T7_).Sup.Sup.message = T8_;
		(*T7_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T7_, "ValueError", "parseBiggestInt", "strutils.nim", 1170);
goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, nsuParseFloat)(NimStringV2 s_p0) {
	NF result;
	NI L_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0.0;
	L_1 = parseFloat__pureZparseutils_u945(s_p0, (&result), ((NI)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NIM_BOOL T3_;
		tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw* T7_;
		NimStringV2 T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((L_1 == s_p0.len));
		if (T3_) goto LA4_;
		T3_ = (L_1 == ((NI)0));
LA4_: ;
		if (!T3_) goto LA5_;
		T7_ = NIM_NIL;
		T7_ = (tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw*) nimNewObj(sizeof(tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw), NIM_ALIGNOF(tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw));
		(*T7_).Sup.Sup.Sup.m_type = (&NTIv2__jLnwc41Xd9aFjddYhlZ15cw_);
		(*T7_).Sup.Sup.name = "ValueError";
		T8_.len = 0; T8_.p = NIM_NIL;
		T8_ = rawNewString(s_p0.len + 15);
appendString((&T8_), TM__JGc9b9bh2D3nTdUR7TGyq8aA_39);
appendString((&T8_), s_p0);
		(*T7_).Sup.Sup.message = T8_;
		(*T7_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T7_, "ValueError", "parseFloat", "strutils.nim", 1202);
goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuNormalize)(NimStringV2 s_p0) {
	NimStringV2 result;
	NI j_1;
{	result.len = 0; result.p = NIM_NIL;
	if ((s_p0.len) < ((NI)0) || (s_p0.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(s_p0.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((s_p0.len));
	j_1 = ((NI)0);
	{
		NI i_1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_40;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		if (nimSubInt(s_p0.len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_40)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_40);
		res_1 = ((NI)0);
		{
			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_44;
				if (!(res_1 <= colontmp_)) goto LA3;
				i_1 = ((NI) (res_1));
				{
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_41;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_42;
					if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
					}
					if (!(((NU8)(s_p0.p->data[i_1])) >= ((NU8)(65)) && ((NU8)(s_p0.p->data[i_1])) <= ((NU8)(90)))) goto LA6_;
					if (j_1 < 0 || j_1 >= result.len){ raiseIndexError2(j_1,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
					}
					if (nimAddInt(((NU8)(s_p0.p->data[i_1])), ((NI)32), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_41)) { raiseOverflow(); goto BeforeRet_;
					};
					if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_41)) < ((NI)0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_41)) > ((NI)255)){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_41), ((NI)0), ((NI)255)); goto BeforeRet_;
					}
					result.p->data[j_1] = ((NIM_CHAR) (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_41))));
					if (nimAddInt(j_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_42)) { raiseOverflow(); goto BeforeRet_;
					};
					j_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_42);
				}
				goto LA4_;
LA6_: ;
				{
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_43;
					if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
					}
					if (!!(((NU8)(s_p0.p->data[i_1]) == (NU8)(95)))) goto LA9_;
					if (j_1 < 0 || j_1 >= result.len){ raiseIndexError2(j_1,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
					}
					result.p->data[j_1] = s_p0.p->data[i_1];
					if (nimAddInt(j_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_43)) { raiseOverflow(); goto BeforeRet_;
					};
					j_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_43);
				}
				goto LA4_;
LA9_: ;
LA4_: ;
				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_44)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_44);
			} LA3: ;
		}
	}
	{
		if (!!((j_1 == s_p0.len))) goto LA13_;
		if ((j_1) < ((NI)0) || (j_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(j_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		setLengthStrV2((&result), (j_1));
	}
LA13_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, nsuInitSkipTable)(NI* a_p0, NimStringV2 sub_p1) {
	NI m_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	m_1 = sub_p1.len;
	fill__pureZstrutils_u1634(a_p0, 256, m_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI i_1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_48;
		NI i_2;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		if (nimSubInt(m_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_48)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_48);
		i_2 = ((NI)0);
		{
			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_49;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_50;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_51;
				if (!(i_2 < colontmp_)) goto LA3;
				i_1 = i_2;
				if (i_1 < 0 || i_1 >= sub_p1.len){ raiseIndexError2(i_1,sub_p1.len-1); goto BeforeRet_;
				}
				if (nimSubInt(m_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_49)) { raiseOverflow(); goto BeforeRet_;
				};
				if (nimSubInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_49), i_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_50)) { raiseOverflow(); goto BeforeRet_;
				};
				a_p0[(((NU8)(sub_p1.p->data[i_1])))- 0] = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_50);
				if (nimAddInt(i_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_51)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_51);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, nsuInitNewSkipTable)(NimStringV2 sub_p0, tyArray__9cc9aPiDa8VaWjVcFLabEDZQ Result) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nsuInitSkipTable(Result, sub_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStrA)(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ a_p0, NimStringV2 s_p1, NimStringV2 sub_p2, NI start_p3, NI last_p4) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI last_2;
	NI subLast_1;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_52;
	NI skip_1;
{	result = (NI)0;
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	{
		if (!(last_p4 < ((NI)0))) goto LA3_;
		colontmpD_ = (s_p1.len-1);
		last_2 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = last_p4;
		last_2 = colontmpD__2;
	}
LA1_: ;
	if (nimSubInt(sub_p2.len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_52)) { raiseOverflow(); goto BeforeRet_;
	};
	subLast_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_52);
	{
		if (!(subLast_1 == ((NI)-1))) goto LA8_;
		result = start_p3;
		goto BeforeRet_;
	}
LA8_: ;
	result = ((NI)-1);
	skip_1 = start_p3;
	{
		while (1) {
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_53;
			NI i_1;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_56;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_57;
			if (nimSubInt(last_2, skip_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_53)) { raiseOverflow(); goto BeforeRet_;
			};
			if (!(subLast_1 <= (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_53))) goto LA11;
			i_1 = subLast_1;
			{
				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_54;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_55;
					if (nimAddInt(skip_1, i_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_54)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_54) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_54) >= s_p1.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_54),s_p1.len-1); goto BeforeRet_;
					}
					if (i_1 < 0 || i_1 >= sub_p2.len){ raiseIndexError2(i_1,sub_p2.len-1); goto BeforeRet_;
					}
					if (!((NU8)(s_p1.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_54)]) == (NU8)(sub_p2.p->data[i_1]))) goto LA13;
					{
						if (!(i_1 == ((NI)0))) goto LA16_;
						result = skip_1;
						goto BeforeRet_;
					}
LA16_: ;
					if (nimSubInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_55)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_55);
				} LA13: ;
			}
			if (nimAddInt(skip_1, subLast_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_56)) { raiseOverflow(); goto BeforeRet_;
			};
			if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_56) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_56) >= s_p1.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_56),s_p1.len-1); goto BeforeRet_;
			}
			if (nimAddInt(skip_1, a_p0[(((NU8)(s_p1.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_56)])))- 0], &TM__JGc9b9bh2D3nTdUR7TGyq8aA_57)) { raiseOverflow(); goto BeforeRet_;
			};
			if (TM__JGc9b9bh2D3nTdUR7TGyq8aA_57 < 0 || TM__JGc9b9bh2D3nTdUR7TGyq8aA_57 > IL64(9223372036854775807)){ raiseOverflow(); goto BeforeRet_;
			}
			skip_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_57);
		} LA11: ;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuReplaceStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NimStringV2 by_p2) {
	NimStringV2 result;
	NI subLen_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = TM__JGc9b9bh2D3nTdUR7TGyq8aA_45;
	subLen_1 = sub_p1.len;
	{
		if (!(subLen_1 == ((NI)0))) goto LA3_;
		eqcopy___system_u2723((&result), s_p0);
	}
	goto LA1_;
LA3_: ;
	{
		NimStringV2 colontmpD_;
		NIM_CHAR c_1;
		NI last_1;
		NI i_1;
		if (!(subLen_1 == ((NI)1))) goto LA6_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		if (((NI)0) < 0 || ((NI)0) >= sub_p1.len){ raiseIndexError2(((NI)0),sub_p1.len-1); goto LA8_;
		}
		c_1 = sub_p1.p->data[((NI)0)];
		last_1 = (s_p0.len-1);
		i_1 = ((NI)0);
		{
			while (1) {
				NimStringV2 colontmpD__2;
				NI j_1;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_46;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_47;
				colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
				if ((i_1) < ((NI)0) || (i_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(i_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA11_;
				}
				j_1 = nsuFindChar(s_p0, c_1, (i_1), last_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
				{
					if (!(j_1 < ((NI)0))) goto LA14_;
					if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
					goto LA9;
				}
LA14_: ;
				if (nimSubInt(j_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_46)) { raiseOverflow(); goto LA11_;
				};
				colontmpD__2 = substr__system_u9113(s_p0, i_1, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_46));
				prepareAdd((&result), colontmpD__2.len + 0);
appendString((&result), colontmpD__2);
				prepareAdd((&result), by_p2.len + 0);
appendString((&result), by_p2);
				if (nimAddInt(j_1, subLen_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_47)) { raiseOverflow(); goto LA11_;
				};
				i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_47);
				{
					LA11_:;
				}
				{
					if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
			}
		} LA9: ;
		colontmpD_ = substr__system_u9126(s_p0, i_1);
		prepareAdd((&result), colontmpD_.len + 0);
appendString((&result), colontmpD_);
		{
			LA8_:;
		}
		{
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA6_: ;
	{
		NimStringV2 colontmpD__3;
		tyArray__9cc9aPiDa8VaWjVcFLabEDZQ a_1;
		NI last_2;
		NI i_2;
		colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
		nimZeroMem((void*)a_1, sizeof(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ));
		nsuInitNewSkipTable(sub_p1, a_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
		last_2 = (s_p0.len-1);
		i_2 = ((NI)0);
		{
			while (1) {
				NimStringV2 colontmpD__4;
				NI j_2;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_58;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_59;
				colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
				if ((i_2) < ((NI)0) || (i_2) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(i_2, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA24_;
				}
				j_2 = nsuFindStrA(a_1, s_p0, sub_p1, (i_2), last_2);
				if (NIM_UNLIKELY(*nimErr_)) goto LA24_;
				{
					if (!(j_2 < ((NI)0))) goto LA27_;
					if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
					goto LA22;
				}
LA27_: ;
				if (nimSubInt(j_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_58)) { raiseOverflow(); goto LA24_;
				};
				colontmpD__4 = substr__system_u9113(s_p0, i_2, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_58));
				prepareAdd((&result), colontmpD__4.len + 0);
appendString((&result), colontmpD__4);
				prepareAdd((&result), by_p2.len + 0);
appendString((&result), by_p2);
				if (nimAddInt(j_2, subLen_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_59)) { raiseOverflow(); goto LA24_;
				};
				i_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_59);
				{
					LA24_:;
				}
				{
					if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
			}
		} LA22: ;
		colontmpD__3 = substr__system_u9126(s_p0, i_2);
		prepareAdd((&result), colontmpD__3.len + 0);
appendString((&result), colontmpD__3);
		{
			LA21_:;
		}
		{
			if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindCharSet)(NimStringV2 s_p0, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p1, NI start_p2, NI last_p3) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI last_2;
{	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	result = ((NI)-1);
	{
		if (!(last_p3 < ((NI)0))) goto LA3_;
		colontmpD_ = (s_p0.len-1);
		last_2 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = last_p3;
		last_2 = colontmpD__2;
	}
LA1_: ;
	{
		NI i_1;
		NI res_1;
		i_1 = (NI)0;
		res_1 = start_p2;
		{
			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_60;
				if (!(res_1 <= last_2)) goto LA8;
				i_1 = ((NI) (res_1));
				{
					if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
					}
					if (!((chars_p1[(NU)((((NU8)(s_p0.p->data[i_1]))))>>3] &(1U<<((NU)((((NU8)(s_p0.p->data[i_1]))))&7U)))!=0)) goto LA11_;
					result = i_1;
					goto BeforeRet_;
				}
LA11_: ;
				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_60)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_60);
			} LA8: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZstrutils_u1897)(NimStringV2 s_p0, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p1) {
	NIM_BOOL result;
	NI T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	T1_ = (NI)0;
	T1_ = nsuFindCharSet(s_p0, chars_p1, ((NI)0), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = (((NI)0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, invalidFormatString__pureZstrutils_u2654)(NimStringV2 formatstr_p0) {
	tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw* T1_;
	NimStringV2 T2_;
{	T1_ = NIM_NIL;
	T1_ = (tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw*) nimNewObj(sizeof(tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw), NIM_ALIGNOF(tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIv2__jLnwc41Xd9aFjddYhlZ15cw_);
	(*T1_).Sup.Sup.name = "ValueError";
	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = rawNewString(formatstr_p0.len + 23);
appendString((&T2_), TM__JGc9b9bh2D3nTdUR7TGyq8aA_65);
appendString((&T2_), formatstr_p0);
	(*T1_).Sup.Sup.message = T2_;
	(*T1_).Sup.Sup.parent = ((Exception*) NIM_NIL);
	raiseExceptionEx((Exception*)T1_, "ValueError", "invalidFormatString", "strutils.nim", 2831);
goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NIM_CHAR, toLowerAscii__stdZprivateZstrimpl_u1)(NIM_CHAR c_p0) {
	NIM_CHAR result;
{	result = (NIM_CHAR)0;
	{
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_85;
		if (!(((NU8)(c_p0)) >= ((NU8)(65)) && ((NU8)(c_p0)) <= ((NU8)(90)))) goto LA3_;
		if (nimAddInt(((NU8)(c_p0)), ((NI)32), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_85)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_85)) < ((NI)0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_85)) > ((NI)255)){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_85), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result = ((NIM_CHAR) (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_85))));
	}
	goto LA1_;
LA3_: ;
	{
		result = c_p0;
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NI result;
	NI aLenX60gensym24__1;
	NI bLenX60gensym24__1;
	NI iX60gensym24__1;
	NI jX60gensym24__1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	aLenX60gensym24__1 = a_p0.len;
	bLenX60gensym24__1 = b_p1.len;
	iX60gensym24__1 = ((NI)0);
	jX60gensym24__1 = ((NI)0);
	{
		while (1) {
			NIM_CHAR colontmpD_;
			NIM_CHAR colontmpD__2;
			NIM_CHAR colontmpD__3;
			NIM_CHAR colontmpD__4;
			NIM_CHAR aaX60gensym24__1;
			NIM_CHAR bbX60gensym24__1;
			colontmpD_ = (NIM_CHAR)0;
			colontmpD__2 = (NIM_CHAR)0;
			colontmpD__3 = (NIM_CHAR)0;
			colontmpD__4 = (NIM_CHAR)0;
			{
				while (1) {
					NIM_BOOL T5_;
					T5_ = (NIM_BOOL)0;
					T5_ = (iX60gensym24__1 < aLenX60gensym24__1);
					if (!(T5_)) goto LA6_;
					T5_ = ((NU8)(a_p0.p->data[iX60gensym24__1]) == (NU8)(95));
LA6_: ;
					if (!T5_) goto LA4;
					iX60gensym24__1 += ((NI)1);
				} LA4: ;
			}
			{
				while (1) {
					NIM_BOOL T9_;
					T9_ = (NIM_BOOL)0;
					T9_ = (jX60gensym24__1 < bLenX60gensym24__1);
					if (!(T9_)) goto LA10_;
					T9_ = ((NU8)(b_p1.p->data[jX60gensym24__1]) == (NU8)(95));
LA10_: ;
					if (!T9_) goto LA8;
					jX60gensym24__1 += ((NI)1);
				} LA8: ;
			}
			{
				if (!(iX60gensym24__1 < aLenX60gensym24__1)) goto LA13_;
				colontmpD_ = toLowerAscii__stdZprivateZstrimpl_u1(a_p0.p->data[iX60gensym24__1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				aaX60gensym24__1 = colontmpD_;
			}
			goto LA11_;
LA13_: ;
			{
				colontmpD__2 = 0;
				aaX60gensym24__1 = colontmpD__2;
			}
LA11_: ;
			{
				if (!(jX60gensym24__1 < bLenX60gensym24__1)) goto LA18_;
				colontmpD__3 = toLowerAscii__stdZprivateZstrimpl_u1(b_p1.p->data[jX60gensym24__1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				bbX60gensym24__1 = colontmpD__3;
			}
			goto LA16_;
LA18_: ;
			{
				colontmpD__4 = 0;
				bbX60gensym24__1 = colontmpD__4;
			}
LA16_: ;
			result = (NI)(((NU8)(aaX60gensym24__1)) - ((NU8)(bbX60gensym24__1)));
			{
				if (!!((result == ((NI)0)))) goto LA23_;
				goto BeforeRet_;
			}
LA23_: ;
			{
				if (!(aLenX60gensym24__1 <= iX60gensym24__1)) goto LA27_;
				{
					if (!(bLenX60gensym24__1 <= jX60gensym24__1)) goto LA31_;
					result = ((NI)0);
					goto BeforeRet_;
				}
LA31_: ;
				result = ((NI)-1);
				goto BeforeRet_;
			}
			goto LA25_;
LA27_: ;
			{
				if (!(bLenX60gensym24__1 <= jX60gensym24__1)) goto LA34_;
				result = ((NI)1);
				goto BeforeRet_;
			}
			goto LA25_;
LA34_: ;
LA25_: ;
			iX60gensym24__1 += ((NI)1);
			jX60gensym24__1 += ((NI)1);
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, findNormalized__pureZstrutils_u2641)(NimStringV2 x_p0, NimStringV2* inArray_p1, NI inArray_p1Len_0) {
	NI result;
	NI i_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	i_1 = ((NI)0);
	{
		while (1) {
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_86;
			if (!(i_1 < (inArray_p1Len_0-1))) goto LA2;
			{
				NI T5_;
				if (i_1 < 0 || i_1 >= inArray_p1Len_0){ raiseIndexError2(i_1,inArray_p1Len_0-1); goto BeforeRet_;
				}
				T5_ = (NI)0;
				T5_ = nsuCmpIgnoreStyle(x_p0, inArray_p1[i_1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!(T5_ == ((NI)0))) goto LA6_;
				result = i_1;
				goto BeforeRet_;
			}
LA6_: ;
			if (nimAddInt(i_1, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_86)) { raiseOverflow(); goto BeforeRet_;
			};
			i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_86);
		} LA2: ;
	}
	result = ((NI)-1);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nsuAddf)(NimStringV2* s_p0, NimStringV2 formatstr_p1, NimStringV2* a_p2, NI a_p2Len_0) {
	NI i_1;
	NI num_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	i_1 = ((NI)0);
	num_1 = ((NI)0);
	{
		while (1) {
			if (!(i_1 < formatstr_p1.len)) goto LA2;
			{
				NIM_BOOL T5_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_62;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_63;
				T5_ = (NIM_BOOL)0;
				if (i_1 < 0 || i_1 >= formatstr_p1.len){ raiseIndexError2(i_1,formatstr_p1.len-1); goto BeforeRet_;
				}
				T5_ = ((NU8)(formatstr_p1.p->data[i_1]) == (NU8)(36));
				if (!(T5_)) goto LA6_;
				if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_62)) { raiseOverflow(); goto BeforeRet_;
				};
				T5_ = ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_62) < formatstr_p1.len);
LA6_: ;
				if (!T5_) goto LA7_;
				if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_63)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_63) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_63) >= formatstr_p1.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_63),formatstr_p1.len-1); goto BeforeRet_;
				}
				switch (((NU8)(formatstr_p1.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_63)]))) {
				case 35:
				{
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_66;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_67;
					{
						if (!((a_p2Len_0-1) < num_1)) goto LA12_;
						invalidFormatString__pureZstrutils_u2654(formatstr_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
LA12_: ;
					if (num_1 < 0 || num_1 >= a_p2Len_0){ raiseIndexError2(num_1,a_p2Len_0-1); goto BeforeRet_;
					}
					prepareAdd((&(*s_p0)), a_p2[num_1].len + 0);
appendString((&(*s_p0)), a_p2[num_1]);
					if (nimAddInt(i_1, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_66)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_66);
					if (nimAddInt(num_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_67)) { raiseOverflow(); goto BeforeRet_;
					};
					num_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_67);
				}
				break;
				case 36:
				{
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_68;
					nimAddCharV1((&(*s_p0)), 36);
					if (nimAddInt(i_1, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_68)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_68);
				}
				break;
				case 49 ... 57:
				case 45:
				{
					NI colontmpD_;
					NI colontmpD__2;
					NI j_1;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_69;
					NIM_BOOL negative_1;
					NI idx_1;
					colontmpD_ = (NI)0;
					colontmpD__2 = (NI)0;
					j_1 = ((NI)0);
					if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_69)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_69);
					if (i_1 < 0 || i_1 >= formatstr_p1.len){ raiseIndexError2(i_1,formatstr_p1.len-1); goto BeforeRet_;
					}
					negative_1 = ((NU8)(formatstr_p1.p->data[i_1]) == (NU8)(45));
					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_70;
						if (!negative_1) goto LA18_;
						if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_70)) { raiseOverflow(); goto BeforeRet_;
						};
						i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_70);
					}
LA18_: ;
					{
						while (1) {
							NIM_BOOL T22_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_71;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_72;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_73;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_74;
							T22_ = (NIM_BOOL)0;
							T22_ = (i_1 < formatstr_p1.len);
							if (!(T22_)) goto LA23_;
							if (i_1 < 0 || i_1 >= formatstr_p1.len){ raiseIndexError2(i_1,formatstr_p1.len-1); goto BeforeRet_;
							}
							T22_ = (((NU8)(formatstr_p1.p->data[i_1])) >= ((NU8)(48)) && ((NU8)(formatstr_p1.p->data[i_1])) <= ((NU8)(57)));
LA23_: ;
							if (!T22_) goto LA21;
							if (nimMulInt(j_1, ((NI)10), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_71)) { raiseOverflow(); goto BeforeRet_;
							};
							if (i_1 < 0 || i_1 >= formatstr_p1.len){ raiseIndexError2(i_1,formatstr_p1.len-1); goto BeforeRet_;
							}
							if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_71), ((NU8)(formatstr_p1.p->data[i_1])), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_72)) { raiseOverflow(); goto BeforeRet_;
							};
							if (nimSubInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_72), ((NI)48), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_73)) { raiseOverflow(); goto BeforeRet_;
							};
							j_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_73);
							if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_74)) { raiseOverflow(); goto BeforeRet_;
							};
							i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_74);
						} LA21: ;
					}
					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_75;
						if (!!(negative_1)) goto LA26_;
						if (nimSubInt(j_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_75)) { raiseOverflow(); goto BeforeRet_;
						};
						colontmpD_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_75);
						idx_1 = colontmpD_;
					}
					goto LA24_;
LA26_: ;
					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_76;
						if (nimSubInt(a_p2Len_0, j_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_76)) { raiseOverflow(); goto BeforeRet_;
						};
						colontmpD__2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_76);
						idx_1 = colontmpD__2;
					}
LA24_: ;
					{
						NIM_BOOL T31_;
						T31_ = (NIM_BOOL)0;
						T31_ = (idx_1 < ((NI)0));
						if (T31_) goto LA32_;
						T31_ = ((a_p2Len_0-1) < idx_1);
LA32_: ;
						if (!T31_) goto LA33_;
						invalidFormatString__pureZstrutils_u2654(formatstr_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
LA33_: ;
					if (idx_1 < 0 || idx_1 >= a_p2Len_0){ raiseIndexError2(idx_1,a_p2Len_0-1); goto BeforeRet_;
					}
					prepareAdd((&(*s_p0)), a_p2[idx_1].len + 0);
appendString((&(*s_p0)), a_p2[idx_1]);
				}
				break;
				case 123:
				{
					NI j_2;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_77;
					NI k_1;
					NIM_BOOL negative_2;
					NI isNumber_1;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_90;
					if (nimAddInt(i_1, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_77)) { raiseOverflow(); goto BeforeRet_;
					};
					j_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_77);
					k_1 = ((NI)0);
					if (j_2 < 0 || j_2 >= formatstr_p1.len){ raiseIndexError2(j_2,formatstr_p1.len-1); goto BeforeRet_;
					}
					negative_2 = ((NU8)(formatstr_p1.p->data[j_2]) == (NU8)(45));
					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_78;
						if (!negative_2) goto LA38_;
						if (nimAddInt(j_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_78)) { raiseOverflow(); goto BeforeRet_;
						};
						j_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_78);
					}
LA38_: ;
					isNumber_1 = ((NI)0);
					{
						while (1) {
							NIM_BOOL T42_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_82;
							T42_ = (NIM_BOOL)0;
							T42_ = (j_2 < formatstr_p1.len);
							if (!(T42_)) goto LA43_;
							if (j_2 < 0 || j_2 >= formatstr_p1.len){ raiseIndexError2(j_2,formatstr_p1.len-1); goto BeforeRet_;
							}
							T42_ = !((((NU8)(formatstr_p1.p->data[j_2])) == ((NU8)(0)) || ((NU8)(formatstr_p1.p->data[j_2])) == ((NU8)(125))));
LA43_: ;
							if (!T42_) goto LA41;
							{
								NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_79;
								NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_80;
								NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_81;
								if (j_2 < 0 || j_2 >= formatstr_p1.len){ raiseIndexError2(j_2,formatstr_p1.len-1); goto BeforeRet_;
								}
								if (!(((NU8)(formatstr_p1.p->data[j_2])) >= ((NU8)(48)) && ((NU8)(formatstr_p1.p->data[j_2])) <= ((NU8)(57)))) goto LA46_;
								if (nimMulInt(k_1, ((NI)10), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_79)) { raiseOverflow(); goto BeforeRet_;
								};
								if (j_2 < 0 || j_2 >= formatstr_p1.len){ raiseIndexError2(j_2,formatstr_p1.len-1); goto BeforeRet_;
								}
								if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_79), ((NU8)(formatstr_p1.p->data[j_2])), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_80)) { raiseOverflow(); goto BeforeRet_;
								};
								if (nimSubInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_80), ((NI)48), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_81)) { raiseOverflow(); goto BeforeRet_;
								};
								k_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_81);
								{
									if (!(isNumber_1 == ((NI)0))) goto LA50_;
									isNumber_1 = ((NI)1);
								}
LA50_: ;
							}
							goto LA44_;
LA46_: ;
							{
								isNumber_1 = ((NI)-1);
							}
LA44_: ;
							if (nimAddInt(j_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_82)) { raiseOverflow(); goto BeforeRet_;
							};
							j_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_82);
						} LA41: ;
					}
					{
						NI colontmpD__3;
						NI colontmpD__4;
						NI idx_2;
						if (!(isNumber_1 == ((NI)1))) goto LA55_;
						colontmpD__3 = (NI)0;
						colontmpD__4 = (NI)0;
						{
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_83;
							if (!!(negative_2)) goto LA59_;
							if (nimSubInt(k_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_83)) { raiseOverflow(); goto BeforeRet_;
							};
							colontmpD__3 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_83);
							idx_2 = colontmpD__3;
						}
						goto LA57_;
LA59_: ;
						{
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_84;
							if (nimSubInt(a_p2Len_0, k_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_84)) { raiseOverflow(); goto BeforeRet_;
							};
							colontmpD__4 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_84);
							idx_2 = colontmpD__4;
						}
LA57_: ;
						{
							NIM_BOOL T64_;
							T64_ = (NIM_BOOL)0;
							T64_ = (idx_2 < ((NI)0));
							if (T64_) goto LA65_;
							T64_ = ((a_p2Len_0-1) < idx_2);
LA65_: ;
							if (!T64_) goto LA66_;
							invalidFormatString__pureZstrutils_u2654(formatstr_p1);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						}
LA66_: ;
						if (idx_2 < 0 || idx_2 >= a_p2Len_0){ raiseIndexError2(idx_2,a_p2Len_0-1); goto BeforeRet_;
						}
						prepareAdd((&(*s_p0)), a_p2[idx_2].len + 0);
appendString((&(*s_p0)), a_p2[idx_2]);
					}
					goto LA53_;
LA55_: ;
					{
						NimStringV2 colontmpD__5;
						NI x_1;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_87;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_88;
						colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
						if (nimAddInt(i_1, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_87)) { raiseOverflow(); goto LA69_;
						};
						if (nimSubInt(j_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_88)) { raiseOverflow(); goto LA69_;
						};
						colontmpD__5 = substr__system_u9113(formatstr_p1, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_87), (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_88));
						x_1 = findNormalized__pureZstrutils_u2641(colontmpD__5, a_p2, a_p2Len_0);
						if (NIM_UNLIKELY(*nimErr_)) goto LA69_;
						{
							NIM_BOOL T72_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_89;
							T72_ = (NIM_BOOL)0;
							T72_ = (((NI)0) <= x_1);
							if (!(T72_)) goto LA73_;
							T72_ = (x_1 < (a_p2Len_0-1));
LA73_: ;
							if (!T72_) goto LA74_;
							if (nimAddInt(x_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_89)) { raiseOverflow(); goto LA69_;
							};
							if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_89) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_89) >= a_p2Len_0){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_89),a_p2Len_0-1); goto LA69_;
							}
							prepareAdd((&(*s_p0)), a_p2[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_89)].len + 0);
appendString((&(*s_p0)), a_p2[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_89)]);
						}
						goto LA70_;
LA74_: ;
						{
							invalidFormatString__pureZstrutils_u2654(formatstr_p1);
							if (NIM_UNLIKELY(*nimErr_)) goto LA69_;
						}
LA70_: ;
						{
							LA69_:;
						}
						{
							if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
						}
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
LA53_: ;
					if (nimAddInt(j_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_90)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_90);
				}
				break;
				case 97 ... 122:
				case 65 ... 90:
				case 128 ... 255:
				case 95:
				{
					NimStringV2 colontmpD__6;
					NI j_3;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_91;
					NI x_2;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_93;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_94;
					colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
					if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_91)) { raiseOverflow(); goto LA80_;
					};
					j_3 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_91);
					{
						while (1) {
							NIM_BOOL T83_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_92;
							T83_ = (NIM_BOOL)0;
							T83_ = (j_3 < formatstr_p1.len);
							if (!(T83_)) goto LA84_;
							if (j_3 < 0 || j_3 >= formatstr_p1.len){ raiseIndexError2(j_3,formatstr_p1.len-1); goto LA80_;
							}
							T83_ = (((NU8)(formatstr_p1.p->data[j_3])) >= ((NU8)(97)) && ((NU8)(formatstr_p1.p->data[j_3])) <= ((NU8)(122)) || ((NU8)(formatstr_p1.p->data[j_3])) >= ((NU8)(65)) && ((NU8)(formatstr_p1.p->data[j_3])) <= ((NU8)(90)) || ((NU8)(formatstr_p1.p->data[j_3])) >= ((NU8)(48)) && ((NU8)(formatstr_p1.p->data[j_3])) <= ((NU8)(57)) || ((NU8)(formatstr_p1.p->data[j_3])) >= ((NU8)(128)) && ((NU8)(formatstr_p1.p->data[j_3])) <= ((NU8)(255)) || ((NU8)(formatstr_p1.p->data[j_3])) == ((NU8)(95)));
LA84_: ;
							if (!T83_) goto LA82;
							if (nimAddInt(j_3, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_92)) { raiseOverflow(); goto LA80_;
							};
							j_3 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_92);
						} LA82: ;
					}
					if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_93)) { raiseOverflow(); goto LA80_;
					};
					if (nimSubInt(j_3, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_94)) { raiseOverflow(); goto LA80_;
					};
					colontmpD__6 = substr__system_u9113(formatstr_p1, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_93), (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_94));
					x_2 = findNormalized__pureZstrutils_u2641(colontmpD__6, a_p2, a_p2Len_0);
					if (NIM_UNLIKELY(*nimErr_)) goto LA80_;
					{
						NIM_BOOL T87_;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_95;
						T87_ = (NIM_BOOL)0;
						T87_ = (((NI)0) <= x_2);
						if (!(T87_)) goto LA88_;
						T87_ = (x_2 < (a_p2Len_0-1));
LA88_: ;
						if (!T87_) goto LA89_;
						if (nimAddInt(x_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_95)) { raiseOverflow(); goto LA80_;
						};
						if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_95) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_95) >= a_p2Len_0){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_95),a_p2Len_0-1); goto LA80_;
						}
						prepareAdd((&(*s_p0)), a_p2[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_95)].len + 0);
appendString((&(*s_p0)), a_p2[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_95)]);
					}
					goto LA85_;
LA89_: ;
					{
						invalidFormatString__pureZstrutils_u2654(formatstr_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto LA80_;
					}
LA85_: ;
					i_1 = j_3;
					{
						LA80_:;
					}
					{
						if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
					}
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				break;
				default:
				{
					invalidFormatString__pureZstrutils_u2654(formatstr_p1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				break;
				}
			}
			goto LA3_;
LA7_: ;
			{
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_96;
				if (i_1 < 0 || i_1 >= formatstr_p1.len){ raiseIndexError2(i_1,formatstr_p1.len-1); goto BeforeRet_;
				}
				nimAddCharV1((&(*s_p0)), formatstr_p1.p->data[i_1]);
				if (nimAddInt(i_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_96)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_96);
			}
LA3_: ;
		} LA2: ;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuFormatOpenArray)(NimStringV2 formatstr_p0, NimStringV2* a_p1, NI a_p1Len_0) {
	NimStringV2 result;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_61;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	if (nimAddInt(formatstr_p0.len, (NI)((NU64)(a_p1Len_0) << (NU64)(((NI)4) & (64 - 1))), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_61)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_61)) < ((NI)0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_61)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_61), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = rawNewString(((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_61)));
	nsuAddf((&result), formatstr_p0, a_p1, a_p1Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuParseInt)(NimStringV2 s_p0) {
	NI result;
	NI L_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = ((NI)0);
	L_1 = parseInt__pureZparseutils_u920(s_p0, (&result), ((NI)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NIM_BOOL T3_;
		tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw* T7_;
		NimStringV2 T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((L_1 == s_p0.len));
		if (T3_) goto LA4_;
		T3_ = (L_1 == ((NI)0));
LA4_: ;
		if (!T3_) goto LA5_;
		T7_ = NIM_NIL;
		T7_ = (tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw*) nimNewObj(sizeof(tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw), NIM_ALIGNOF(tyObject_ValueError__jLnwc41Xd9aFjddYhlZ15cw));
		(*T7_).Sup.Sup.Sup.m_type = (&NTIv2__jLnwc41Xd9aFjddYhlZ15cw_);
		(*T7_).Sup.Sup.name = "ValueError";
		T8_.len = 0; T8_.p = NIM_NIL;
		T8_ = rawNewString(s_p0.len + 17);
appendString((&T8_), TM__JGc9b9bh2D3nTdUR7TGyq8aA_97);
appendString((&T8_), s_p0);
		(*T7_).Sup.Sup.message = T8_;
		(*T7_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T7_, "ValueError", "parseInt", "strutils.nim", 1160);
goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitChar)(NimStringV2 s_p0, NIM_CHAR sep_p1, NI maxsplit_p2) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	{
		NimStringV2 xX60gensym67__1;
		NI lastX60gensym34__1;
		NI splitsX60gensym34__1;
		xX60gensym67__1.len = 0; xX60gensym67__1.p = NIM_NIL;
		lastX60gensym34__1 = ((NI)0);
		splitsX60gensym34__1 = maxsplit_p2;
		{
			while (1) {
				NI firstX60gensym34__1;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_99;
				NimStringV2 T13_;
				NimStringV2 blitTmp_1;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_100;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_101;
				if (!(lastX60gensym34__1 <= s_p0.len)) goto LA4;
				firstX60gensym34__1 = lastX60gensym34__1;
				{
					while (1) {
						NIM_BOOL T7_;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_98;
						T7_ = (NIM_BOOL)0;
						T7_ = (lastX60gensym34__1 < s_p0.len);
						if (!(T7_)) goto LA8_;
						if (lastX60gensym34__1 < 0 || lastX60gensym34__1 >= s_p0.len){ raiseIndexError2(lastX60gensym34__1,s_p0.len-1); goto LA2_;
						}
						T7_ = !(((NU8)(s_p0.p->data[lastX60gensym34__1]) == (NU8)(sep_p1)));
LA8_: ;
						if (!T7_) goto LA6;
						if (nimAddInt(lastX60gensym34__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_98)) { raiseOverflow(); goto LA2_;
						};
						lastX60gensym34__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_98);
					} LA6: ;
				}
				{
					if (!(splitsX60gensym34__1 == ((NI)0))) goto LA11_;
					lastX60gensym34__1 = s_p0.len;
				}
LA11_: ;
				if (nimSubInt(lastX60gensym34__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_99)) { raiseOverflow(); goto LA2_;
				};
				T13_.len = 0; T13_.p = NIM_NIL;
				T13_ = substr__system_u9113(s_p0, firstX60gensym34__1, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_99));
				eqsink___system_u2729((&xX60gensym67__1), T13_);
				blitTmp_1 = xX60gensym67__1;
				eqwasMoved___system_u2720((&xX60gensym67__1));
				add__stdZenumutils_u70((&result), blitTmp_1);
				{
					if (!(splitsX60gensym34__1 == ((NI)0))) goto LA16_;
					goto LA3;
				}
LA16_: ;
				if (nimSubInt(splitsX60gensym34__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_100)) { raiseOverflow(); goto LA2_;
				};
				splitsX60gensym34__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_100);
				if (nimAddInt(lastX60gensym34__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_101)) { raiseOverflow(); goto LA2_;
				};
				lastX60gensym34__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_101);
			} LA4: ;
		} LA3: ;
		{
			LA2_:;
		}
		{
			if (xX60gensym67__1.p && !(xX60gensym67__1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(xX60gensym67__1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToLowerAsciiChar)(NIM_CHAR c_p0) {
	NIM_CHAR result;
	{
		if (!(((NU8)(c_p0)) >= ((NU8)(65)) && ((NU8)(c_p0)) <= ((NU8)(90)))) goto LA3_;
		result = ((NIM_CHAR) ((NU8)(((NU8) (((NU8)(c_p0)))) ^ ((NU8)32))));
	}
	goto LA1_;
LA3_: ;
	{
		result = c_p0;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuToLowerAsciiStr)(NimStringV2 s_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	if ((s_p0.len) < ((NI)0) || (s_p0.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(s_p0.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((s_p0.len));
	{
		NI iX60gensym7__1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_102;
		NI res_1;
		iX60gensym7__1 = (NI)0;
		colontmp_ = (NI)0;
		if (nimSubInt(s_p0.len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_102)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_102);
		res_1 = ((NI)0);
		{
			while (1) {
				NIM_CHAR T4_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_103;
				if (!(res_1 <= colontmp_)) goto LA3;
				iX60gensym7__1 = ((NI) (res_1));
				if (iX60gensym7__1 < 0 || iX60gensym7__1 >= result.len){ raiseIndexError2(iX60gensym7__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (iX60gensym7__1 < 0 || iX60gensym7__1 >= s_p0.len){ raiseIndexError2(iX60gensym7__1,s_p0.len-1); goto BeforeRet_;
				}
				T4_ = (NIM_CHAR)0;
				T4_ = nsuToLowerAsciiChar(s_p0.p->data[iX60gensym7__1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				result.p->data[iX60gensym7__1] = T4_;
				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_103)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_103);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NI result;
	NI aLenX60gensym20__1;
	NI bLenX60gensym20__1;
	NI iX60gensym20__1;
	NI mX60gensym20__1;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_106;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	aLenX60gensym20__1 = a_p0.len;
	bLenX60gensym20__1 = b_p1.len;
	iX60gensym20__1 = ((NI)0);
	mX60gensym20__1 = ((aLenX60gensym20__1 <= bLenX60gensym20__1) ? aLenX60gensym20__1 : bLenX60gensym20__1);
	{
		while (1) {
			NIM_CHAR T3_;
			NIM_CHAR T4_;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_104;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_105;
			if (!(iX60gensym20__1 < mX60gensym20__1)) goto LA2;
			if (iX60gensym20__1 < 0 || iX60gensym20__1 >= a_p0.len){ raiseIndexError2(iX60gensym20__1,a_p0.len-1); goto BeforeRet_;
			}
			T3_ = (NIM_CHAR)0;
			T3_ = toLowerAscii__stdZprivateZstrimpl_u1(a_p0.p->data[iX60gensym20__1]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (iX60gensym20__1 < 0 || iX60gensym20__1 >= b_p1.len){ raiseIndexError2(iX60gensym20__1,b_p1.len-1); goto BeforeRet_;
			}
			T4_ = (NIM_CHAR)0;
			T4_ = toLowerAscii__stdZprivateZstrimpl_u1(b_p1.p->data[iX60gensym20__1]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (nimSubInt(((NU8)(T3_)), ((NU8)(T4_)), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_104)) { raiseOverflow(); goto BeforeRet_;
			};
			result = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_104);
			{
				if (!!((result == ((NI)0)))) goto LA7_;
				goto BeforeRet_;
			}
LA7_: ;
			if (nimAddInt(iX60gensym20__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_105)) { raiseOverflow(); goto BeforeRet_;
			};
			iX60gensym20__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_105);
		} LA2: ;
	}
	if (nimSubInt(aLenX60gensym20__1, bLenX60gensym20__1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_106)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_106);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHex__pureZstrutils_u809)(NimStringV2 s_p0) {
	NimStringV2 result;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_107;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	if (nimMulInt(s_p0.len, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_107)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_107)) < ((NI)0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_107)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_107), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString(((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_107)));
	{
		NI pos_1;
		NIM_CHAR c_1;
		NI i_1;
		NI L_1;
		pos_1 = (NI)0;
		c_1 = (NIM_CHAR)0;
		i_1 = ((NI)0);
		L_1 = s_p0.len;
		{
			while (1) {
				NI n_1;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_108;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_109;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_111;
				if (!(i_1 < L_1)) goto LA3;
				pos_1 = i_1;
				if (i_1 < 0 || i_1 >= s_p0.len){ raiseIndexError2(i_1,s_p0.len-1); goto BeforeRet_;
				}
				c_1 = s_p0.p->data[i_1];
				n_1 = ((NU8)(c_1));
				if (nimMulInt(pos_1, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_108)) { raiseOverflow(); goto BeforeRet_;
				};
				if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_108), ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_109)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_109) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_109) >= result.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_109),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if ((NI)(n_1 & ((NI)15)) < 0 || (NI)(n_1 & ((NI)15)) >= TM__JGc9b9bh2D3nTdUR7TGyq8aA_110.len){ raiseIndexError2((NI)(n_1 & ((NI)15)),TM__JGc9b9bh2D3nTdUR7TGyq8aA_110.len-1); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_109)] = TM__JGc9b9bh2D3nTdUR7TGyq8aA_110.p->data[(NI)(n_1 & ((NI)15))];
				n_1 = (NI)((NI64)(n_1) >> (NU64)(((NI)4) & (64 - 1)));
				if (nimMulInt(pos_1, ((NI)2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_111)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_111) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_111) >= result.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_111),result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (n_1 < 0 || n_1 >= TM__JGc9b9bh2D3nTdUR7TGyq8aA_112.len){ raiseIndexError2(n_1,TM__JGc9b9bh2D3nTdUR7TGyq8aA_112.len-1); goto BeforeRet_;
				}
				result.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_111)] = TM__JGc9b9bh2D3nTdUR7TGyq8aA_112.p->data[n_1];
				i_1 += ((NI)1);
				{
					if (!!((s_p0.len == L_1))) goto LA6_;
					failedAssertImpl__stdZassertions_u95(TM__JGc9b9bh2D3nTdUR7TGyq8aA_114);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA6_: ;
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringV2 s_p0, NimStringV2 prefix_p1) {
	NIM_BOOL result;
	NI prefixLenX60gensym144__1;
	NI sLenX60gensym144__1;
	NI iX60gensym144__1;
{	result = NIM_FALSE;
	prefixLenX60gensym144__1 = prefix_p1.len;
	sLenX60gensym144__1 = s_p0.len;
	iX60gensym144__1 = ((NI)0);
	{
		while (1) {
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_115;
			{
				if (!(prefixLenX60gensym144__1 <= iX60gensym144__1)) goto LA5_;
				result = NIM_TRUE;
				goto BeforeRet_;
			}
LA5_: ;
			{
				NIM_BOOL T9_;
				T9_ = (NIM_BOOL)0;
				T9_ = (sLenX60gensym144__1 <= iX60gensym144__1);
				if (T9_) goto LA10_;
				if (iX60gensym144__1 < 0 || iX60gensym144__1 >= s_p0.len){ raiseIndexError2(iX60gensym144__1,s_p0.len-1); goto BeforeRet_;
				}
				if (iX60gensym144__1 < 0 || iX60gensym144__1 >= prefix_p1.len){ raiseIndexError2(iX60gensym144__1,prefix_p1.len-1); goto BeforeRet_;
				}
				T9_ = !(((NU8)(s_p0.p->data[iX60gensym144__1]) == (NU8)(prefix_p1.p->data[iX60gensym144__1])));
LA10_: ;
				if (!T9_) goto LA11_;
				result = NIM_FALSE;
				goto BeforeRet_;
			}
LA11_: ;
			if (nimAddInt(iX60gensym144__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_115)) { raiseOverflow(); goto BeforeRet_;
			};
			iX60gensym144__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_115);
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NI start_p2, NI last_p3) {
	NI result;
	tyArray__9cc9aPiDa8VaWjVcFLabEDZQ T9_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	{
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_116;
		if (nimSubInt(s_p0.len, start_p2, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_116)) { raiseOverflow(); goto BeforeRet_;
		};
		if (!((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_116) < sub_p1.len)) goto LA3_;
		result = ((NI)-1);
		goto BeforeRet_;
	}
LA3_: ;
	{
		if (!(sub_p1.len == ((NI)1))) goto LA7_;
		if (((NI)0) < 0 || ((NI)0) >= sub_p1.len){ raiseIndexError2(((NI)0),sub_p1.len-1); goto BeforeRet_;
		}
		result = nsuFindChar(s_p0, sub_p1.p->data[((NI)0)], start_p2, last_p3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA7_: ;
	nimZeroMem((void*)T9_, sizeof(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ));
	nsuInitNewSkipTable(sub_p1, T9_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = nsuFindStrA(T9_, s_p0, sub_p1, start_p2, last_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZstrutils_u1893)(NimStringV2 s_p0, NimStringV2 sub_p1) {
	NIM_BOOL result;
	NI T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	T1_ = (NI)0;
	T1_ = nsuFindStr(s_p0, sub_p1, ((NI)0), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = (((NI)0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuEndsWith)(NimStringV2 s_p0, NimStringV2 suffix_p1) {
	NIM_BOOL result;
	NI suffixLenX60gensym151__1;
	NI sLenX60gensym151__1;
	NI iX60gensym151__1;
	NI jX60gensym151__1;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_117;
{	result = NIM_FALSE;
	suffixLenX60gensym151__1 = suffix_p1.len;
	sLenX60gensym151__1 = s_p0.len;
	iX60gensym151__1 = ((NI)0);
	if (nimSubInt(sLenX60gensym151__1, suffixLenX60gensym151__1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_117)) { raiseOverflow(); goto BeforeRet_;
	};
	jX60gensym151__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_117);
	{
		while (1) {
			NIM_BOOL T3_;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_118;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_119;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_121;
			T3_ = (NIM_BOOL)0;
			if (nimAddInt(iX60gensym151__1, jX60gensym151__1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_118)) { raiseOverflow(); goto BeforeRet_;
			};
			T3_ = (((NI)0) <= (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_118));
			if (!(T3_)) goto LA4_;
			if (nimAddInt(iX60gensym151__1, jX60gensym151__1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_119)) { raiseOverflow(); goto BeforeRet_;
			};
			T3_ = ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_119) < sLenX60gensym151__1);
LA4_: ;
			if (!T3_) goto LA2;
			{
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_120;
				if (nimAddInt(iX60gensym151__1, jX60gensym151__1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_120)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_120) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_120) >= s_p0.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_120),s_p0.len-1); goto BeforeRet_;
				}
				if (iX60gensym151__1 < 0 || iX60gensym151__1 >= suffix_p1.len){ raiseIndexError2(iX60gensym151__1,suffix_p1.len-1); goto BeforeRet_;
				}
				if (!!(((NU8)(s_p0.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_120)]) == (NU8)(suffix_p1.p->data[iX60gensym151__1])))) goto LA7_;
				result = NIM_FALSE;
				goto BeforeRet_;
			}
LA7_: ;
			if (nimAddInt(iX60gensym151__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_121)) { raiseOverflow(); goto BeforeRet_;
			};
			iX60gensym151__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_121);
		} LA2: ;
	}
	{
		if (!(suffixLenX60gensym151__1 <= iX60gensym151__1)) goto LA11_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
LA11_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_CHAR*, X5BX5D___system_u8588)(NimStringV2* s_p0, NI i_p1) {
	NIM_CHAR* result;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_123;
{	result = (NIM_CHAR*)0;
	nimPrepareStrMutationV2((&(*s_p0)));
	if (nimSubInt((*s_p0).len, i_p1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_123)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_123) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_123) >= (*s_p0).len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_123),(*s_p0).len-1); goto BeforeRet_;
	}
	result = (&(*s_p0).p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_123)]);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, X5BX5Deq___system_u8603)(NimStringV2* s_p0, NI i_p1, NIM_CHAR x_p2) {
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_124;
{	if (nimSubInt((*s_p0).len, i_p1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_124)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_124) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_124) >= (*s_p0).len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_124),(*s_p0).len-1); goto BeforeRet_;
	}
	nimPrepareStrMutationV2((&(*s_p0)));
	(*s_p0).p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_124)] = x_p2;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuformatBiggestFloat)(NF f_p0, tyEnum_FloatFormatMode__NktTD9agsSu9bXX0rEiwGseg format_p1, NI precision_p2, NIM_CHAR decimalSep_p3) {
	NimStringV2 result;
	tyArray__Dz6OE1kpzz8bnx9batFy1Cw frmtstr_1;
	tyArray__WALV5e0ysjOIjCclEgOBNg buf_1;
	int L_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	L_1 = (int)0;
	frmtstr_1[(((NI)0))- 0] = 37;
	{
		if (!(((NI)0) <= precision_p2)) goto LA3_;
		frmtstr_1[(((NI)1))- 0] = 35;
		frmtstr_1[(((NI)2))- 0] = 46;
		frmtstr_1[(((NI)3))- 0] = 42;
		frmtstr_1[(((NI)4))- 0] = floatFormatToChar__pureZstrutils_u2252[(format_p1)- 0];
		frmtstr_1[(((NI)5))- 0] = 0;
		L_1 = snprintf(((NCSTRING) (buf_1)), ((size_t)2501), ((NCSTRING) (frmtstr_1)), precision_p2, f_p0);
	}
	goto LA1_;
LA3_: ;
	{
		frmtstr_1[(((NI)1))- 0] = floatFormatToChar__pureZstrutils_u2252[(format_p1)- 0];
		frmtstr_1[(((NI)2))- 0] = 0;
		L_1 = snprintf(((NCSTRING) (buf_1)), ((size_t)2501), ((NCSTRING) (frmtstr_1)), f_p0);
	}
LA1_: ;
	if ((L_1) < ((NI)0) || (L_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(L_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString(((NI) (L_1)));
	{
		NI32 i_1;
		NI32 res_1;
		i_1 = (NI32)0;
		res_1 = ((NI32)0);
		{
			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_122;
				if (!(res_1 < L_1)) goto LA8;
				i_1 = res_1;
				{
					if ((NU)(i_1) > (NU)(2500)){ raiseIndexError2(i_1, 2500); goto BeforeRet_;
					}
					if (!(((NU8)(buf_1[(i_1)- 0])) == ((NU8)(46)) || ((NU8)(buf_1[(i_1)- 0])) == ((NU8)(44)))) goto LA11_;
					if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					result.p->data[i_1] = decimalSep_p3;
				}
				goto LA9_;
LA11_: ;
				{
					if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					if ((NU)(i_1) > (NU)(2500)){ raiseIndexError2(i_1, 2500); goto BeforeRet_;
					}
					result.p->data[i_1] = buf_1[(i_1)- 0];
				}
LA9_: ;
				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_122)) { raiseOverflow(); goto BeforeRet_;
				};
				if (TM__JGc9b9bh2D3nTdUR7TGyq8aA_122 < (-2147483647 -1) || TM__JGc9b9bh2D3nTdUR7TGyq8aA_122 > 2147483647){ raiseOverflow(); goto BeforeRet_;
				}
				res_1 = (NI32)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_122);
			} LA8: ;
		}
	}
	{
		NIM_BOOL T16_;
		NIM_BOOL T17_;
		NIM_CHAR* T19_;
		NIM_CHAR* T21_;
		NimStringV2* T24_;
		NIM_CHAR* T25_;
		NimStringV2* T26_;
		NIM_CHAR* T27_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_125;
		T16_ = (NIM_BOOL)0;
		T17_ = (NIM_BOOL)0;
		T17_ = (((NI)4) < result.len);
		if (!(T17_)) goto LA18_;
		T19_ = (NIM_CHAR*)0;
		T19_ = X5BX5D___system_u8588((&result), ((NI)4));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T17_ = ((NU8)((*T19_)) == (NU8)(43));
LA18_: ;
		T16_ = T17_;
		if (!(T16_)) goto LA20_;
		T21_ = (NIM_CHAR*)0;
		T21_ = X5BX5D___system_u8588((&result), ((NI)3));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T16_ = ((NU8)((*T21_)) == (NU8)(48));
LA20_: ;
		if (!T16_) goto LA22_;
		T24_ = (NimStringV2*)0;
		T24_ = (&result);
		T25_ = (NIM_CHAR*)0;
		T25_ = X5BX5D___system_u8588((&result), ((NI)2));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		X5BX5Deq___system_u8603(T24_, ((NI)3), (*T25_));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T26_ = (NimStringV2*)0;
		T26_ = (&result);
		T27_ = (NIM_CHAR*)0;
		T27_ = X5BX5D___system_u8588((&result), ((NI)1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		X5BX5Deq___system_u8603(T26_, ((NI)2), (*T27_));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimSubInt(result.len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_125)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_125)) < ((NI)0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_125)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_125), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		setLengthStrV2((&result), ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_125)));
	}
LA22_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuformatFloat)(NF f_p0, tyEnum_FloatFormatMode__NktTD9agsSu9bXX0rEiwGseg format_p1, NI precision_p2, NIM_CHAR decimalSep_p3) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = nsuformatBiggestFloat(f_p0, format_p1, precision_p2, decimalSep_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuAlignString)(NimStringV2 s_p0, NI count_p1, NIM_CHAR padding_p2) {
	NimStringV2 result;
{	result.len = 0; result.p = NIM_NIL;
	{
		NI spaces_1;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_126;
		if (!(s_p0.len < count_p1)) goto LA3_;
		result = mnewString(count_p1);
		if (nimSubInt(count_p1, s_p0.len, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_126)) { raiseOverflow(); goto BeforeRet_;
		};
		spaces_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_126);
		{
			NI i_1;
			NI colontmp_;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_127;
			NI res_1;
			i_1 = (NI)0;
			colontmp_ = (NI)0;
			if (nimSubInt(spaces_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_127)) { raiseOverflow(); goto BeforeRet_;
			};
			colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_127);
			res_1 = ((NI)0);
			{
				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_128;
					if (!(res_1 <= colontmp_)) goto LA7;
					i_1 = ((NI) (res_1));
					if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					result.p->data[i_1] = padding_p2;
					if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_128)) { raiseOverflow(); goto BeforeRet_;
					};
					res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_128);
				} LA7: ;
			}
		}
		{
			NI i_2;
			NI colontmp__2;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_129;
			NI res_2;
			i_2 = (NI)0;
			colontmp__2 = (NI)0;
			if (nimSubInt(count_p1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_129)) { raiseOverflow(); goto BeforeRet_;
			};
			colontmp__2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_129);
			res_2 = spaces_1;
			{
				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_130;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_131;
					if (!(res_2 <= colontmp__2)) goto LA10;
					i_2 = ((NI) (res_2));
					if (i_2 < 0 || i_2 >= result.len){ raiseIndexError2(i_2,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					if (nimSubInt(i_2, spaces_1, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_130)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_130) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_130) >= s_p0.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_130),s_p0.len-1); goto BeforeRet_;
					}
					result.p->data[i_2] = s_p0.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_130)];
					if (nimAddInt(res_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_131)) { raiseOverflow(); goto BeforeRet_;
					};
					res_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_131);
				} LA10: ;
			}
		}
	}
	goto LA1_;
LA3_: ;
	{
		eqcopy___system_u2723((&result), s_p0);
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuRepeatStr)(NimStringV2 s_p0, NI n_p1) {
	NimStringV2 result;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_132;
{	result.len = 0; result.p = NIM_NIL;
	if (nimMulInt(n_p1, s_p0.len, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_132)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_132)) < ((NI)0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_132)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_132), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = rawNewString(((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_132)));
	{
		NI i_1;
		NI res_1;
		i_1 = (NI)0;
		res_1 = ((NI)1);
		{
			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_133;
				if (!(res_1 <= n_p1)) goto LA3;
				i_1 = ((NI) (res_1));
				prepareAdd((&result), s_p0.len + 0);
appendString((&result), s_p0);
				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_133)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_133);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
