/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing -DWIN32_LEAN_AND_MEAN -Os -fno-ident   -IC:\Bar\nim\lib -Ic:\UserProgram\nim\pipet\src -o c:\UserProgram\nim\pipet\releasecache\@pstd@smonotimes.nim.c.o c:\UserProgram\nim\pipet\releasecache\@pstd@smonotimes.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_MonoTime__Xl8F9bSUuuHb8Ha6XvoO9bGQ tyObject_MonoTime__Xl8F9bSUuuHb8Ha6XvoO9bGQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_Duration__gI3VhQmgIUikZXxJXHSNtA tyObject_Duration__gI3VhQmgIUikZXxJXHSNtA;
struct tyObject_MonoTime__Xl8F9bSUuuHb8Ha6XvoO9bGQ {
	NI64 ticks;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef N_STDCALL_PTR(void, tyProc__PD9b9cqhDqM6Xy1oSxwODsOQ) (NU64* res_p0);
struct tyObject_Duration__gI3VhQmgIUikZXxJXHSNtA {
	NI64 seconds;
	NI nanosecond;
};
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void*, nimLoadLibrary)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimLoadLibraryError)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimGetProcAddr)(void* lib_p0, NCSTRING name_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorNoArgs)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_Duration__gI3VhQmgIUikZXxJXHSNtA, initDuration__pureZtimes_u501)(NI64 nanoseconds_p0, NI64 microseconds_p1, NI64 milliseconds_p2, NI64 seconds_p3, NI64 minutes_p4, NI64 hours_p5, NI64 days_p6, NI64 weeks_p7);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__IP4V1hRabVpf8OnX9bWuPxw_4 = { 8 | NIM_STRLIT_FLAG, "kernel32" };
static const NimStringV2 TM__IP4V1hRabVpf8OnX9bWuPxw_5 = {8, (NimStrPayload*)&TM__IP4V1hRabVpf8OnX9bWuPxw_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__IP4V1hRabVpf8OnX9bWuPxw_6 = { 8 | NIM_STRLIT_FLAG, "kernel32" };
static const NimStringV2 TM__IP4V1hRabVpf8OnX9bWuPxw_7 = {8, (NimStrPayload*)&TM__IP4V1hRabVpf8OnX9bWuPxw_6};
static void* TM__IP4V1hRabVpf8OnX9bWuPxw_2;
tyProc__PD9b9cqhDqM6Xy1oSxwODsOQ Dl_2466250756_;
tyProc__PD9b9cqhDqM6Xy1oSxwODsOQ Dl_2466250758_;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4167;
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_MonoTime__Xl8F9bSUuuHb8Ha6XvoO9bGQ, getMonoTime__stdZmonotimes_u8)(void) {
	tyObject_MonoTime__Xl8F9bSUuuHb8Ha6XvoO9bGQ result;
	NU64 ticks_1;
	NU64 freq_1;
	NU64 queryPerformanceCounterFreq_1;
{	nimZeroMem((void*)(&result), sizeof(tyObject_MonoTime__Xl8F9bSUuuHb8Ha6XvoO9bGQ));
	ticks_1 = 0ULL;
	Dl_2466250756_((&ticks_1));
	freq_1 = 0ULL;
	Dl_2466250758_((&freq_1));
	queryPerformanceCounterFreq_1 = (NU64)((NU64)(1000000000ULL) / (NU64)(freq_1));
	if ((NU64)((NU64)(ticks_1) * (NU64)(queryPerformanceCounterFreq_1)) > (NU64)(IL64(9223372036854775807))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
	}
	result.ticks = ((NI64) ((NU64)((NU64)(ticks_1) * (NU64)(queryPerformanceCounterFreq_1))));
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4167);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Duration__gI3VhQmgIUikZXxJXHSNtA, minus___stdZmonotimes_u38)(tyObject_MonoTime__Xl8F9bSUuuHb8Ha6XvoO9bGQ a_p0, tyObject_MonoTime__Xl8F9bSUuuHb8Ha6XvoO9bGQ b_p1) {
	tyObject_Duration__gI3VhQmgIUikZXxJXHSNtA result;
	NI64 TM__IP4V1hRabVpf8OnX9bWuPxw_12;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Duration__gI3VhQmgIUikZXxJXHSNtA));
	if (nimSubInt64(a_p0.ticks, b_p1.ticks, &TM__IP4V1hRabVpf8OnX9bWuPxw_12)) { raiseOverflow(); goto BeforeRet_;
	};
	result = initDuration__pureZtimes_u501((NI64)(TM__IP4V1hRabVpf8OnX9bWuPxw_12), IL64(0), IL64(0), IL64(0), IL64(0), IL64(0), IL64(0), IL64(0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atpstdatsmonotimesdotnim_DatInit000)(void) {
if (!((TM__IP4V1hRabVpf8OnX9bWuPxw_2 = nimLoadLibrary(TM__IP4V1hRabVpf8OnX9bWuPxw_5))
)) nimLoadLibraryError(TM__IP4V1hRabVpf8OnX9bWuPxw_7);
	Dl_2466250756_ = (tyProc__PD9b9cqhDqM6Xy1oSxwODsOQ) nimGetProcAddr(TM__IP4V1hRabVpf8OnX9bWuPxw_2, "QueryPerformanceCounter");
	Dl_2466250758_ = (tyProc__PD9b9cqhDqM6Xy1oSxwODsOQ) nimGetProcAddr(TM__IP4V1hRabVpf8OnX9bWuPxw_2, "QueryPerformanceFrequency");
}

